capture rename   CattleHerdPurchasesCalvesNum   CATTLE_CALVES_PURCHASES_NO        
capture rename   CattleHerdPurchasesCalvesVal   CATTLE_CALVES_PURCHASES_EU        
capture rename   CattleHerdPurchasesWeanlings   CATTLE_WEANLINGS_PURCHASES_NO     
capture rename   F                              CATTLE_WEANLINGS_PURCHASES_EU     
capture rename   CattleHerdPurchasesStoresNum   TOTAL_STORES_PURCHASED_NO         
capture rename   CattleHerdPurchasesStoresVa    TOTAL_STORES_PURCHASED_EU         
capture rename   CattleHerdPurchasesBreedHerd   CATTLE_BREED_REPLACE_PURCH_NO     
capture rename   J                              CATTLE_BREED_REPLACE_PURCH_EU     
capture rename   CattleHerdPurchasesOtherNumb   CATTLE_OTHER_PURCHASES_NO         
capture rename   CattleHerdPurchasesOtherValu   CATTLE_OTHER_PURCHASES_EU         
capture rename   CattleHerdPurchasesTotalNumb   CATTLE_TOTAL_PURCHASES_NO         
capture rename   CattleHerdPurchasesTotalValu   CATTLE_TOTAL_PURCHASES_EU         
capture rename   CattleHerdUsedinHouseNumber    CATTLE_USED_IN_HOUSE_NO           
capture rename   CattleHerdUsedinHouseValue     CATTLE_USED_IN_HOUSE_EU           
capture rename   CattleHerdReceiptsforBullSe    CATTLE_RCPT_BULL_SERVICES_EU      
capture rename   CattleHerdSubsidiesValue       CATTLE_SUBSIDIES_EU               
