capture rename   PoultryClosingInventoryLayers  LAYERS_CLOS_INV_NO                 
capture rename   D                              LAYERS_CLOS_INV_PERUNIT_EU         
capture rename   PoultryClosingInventoryChicks  CHICKS_PULLETS_CLOS_INV_NO         
capture rename   F                              var22                              
capture rename   PoultryClosingInventoryTable   TABLE_FOWL_CLOS_INV_NO             
capture rename   H                              TABLE_FOWL_CLOS_INV_PERUNIT_EU     
capture rename   ClosingInventoryTotalNumber    TOTAL_ORDINARY_FOWL_CLOS_INV_NO    
capture rename   ClosingInventoryTurkeysNumber  TURKEYS_CLOS_INV_NO                
capture rename   ClosingInventoryTurkeysValue   TURKEYS_CLOS_INV_PERUNIT_EU        
capture rename   ClosingInventoryGeeseNumber    GEESE_CLOS_INV_NO                  
capture rename   ClosingInventoryGeeseValueun   GEESE_CLOS_INV_PERUNIT_EU          
capture rename   ClosingInventoryDucksNumber    DUCKS_CLOS_INV_NO                  
capture rename   ClosingInventoryDucksValueu    DUCKS_CLOS_INV_PERUNIT_EU          
capture rename   ClosingInventoryOthersNumber   OTHERS_CLOS_INV_NO                 
capture rename   ClosingInventoryOthersValueu   OTHERS_CLOS_INV_PERUNIT_EU         
capture rename   ClosingInventoryotherfowlTot   TOTAL_OTHER_FOWL_CLOS_INV_NO       
