capture rename   Paidcasuallabourallocatedto    var72                              
capture rename   D                              CASUAL_LABOUR_ALLOC_CATTLE_EU      
capture rename   E                              CASUAL_LABOUR_ALLOC_SHEEP_EU       
capture rename   F                              CASUAL_LABOUR_ALLOC_PIGS_EU        
capture rename   G                              CASUAL_LABOUR_ALLOC_POULTRY_EU     
capture rename   H                              CASUAL_LABOUR_ALLOC_OTHER_EU       
capture rename   PaidcasuallabourNonAllocable   CAS_LAB_NON_ALLOCABLE_EU           
capture rename   J                              CROP_CODE                          
capture rename   K                              ALLOCATED_TO_CROP_EU               
capture rename   L                              CROP_CODE                          
capture rename   M                              ALLOCATED_TO_CROP_EU               
capture rename   N                              CROP_CODE                          
capture rename   O                              ALLOCATED_TO_CROP_EU               
capture rename   P                              CROP_CODE                          
capture rename   Q                              ALLOCATED_TO_CROP_EU               
capture rename   R                              CROP_CODE                          
capture rename   S                              ALLOCATED_TO_CROP_EU               
capture rename   T                              CROP_CODE                          
capture rename   U                              ALLOCATED_TO_CROP_EU               
capture rename   PaidcasuallabourTotalAllocat   CAS_LAB_TOTAL_ALLOC_EU             
