capture rename   GroundCutOnceacres             HAY_1ST_GROUND_CUT_HA              
capture rename   GroundCutOnceofproduction      HAY_1ST_CUT_PRODUCTION_PERCENT     
capture rename   GroundCuttwiceacres            HAY_2ND_GROUND_CUT_HA              
capture rename   GroundCuttwiceofproductio      HAY_2ND_CUT_PRODUCTION_PERCENT     
capture rename   GroundCutthriceacres           HAY_3RD_GROUND_CUT_HA              
capture rename   GroundCutthriceofproducti      HAY_3RD_CUT_PRODUCTION_PERCENT     
capture rename   OpeningInventoryTotalValue     HAY_OP_INV_TOTAL_VALUE_EU          
capture rename   OpeningInventoryQuantitytonn   HAY_OP_INV_QTY_TONNES              
capture rename   TotalYieldtonnes               HAY_TOTAL_YIELD_TONNES             
capture rename   TotalAvailablefordisposal      HAY_TOTAL_AVAILABLE_TONNES         
capture rename   AmountFedtonnes                HAY_FED_QUANTITY_TONNES            
capture rename   AmountSoldtonnes               HAY_SALES_QUANTITY_TONNES          
capture rename   ValueSold                      HAY_SALES_VALUE_EU                 
capture rename   Allowancestonnes               HAY_ALLOW_QUANTITY_TONNES          
capture rename   AllowancesTotalvalue           HAY_ALLOW_VALUE_EU                 
capture rename   Wastetonnes                    HAY_WASTE_QUANTITY_TONNES          
capture rename   ClosingInventorytonnes         HAY_CLOSING_INV_QUANTITY_TONNES    
