capture rename   OpeningInventoryOtherCowsNum   CATTLE_OTHER_COWS_OP_INV_NO        
capture rename   OpeningInventoryOtherCowsH     CATTLE_OTHER_COWS_OP_INV_EU        
capture rename   OpeningInventoryInCalfHeifer   CATTLE_IN_CALF_HEIFERS_OP_INV_NO   
capture rename   F                              CATTLE_IN_CALF_HEIFERS_OP_INV_EU   
capture rename   DroppedCalvesNo                DROPPED_CALVES_C21_NO              
capture rename   DroppedCalves                  DROPPED_CALVES_C21_EU              
capture rename   OpeningInventoryCalveslessth   CATTLE_CALVES_LT6MTHS_OP_INV_NO    
capture rename   J                              CATTLE_CALVES_LT6MTHS_OP_INV_EU    
capture rename   OpeningInventoryCalves6month   var54                              
capture rename   L                              var55                              
capture rename   OpeningInventoryMaleCattle1    CATTLE_MALE_1_2YRS_OP_INV_NO       
capture rename   N                              CATTLE_MALE_1_2YRS_OP_INV_EU       
capture rename   OpeningInventoryFemaleCattle   CATTLE_FEMALE_1_2YRS_OP_INV_NO     
capture rename   P                              CATTLE_FEMALE_1_2YRS_OP_INV_EU     
capture rename   OpeningInventoryMaleCattle2    CATTLE_MALE_2_3YRS_OP_INV_NO       
capture rename   R                              CATTLE_MALE_2_3YRS_OP_INV_EU       
capture rename   OpeningInventoryfemaleCattle   CATTLE_FEMALE_2_3YRS_OP_INV_NO     
capture rename   T                              CATTLE_FEMALE_2_3YRS_OP_INV_EU     
capture rename   OpeningInventoryStockBullsNu   CATTLE_STOCK_BULLS_OP_INV_NO       
capture rename   OpeningInventoryStockBulls     CATTLE_STOCK_BULLS_OP_INV_EU       
capture rename   OpeningInventorTotalNumber     CATTLE_TOTAL_OP_INV_NO             
