capture rename   EggsusedinHousedoz             EGGS_DOZ_USED_IN_HOUSE_NO          
capture rename   EggsusedinHouseValue           EGGS_DOZ_USED_IN_HOUSE_EU          
capture rename   EggsusedinWagesdoz             EGGS_DOZ_WAGES_NO                  
capture rename   EggsusedinWagesValue           EGGS_DOZ_WAGES_EU                  
capture rename   EggsusedinOtherdoz             EGGS_DOZ_OTHER_ALLOWANCES_NO       
capture rename   EggsusedinOtherValue           EGGS_DOZ_OTHER_ALLOWANCES_EU       
capture rename   OrdinaryFowlusedinHouseNumb    ORDINARY_FOWL_USED_IN_HOUSE_NO     
capture rename   OrdinaryFowlusedinHouseValu    ORDINARY_FOWL_USED_IN_HOUSE_EU     
capture rename   OrdinaryFowlusedinWagesNumb    ORDINARY_FOWL_WAGES_NO             
capture rename   OrdinaryFowlusedinWagesValu    ORDINARY_FOWL_WAGES_EU             
capture rename   OrdinaryFowlusedinOtherNumb    var58                              
capture rename   OrdinaryFowlusedinOtherValu    var59                              
capture rename   OtherFowlusedinHouseNumber     OTHER_FOWL_USED_IN_HOUSE_NO        
capture rename   OtherFowlusedinHouseValue      OTHER_FOWL_USED_IN_HOUSE_EU        
capture rename   OtherFowlusedinWagesNumber     OTHER_FOWL_WAGES_NO                
capture rename   OtherFowlusedinWagesValue      OTHER_FOWL_WAGES_EU                
capture rename   OtherFowlusedinOtherNumber     OTHER_FOWL_OTHER_ALLOWANCES_NO     
capture rename   OtherFowlusedinOtherValue      OTHER_FOWL_OTHER_ALLOWANCES_EU     
capture rename   Poultry12MonthTotalsLaying     MTH12_TOTAL_LAYING_BIRDS_NO        
capture rename   Poultry12MonthTotalsChicks     MTH12_TOTAL_CHICKS_PULLETS_NO      
capture rename   Poultry12MonthTotalsTable      MTH12_TOTAL_TABLE_FOWL_NO          
capture rename   Poultry12MonthTotalsOther      MTH12_TOTAL_OTHER_FOWL_NO          
capture rename   Poultry12MonthTotalsAllFo      MTH12_TOTAL_ALL_FOWL_NO            
capture rename   PoultrySystemCode              SYSTEM_CODE                        
