capture rename   CommonageDairyCattleNoof       COMMONAGE_DAIRY_ANIMALS_NO         
capture rename   D                              COMMONAGE_DAIRY_DAYS_NO            
capture rename   CommonageDairyCattle           COMMONAGE_DAIRY_EU                 
capture rename   CommonageDairyCattleLUEq       COMMONAGE_DAIRY_LU_EQUIV           
capture rename   G                              COMMONAGE_CATTLE1_ANIMALS_NO       
capture rename   H                              COMMONAGE_CATTLE1_DAYS_NO          
capture rename   I                              COMMONAGE_CATTLE1_EU               
capture rename   J                              COMMONAGE_CATTLE1_LU_EQUIV         
capture rename   K                              COMMONAGE_CATTLE2_ANIMALS_NO       
capture rename   L                              COMMONAGE_CATTLE2_DAYS_NO          
capture rename   M                              COMMONAGE_CATTLE2_EU               
capture rename   N                              COMMONAGE_CATTLE2_LU_EQUIV         
capture rename   CommonageSheep1NoofAnimals     COMMONAGE_SHEEP1_ANIMALS_NO        
capture rename   CommonageSheep1NoofDays        COMMONAGE_SHEEP1_DAYS_NO           
capture rename   CommonageSheep1                COMMONAGE_SHEEP1_EU                
capture rename   CommonageSheep1LUEquivalen     COMMONAGE_SHEEP1_LU_EQUIV          
capture rename   CommonageSheep2NoofAnimals     COMMONAGE_SHEEP2_ANIMALS_NO        
capture rename   CommonageSheep2NoofDays        COMMONAGE_SHEEP2_DAYS_NO           
capture rename   CommonageSheep2                COMMONAGE_SHEEP2_EU                
capture rename   CommonageSheep2LUEquivalen     COMMONAGE_SHEEP2_LU_EQUIV          
capture rename   CommonageHorsesNoofAnimals     COMMONAGE_HORSES_ANIMALS_NO        
capture rename   CommonageHorsesNoofDays        COMMONAGE_HORSES_DAYS_NO           
capture rename   CommonageHorses                COMMONAGE_HORSES_EU                
capture rename   CommonageHorsesLUEquivalent    COMMONAGE_HORSES_LU_EQUIV          
