capture rename   NoofUnits1                     C48_UNITS_NO_1                    
capture rename   ValUnit1                       C48_VAL_PER_UNIT_1                
capture rename   NoofUnits2                     C48_UNITS_NO_2                    
capture rename   ValUnit2                       C48_VAL_PER_UNIT_2                
capture rename   NoofUnits3                     C48_UNITS_NO_3                    
capture rename   ValUnit3                       C48_VAL_PER_UNIT_3                
capture rename   NoofUnits4                     C48_UNITS_NO_4                    
capture rename   ValUnit4                       C48_VAL_PER_UNIT_4                
capture rename   NoofUnits5                     C48_UNITS_NO_5                    
capture rename   ValUnit5                       C48_VAL_PER_UNIT_5                
capture rename   ToTalUnits                     C48_TOTAL_UNITS                   
