capture rename   PurchasesCode                  C49_PURCHASES_CODE                 
capture rename   Purchases                      C49_PURCHASES_EU                   
capture rename   SalesCode                      C49_SALES_CODE                     
capture rename   Sales                          C49_SALES_EU                       
capture rename   UsedinHouseCode                C49_USED_IN_HOUSE_CODE             
capture rename   UsedinHouse                    C49_USED_IN_HOUSE_EU               
capture rename   WagesCode                      C49_WAGES_CODE                     
capture rename   Wages                          C49_WAGES_EU                       
capture rename   OtherCode                      C49_OTHER_CODE                     
capture rename   Other                          C49_OTHER_EU                       
capture rename   DirectCostsCode                C49_DIRECT_COSTS_CODE              
capture rename   DirectCosts                    C49_DIRECT_COSTS_EU                
capture rename   SubsidiesCode                  C49_SUBSIDIES_CODE                 
capture rename   Subsidies                      C49_SUBSIDIES_EU                   
