capture rename   HorsesClosingInventoryBreedin  var27                              
capture rename   D                              var28                              
capture rename   E                              var29                              
capture rename   F                              var30                              
capture rename   HorsesClosingInventoryOtherS   HORSES_OTHER_STOCK1_CLOS_INV_NO    
capture rename   H                              var32                              
capture rename   HorsesClosingInventoryNumber   HORSES1_CLOS_INV_NO                
capture rename   HorsesClosingInventoryValue    HORSES1_CLOS_INV_PERUNIT_EU        
capture rename   K                              HORSES2_CLOS_INV_NO                
capture rename   L                              HORSES2_CLOS_INV_PERUNIT_EU        
capture rename   M                              HORSES3_CLOS_INV_NO                
capture rename   N                              HORSES3_CLOS_INV_PERUNIT_EU        
capture rename   O                              HORSES4_CLOS_INV_NO                
capture rename   P                              HORSES4_CLOS_INV_PERUNIT_EU        
capture rename   HorsesClosingInventoryTotal    TOTAL_HORSES_CLOS_INV_NO           
capture rename   ClosingInventoryNumber         CLOS_INV_NO                        
capture rename   ClosingInventoryValuehd        CLOS_INV_PERUNIT_EU                
capture rename   ClosingInventoryBreedingAnima  BREEDING_ANIMALS_CLOS_INV_NO       
capture rename   U                              var45                              
capture rename   ClosingInventoryOthersNumber   OTHERS_CLOS_INV_NO                 
capture rename   ClosingInventoryOthersValueh   OTHERS_CLOS_INV_PERUNIT_EU         
