capture rename   PigsSystemCode                 PigsSystemCode                    
capture rename   PigsNoofFarrowings             FARROWINGS_NO                     
capture rename   PigsLiveBirths                 BIRTHS_LIVE_NO                    
capture rename   PigsDeathsbeforeweaning        DEATHS_PRE_WEANING_NO             
capture rename   PigsDeathsFatteners            DEATHS_FATTENERS_NO               
capture rename   PigsDeathsOthers               DEATHS_OTHERS_NO                  
capture rename   Pigs12MonthTotalSows           MTH12_TOTAL_SOWS_NO               
capture rename   Pigs12MonthTotalGiltsinPig     MTH12_TOTAL_GILTS_IN_PIG_NO       
capture rename   Pigs12MonthTotalBonhamsbefo    MTH12_TOTAL_BONHAMS_PRE_WEAN_NO   
capture rename   Pigs12MonthTotalWeaners        MTH12_TOTAL_WEANERS_NO            
capture rename   Pigs12MonthTotalFatteners      MTH12_TOTAL_FATTENERS_NO          
capture rename   Pigs12MonthTotalFatteningSo    MTH12_TOTAL_FATTENING_SOWS_NO     
capture rename   Pigs12MonthTotalStockBoars     MTH12_TOTAL_STOCK_BOARS_NO        
capture rename   Pigs12MonthTotal               MTH12_TOTAL_ALL_PIGS_NO           
