capture rename   GroundCutOnceacres             SIL_1ST_GROUND_CUT_HA             
capture rename   GroundCutOnceofproduction      SIL_1ST_CUT_PRODUCTION_PERCENT    
capture rename   GroundCuttwiceacres            SIL_2ND_GROUND_CUT_HA             
capture rename   GroundCuttwiceofproductio      SIL_2ND_CUT_PRODUCTION_PERCENT    
capture rename   GroundCutthriceacres           SIL_3RD_GROUND_CUT_HA             
capture rename   GroundCutthriceofproducti      SIL_3RD_CUT_PRODUCTION_PERCENT    
capture rename   OpeningInventoryTotalValue     SIL_OP_INV_TOTAL_VALUE_EU         
capture rename   OpeningInventoryQuantitytonn   SIL_OP_INV_QTY_TONNES             
capture rename   TotalYieldtonnes               SIL_TOTAL_YIELD_TONNES            
capture rename   TotalAvailablefordisposal      SIL_TOTAL_AVAILABLE_TONNES        
capture rename   AmountFedtonnes                SIL_FED_QUANTITY_TONNES           
capture rename   AmountSoldtonnes               SIL_SALES_QUANTITY_TONNES         
capture rename   ValueSold                      SIL_SALES_VALUE_EU                
capture rename   Allowancestonnes               SIL_ALLOW_QUANTITY_TONNES         
capture rename   AllowancesTotalvalue           SIL_ALLOW_VALUE_EU                
capture rename   Wastetonnes                    SIL_WASTE_QUANTITY_TONNES         
capture rename   ClosingInventorytonnes         SIL_CLOSING_INV_QUANTITY_TONNES   
