capture rename   CattleHerdSalesCalvesNumber    CATTLE_CALVES_SALES_NO             
capture rename   CattleHerdSalesCalvesValue     CATTLE_CALVES_SALES_EU             
capture rename   CattleHerdSalesWeanlingsNumb   CATTLE_WEANLINGS_SALES_NO          
capture rename   CattleHerdSalesWeanlingsValu   CATTLE_WEANLINGS_SALES_EU          
capture rename   CattleHerdSalesBreedHerdCul    var124                             
capture rename   L                              var125                             
capture rename   CattleHerdSalesOtherNumber     CATTLE_OTHER_SALES_NO              
capture rename   CattleHerdSalesOtherValue      CATTLE_OTHER_SALES_EU              
capture rename   CattleHerdSalesTotalNumber     CATTLE_TOTAL_SALES_NO              
capture rename   CattleHerdSalesTotalValue      CATTLE_TOTAL_SALES_EU              
