capture rename   CropCode                       CROP_CODE                         
capture rename   PurchasedSeed                  PURCHASED_SEED_EU                 
capture rename   CropProtection                 CROP_PROTECTION_EU                
capture rename   TransportGrossCost             TRANSPORT_GROSS_COST_EU           
capture rename   TransportSubsidy               TRANSPORT_SUBSIDY_EU              
capture rename   MachineryHire                  MACHINERY_HIRE_EU                 
capture rename   Miscellaneous                  MISCELLANEOUS_EU                  
capture rename   Total                          TOTAL_EU                          
capture rename   HomeGrownseedvalue             HOME_GROWN_SEED_VALUE_EU          
