capture rename   CalvesSalesNumber              DAIRY_CALVES_SALES_NO              
capture rename   CalvesSalesValue               DAIRY_CALVES_SALES_EU              
capture rename   CalvesTransfersNumber          DAIRY_CALVES_TRANSFER_NO           
capture rename   CalvesTransfersValue           DAIRY_CALVES_TRANSFER_EU           
capture rename   CowsSpringingHeifersBulls      DAIRY_COWS_SH_BULLS_PURCHASES_NO   
capture rename   H                              DAIRY_COWS_SH_BULLS_PURCHASES_EU   
capture rename   SalesDairyCowsNo               DAIRY_COWS_SALES_NO                
capture rename   SalesDairyCowsValue            DAIRY_COWS_SALES_VALUE_EU          
capture rename   K                              var35                              
capture rename   L                              var36                              
capture rename   M                              var37                              
capture rename   N                              var38                              
capture rename   DairySubsidiesValue            DAIRY_SUPPORT_VALUE_EU             
