capture rename   TransportAllocatedtoPigs       TRANSPORT_ALLOC_PIGS_EU           
capture rename   MiscellaneousAllocatedtoPigs   MISCELLANEOUS_ALLOC_PIGS_EU       
capture rename   TransportAllocatedtoPoultry    TRANSPORT_ALLOC_POULTRY_EU        
capture rename   MiscellaneousAllocatedtoPoult  MISCELLANEOUS_ALLOC_POULTRY_EU    
capture rename   TransportAllocatedtoDairyHer   TRANSPORT_ALLOC_DAIRY_HERD_EU     
capture rename   MiscellaneousAllocatedtoDairy  MISC_ALLOC_DAIRY_HERD_EU          
capture rename   TransportAllocatedtoCattle     TRANSPORT_ALLOC_CATTLE_EU         
capture rename   MiscellaneousAllocatedtoCattl  MISCELLANEOUS_ALLOC_CATTLE_EU     
capture rename   TransportAllocatedtoSheep      TRANSPORT_ALLOC_SHEEP_EU          
capture rename   MiscellaneousAllocatedtoSheep  MISCELLANEOUS_ALLOC_SHEEP_EU      
capture rename   TransportAllocatedtoHorses     TRANSPORT_ALLOC_HORSES_EU         
capture rename   MiscellaneousAllocatedtoHorse  MISCELLANEOUS_ALLOC_HORSES_EU     
capture rename   TransportAllocatedtoother      TRANSPORT_ALLOC_OTHER_GRAZING_EU  
capture rename   MiscellaneousAllocatedtoother  MISC_ALLOC_OTHER_GRAZING_EU       
capture rename   TotalTransportMiscCostsAl      TRANS_MISC_EXP_TOTAL_ALLOC_EU     
