capture rename   Acres                          CY_HECTARES_HA                     
capture rename   TotalYield                     CY_TOTAL_YIELD                     
capture rename   SalesQuantitytonsAc            CY_SALES_QTY_TONNES_HA             
capture rename   SalesValue                     CY_SALES_VALUE_EU                  
capture rename   FedQuantitytonsAc              CY_FED_QTY_TONNES_HA               
capture rename   FedValue                       CY_FED_VALUE_EU                    
capture rename   SeedQuantitytonsAc             CY_SEED_QTY_TONNES_HA              
capture rename   SeedValue                      CY_SEED_VALUE_EU                   
capture rename   AllowancesHousetonsAc          CY_ALLOW_HOUSE_TONNES_HA           
capture rename   AllowancesWagestonsAc          CY_ALLOW_WAGES_TONNES_HA           
capture rename   WastetonsAc                    CY_WASTE_TONNES_HA                 
capture rename   ClosingInventoryQuantityto     CY_CLOSING_QTY_TONNES_HA           
capture rename   ClosingInventoryValue          CY_CLOSING_VALUE_EU                
