capture rename   closingInventoryOtherCowsNum   CATTLE_OTHER_COWS_CLOS_INV_NO     
capture rename   closingInventoryOtherCowsH     CATTLE_OTHER_COWS_CLOS_INV_EU     
capture rename   closingInventoryInCalfHeifer   CATTLE_IN_CALF_HF_CLOS_INV_NO     
capture rename   F                              CATTLE_IN_CALF_HF_CLOS_INV_EU     
capture rename   DroppedCalvesNo                DROPPED_CALVES_C22_NO             
capture rename   DroppedCalves                  DROPPED_CALVES_C22_EU             
capture rename   closingInventoryCalveslessth   CATTLE_CALVES_LT6M_CLOS_INV_NO    
capture rename   J                              CATTLE_CALVES_LT6M_CLOS_INV_EU    
capture rename   closingInventoryCalves6month   CATTLE_CALVES_6M_1YR_CLOS_INV_NO  
capture rename   L                              CATTLE_CALVES_6M_1YR_CLOS_INV_EU  
capture rename   closingInventoryMaleCattle1    CATTLE_MALE_1_2YRS_CLOS_INV_NO    
capture rename   N                              CATTLE_MALE_1_2YRS_CLOS_INV_EU    
capture rename   closingInventoryFemaleCattle   CATTLE_FEMALE_1_2YRS_CLOS_INV_NO  
capture rename   P                              CATTLE_FEMALE_1_2YRS_CLOS_INV_EU  
capture rename   closingInventoryMaleCattle2    CATTLE_MALE_2_3YRS_CLOS_INV_NO    
capture rename   R                              CATTLE_MALE_2_3YRS_CLOS_INV_EU    
capture rename   closingInventoryfemaleCattle   CATTLE_FEMALE_2_3YRS_CLOS_INV_NO  
capture rename   T                              CATTLE_FEMALE_2_3YRS_CLOS_INV_EU  
capture rename   closingInventoryStockBullsNu   CATTLE_STOCK_BULLS_CLOS_INV_NO    
capture rename   closingInventoryStockBulls     CATTLE_STOCK_BULLS_CLOS_INV_EU    
capture rename   closingInventorTotalNumber     CATTLE_TOTAL_CLOS_INV_NO          
