capture rename   CalfBirthsJanuary              BIRTHS_JAN_NO                      
capture rename   CalfBirthsFebruary             BIRTHS_FEB_NO                      
capture rename   CalfBirthsMarch                BIRTHS_MAR_NO                      
capture rename   CalfBirthsApril                BIRTHS_APR_NO                      
capture rename   CalfBirthsMay                  BIRTHS_MAY_NO                      
capture rename   CalfBirthsJune                 BIRTHS_JUN_NO                      
capture rename   CalfBirthsJuly                 BIRTHS_JUL_NO                      
capture rename   CalfBirthsAugust               BIRTHS_AUG_NO                      
capture rename   CalfBirthsSeptember            BIRTHS_SEP_NO                      
capture rename   CalfBirthsOctober              BIRTHS_OCT_NO                      
capture rename   CalfBirthsNovember             BIRTHS_NOV_NO                      
capture rename   CalfBirthsDecember             BIRTHS_DEC_NO                      
capture rename   CalfBirthsTotal                BIRTHS_TOTAL_NO                    
capture rename   CattleDeathslessthan6Months    DEATHS_LT6MTHS_NO                  
capture rename   CattleDeathsGreaterthan6Mon    DEATHS_GT6MTHS_NO                  
capture rename   CattleDeathsAllCows            DEATHS_CATTLE_HERD_COWS_NO         
capture rename   DeadCalfBirths                 DEATHS_CALVES_AT_BIRTH_NO          
