capture rename   OpeningInventoryQuantityto     OP_INV_QTY_TONNES_HA               
capture rename   OpeningInventoryValue          OP_INV_VALUE_EU                    
capture rename   SalesQuantitytonsha            OP_INV_SALES_QTY_TONNES_HA         
capture rename   SalesValue                     OP_INV_SALES_VALUE_EU              
capture rename   FedQuantitytonsha              OP_INV_FED_QTY_TONNES_HA           
capture rename   FedValue                       OP_INV_FED_VALUE_EU                
capture rename   SeedQuantity                   OP_INV_SEED_QTY_TONNES_HA          
capture rename   SeedValue                      OP_INV_SEED_VALUE_EU               
capture rename   AllowancesHousetonshaa         OP_INV_ALLOW_HOUSE_TONNES_HA       
capture rename   AllowancesWagestonsha          OP_INV_ALLOW_WAGES_TONNES_HA       
capture rename   Wastetonsha                    OP_INV_WASTE_TONNES_HA             
capture rename   ClosingInventoryQuantityto     OP_INV_CLOSING_QTY_TONNES_HA       
capture rename   ClosingInventoryValue          OP_INV_CLOSING_VALUE_EU            
