capture rename   FarmBuildingsTOTALOriginalGr   TOTAL_ORIGINAL_GROSS_COST_EU       
capture rename   D                              TOTAL_ORIGINAL_GRANT_EU            
capture rename   FarmBuildingsbeginningofyear   TAKE_ON_YEAR                       
capture rename   FarmBuildingsNewThisYear       TOTAL_NEW_BUILDINGS_EU             
capture rename   FarmBuildingsTOTALMajorRepai   TOTAL_MAJOR_REPAIRS_EU             
capture rename   FarmBuildingsGrantrecforinv    TOTAL_GRANTS_EU                    
capture rename   FarmBuildingsDepreciation      HIST_DEP_VALUE                     
capture rename   FarmBuildingsendValue          HIST_NET_VALUE                     
capture rename   K                              BLD_GrantRecPrevYear               
