capture rename   FuelLubricantsOpeningInve      MACHINERY_FUEL_LUBS_OP_INV_EU     
capture rename   FuelLubricantsPurchases        MACHINERY_FUEL_LUBS_PURCHASES_EU  
capture rename   FuelLubricantsClosingInve      MACHINERY_FUEL_LUBS_CLOS_INV_EU   
capture rename   MachineryRepairsMinor          MACHINERY_MINOR_REPAIRS_EU        
capture rename   MachineryTax                   MACHINERY_TAX_EU                  
capture rename   MachineryInsurance             MACHINERY_INSURANCE_EU            
capture rename   RepairsGeneralUpkeeptoFarm     BUILDINGS_REPAIRS_UPKEEP_EU       
capture rename   FireInsuranceforFarmBuilding   BUILDINGS_FIRE_INSURANCE_EU       
capture rename   GeneralUpkeepofLand            LAND_GENERAL_UPKEEP_EU            
