capture rename   PurchasedConcentrateAllocated  var11                              
capture rename   D                              var12                              
capture rename   E                              CONC_ALLOC_CATTLE_50KGBAGS_NO      
capture rename   F                              CONC_ALLOC_CATTLE_50KGBAGS_EU      
capture rename   G                              CONC_ALLOC_SHEEP_50KGBAGS_NO       
capture rename   H                              CONC_ALLOC_SHEEP_50KGBAGS_EU       
capture rename   I                              CONC_ALLOC_HORSES_50KGBAGS_NO      
capture rename   J                              CONC_ALLOC_HORSES_50KGBAGS_EU      
capture rename   K                              CONC_ALLOC_PIGS_50KGBAGS_NO        
capture rename   L                              CONC_ALLOC_PIGS_50KGBAGS_EU        
capture rename   M                              CONC_ALLOC_POULTRY_50KGBAGS_NO     
capture rename   N                              CONC_ALLOC_POULTRY_50KGBAGS_EU     
capture rename   O                              CONC_ALLOC_OTHER_50KGBAGS_NO       
capture rename   P                              CONC_ALLOC_OTHER_50KGBAGS_EU       
capture rename   Q                              CONC_ALLOC_WASTE_50KGBAGS_NO       
capture rename   R                              CONC_ALLOC_WASTE_50KGBAGS_EU       
capture rename   PurchasedConcentrateTotalAllo  CONC_ALLOC_TOTAL_50KGBAGS_NO       
capture rename   T                              CONC_ALLOC_TOTAL_50KGBAGS_EU       
capture rename   MilkSubstitutefedtoCalves50    var33                              
capture rename   MilkSubstitutefedtoCalvesCo    var34                              
