capture rename   VetMedAIOpeningInvento         VET_MED_AI_OP_INV_EU               
capture rename   VetMedAIPurchasedDurin         VET_MED_AI_PURCHASED_EU            
capture rename   VetMedAIClosingInvento         VET_MED_AI_CLOS_INV_EU             
capture rename   VetMedicinetoPigs              VET_MED_ALLOC_PIGS_EU              
capture rename   AIServiceFeestoPigs            AI_SERVICE_FEES_ALLOC_PIGS_EU      
capture rename   VetMedicineEtctoPoultry        VET_MED_ETC_ALLOC_POULTRY_EU       
capture rename   VetMedicinetoDairyHerd         VET_MED_ALLOC_DAIRY_HERD_EU        
capture rename   AIServiceFeestoDairyHer        var39                              
capture rename   VetMedicinetoCattle            VET_MED_ALLOC_CATTLE_EU            
capture rename   AIServiceFeestoCattle          AI_SERVICE_FEES_ALLOC_CATTLE_EU    
capture rename   VetMedicinetoSheep             VET_MED_ALLOC_SHEEP_EU             
capture rename   AIServiceFeestoSheep           AI_SERVICE_FEES_ALLOC_SHEEP_EU     
capture rename   VetMedicinetoHorses            VET_MED_ALLOC_HORSES_EU            
capture rename   AIServiceFeestoHorses          AI_SERVICE_FEES_ALLOC_HORSES_EU    
capture rename   TotalAllocated                 var52                              
