capture rename   GrantsSubsidiesMiscellaneous   MISC_GRANTS_SUBSIDIES_EU          
capture rename   D                              MISC_GRANTS_SUBS_PREV_YEARS_EU    
capture rename   HiredMachineryInCash           HIRED_MACHINERY_IN_CASH_EU        
capture rename   HiredMachineryInKind           HIRED_MACHINERY_IN_KIND_EU        
capture rename   OtherReceiptsInCash            OTHER_RECEIPTS_IN_CASH_EU         
capture rename   OtherReceiptsInKind            OTHER_RECEIPTS_IN_KIND_EU         
capture rename   Total                          TOTAL_MISC_RECEIPTS_EU            
capture rename   OtherMiscellaneousExpensesin   OTHER_MISC_EXPENSES_IN_CASH_EU    
capture rename   K                              OTHER_MISC_EXPENSES_IN_KIND_EU    
capture rename   Electricityfarmshare           ELECTRICITY_FARM_SHARE_EU         
capture rename   Telephonefarmshare             TELEPHONE_FARM_SHARE_EU           
capture rename   UsedinHouseOther               USED_IN_HOUSE_OTHER_EU            
capture rename   Carfarmshare                   FARM_SHARE_PERCENTAGE             
capture rename   P                              TOTAL_MISC_EXPENSES_EU            
