capture rename   BoardingoutDairyCattleNo       BOARDING_OUT_DAIRY_ANIMALS_NO      
capture rename   D                              BOARDING_OUT_DAIRY_DAYS_NO         
capture rename   BoardingoutDairyCattle         BOARDING_OUT_DAIRY_EU              
capture rename   BoardingoutDairyCattleLU       BOARDING_OUT_DAIRY_LU_EQUIV        
capture rename   G                              BOARDING_OUT_CATTLE1_ANIMALS_NO    
capture rename   H                              BOARDING_OUT_CATTLE1_DAYS_NO       
capture rename   I                              BOARDING_OUT_CATTLE1_EU            
capture rename   J                              BOARDING_OUT_CATTLE1_LU_EQUIV      
capture rename   K                              BOARDING_OUT_CATTLE2_ANIMALS_NO    
capture rename   L                              BOARDING_OUT_CATTLE2_DAYS_NO       
capture rename   M                              BOARDING_OUT_CATTLE2_EU            
capture rename   N                              BOARDING_OUT_CATTLE2_LU_EQUIV      
capture rename   BoardingoutSheep1NoofAnim      BOARDING_OUT_SHEEP1_ANIMALS_NO     
capture rename   BoardingoutSheep1NoofDays      BOARDING_OUT_SHEEP1_DAYS_NO        
capture rename   BoardingoutSheep1              BOARDING_OUT_SHEEP1_EU             
capture rename   BoardingoutSheep1LUEquiva      BOARDING_OUT_SHEEP1_LU_EQUIV       
capture rename   BoardingoutSheep2NoofAnim      BOARDING_OUT_SHEEP2_ANIMALS_NO     
capture rename   BoardingoutSheep2NoofDays      BOARDING_OUT_SHEEP2_DAYS_NO        
capture rename   BoardingoutSheep2              BOARDING_OUT_SHEEP2_EU             
capture rename   BoardingoutSheep2LUEquiva      BOARDING_OUT_SHEEP2_LU_EQUIV       
capture rename   BoardingoutHorsesNoofAnima     BOARDING_OUT_HORSES_ANIMALS_NO     
capture rename   BoardingoutHorsesNoofDays      BOARDING_OUT_HORSES_DAYS_NO        
capture rename   BoardingoutHorses              BOARDING_OUT_HORSES_EU             
capture rename   BoardingoutHorsesLUEquival     BOARDING_OUT_HORSES_LU_EQUIV       
