capture rename   closingInventoryOtherCowsNum   CATTLE_OTHER_COWS_CLOS_INV_NO      
capture rename   closingInventoryOtherCowsH     CATTLE_OTHER_COWS_CLOS_INV_EU      
capture rename   closingInventoryInCalfHeifer   var71                              
capture rename   F                              var72                              
capture rename   DroppedCalvesNo                DROPPED_CALVES_C22_NO              
capture rename   DroppedCalves                  DROPPED_CALVES_C22_EU              
capture rename   closingInventoryCalveslessth   var75                              
capture rename   J                              var76                              
capture rename   closingInventoryCalves6month   var77                              
capture rename   L                              var78                              
capture rename   closingInventoryMaleCattle1    CATTLE_MALE_1_2YRS_CLOS_INV_NO     
capture rename   N                              CATTLE_MALE_1_2YRS_CLOS_INV_EU     
capture rename   closingInventoryFemaleCattle   CATTLE_FEMALE_1_2YRS_CLOS_INV_NO   
capture rename   P                              CATTLE_FEMALE_1_2YRS_CLOS_INV_EU   
capture rename   closingInventoryMaleCattle2    CATTLE_MALE_2_3YRS_CLOS_INV_NO     
capture rename   R                              CATTLE_MALE_2_3YRS_CLOS_INV_EU     
capture rename   closingInventoryfemaleCattle   CATTLE_FEMALE_2_3YRS_CLOS_INV_NO   
capture rename   T                              CATTLE_FEMALE_2_3YRS_CLOS_INV_EU   
capture rename   closingInventoryStockBullsNu   CATTLE_STOCK_BULLS_CLOS_INV_NO     
capture rename   closingInventoryStockBulls     CATTLE_STOCK_BULLS_CLOS_INV_EU     
capture rename   closingInventorTotalNumber     CATTLE_TOTAL_CLOS_INV_NO           
