capture rename   StandardManDaysDairyCows       DAIRY_COWS                         
capture rename   StandardManDaysSuckling        SUCKLING                           
capture rename   StandardManDaysCattle1Year     CATTLE_LT1YR                       
capture rename   StandardManDays12YearsOld      CATTLE_1_2YRS                      
capture rename   StandardManDays23YearsOld      CATTLE_2_3YRS                      
capture rename   StandardManDaysSheepEwes       SHEEP_EWES                         
capture rename   StandardManDaysHoggets         SHEEP_HOGGETS                      
capture rename   StandardManDaysPigsSows        PIGS_SOWS                          
capture rename   StandardManDaysFatteners       PIGS_FATTENERS                     
capture rename   StandardManDaysPoultryHensL    POULTRY_HENS_LAYERS                
capture rename   StandardManDaysTableFowl       POULTRY_TABLE_FOWL                 
capture rename   StandardManDaysPullets         POULTRY_PULLETS                    
capture rename   StandardManDaysOtherFowlT      POULTRY_OTHER_FOWL_TURKEYS         
capture rename   StandardManDaysHorsesDraug     HORSES_DRAUGHT                     
capture rename   StandardManDaysLessthan2ye     HORSES_LT2YRS                      
capture rename   StandardManDaysOver2yearso     HORSES_GT2YRS                      
capture rename   StandardManDaysOtherPonies     HORSES_PONIES_MULES                
capture rename   StandardManDaysCereals         CEREALS                            
capture rename   StandardManDaysSugarBeet       SUGAR_BEET                         
capture rename   StandardManDaysPotatoesProc    POTATOES_PROCESSING                
capture rename   StandardManDaysPotatoesWare    POTATOES_WARE                      
capture rename   StandardManDaysVegetableCrop   VEGETABLE_CROPS                    
capture rename   StandardManDaysSilageCode      SILAGE_CODE                        
capture rename   forageacresHandFedacres        FORAGE_HAND_FED_HA                 
capture rename   forageacresHandFeddays         FORAGE_HAND_FED_DAYS               
capture rename   forageacresgrazedacres         FORAGE_GRAZED_HA                   
capture rename   forageacresgrazeddays          FORAGE_GRAZED_DAYS                 
