capture rename   PowerMachineryTOTALOriginalG   TOTAL_ORIGINAL_GROSS_COST_EU       
capture rename   D                              TOTAL_ORIGINAL_GRANT_EU            
capture rename   PowerMachinerybeginningofyea   TAKE_ON_YEAR                       
capture rename   PowerMachineryTOTALPurchaseT   TOTAL_PURCHASE_THIS_YEAR_EU        
capture rename   PowerMachineryTOTALMajorRepa   TOTAL_MAJOR_REPAIRS_EU             
capture rename   PowerMachineryGrantrecincur    APPLIED_GRANT                      
capture rename   PowerMachineryTOTALSalesTr     TOTAL_SALES_TRADEINS_EU            
capture rename   PowerMachineryTOTALValue       WRITE_OFF_YEAR                     
capture rename   PowerMachineryDepreciation     HIST_DEP_VALUE                     
capture rename   PowerMachineryENDofyearnet     HIST_NET_VALUE                     
