capture rename   BreedofEwe                     EWE_BREED_CODE                     
capture rename   BreedofRam                     RAM_BREED_CODE                     
capture rename   HillorLowland                  HILL_LOWLAND_CODE                  
capture rename   NoofSheepShorn                 SHEEP_SHORN_NO                     
capture rename   NoofEweslettoRam               EWES_LET_TO_RAM_NO                 
capture rename   NoofeweLambstakingtheRam       EWE_LAMBS_TAKING_RAM_NO            
capture rename   NoofBarrenEwes                 BARREN_EWES_NO                     
capture rename   NoofEwesMatedHormoneTreate     EWES_MATED_HORMONE_TREATED_NO      
capture rename   NoofFatLambssoldpreJune1       FAT_LAMBS_SOLD_PRE_JUNE1_NO        
capture rename   NoofInLambewesPurchases        EWES_IN_LAMB_PURCHASES_NO          
capture rename   NoofInLambewesSales            EWES_IN_LAMB_SALES_NO              
capture rename   NoofewesPurchasedwithlambs     EWES_AT_FOOT_LAMBS_PURCHASES_NO    
capture rename   NoofewesSoldwithlambsatfo      EWES_AT_FOOT_LAMBS_SALES_NO        
capture rename   NoofLambsPurchasedatfoot       LAMBS_AT_FOOT_PURCHASES_NO         
capture rename   NoofLambsSoldatfoot            LAMBS_AT_FOOT_SALES_NO             
capture rename   BirthsLive                     BIRTHS_LIVE_NO                     
capture rename   DeathsEwes                     DEATHS_EWES_NO                     
capture rename   DeathsLambsbeforeWeaning       DEATHS_LAMBS_PRE_WEANING_NO        
capture rename   DeathsOther                    DEATHS_OTHER_NO                    
