capture rename   CattleHerdPurchasesCalvesNum   CATTLE_CALVES_PURCHASES_NO         
capture rename   CattleHerdPurchasesCalvesVal   CATTLE_CALVES_PURCHASES_EU         
capture rename   CattleHerdPurchasesWeanlings   CATTLE_WEANLINGS_PURCHASES_NO      
capture rename   F                              CATTLE_WEANLINGS_PURCHASES_EU      
capture rename   CattleHerdPurchasesBreedHerd   var98                              
capture rename   J                              var99                              
capture rename   CattleHerdPurchasesOtherNumb   CATTLE_OTHER_PURCHASES_NO          
capture rename   CattleHerdPurchasesOtherValu   CATTLE_OTHER_PURCHASES_EU          
capture rename   CattleHerdPurchasesTotalNumb   CATTLE_TOTAL_PURCHASES_NO          
capture rename   CattleHerdPurchasesTotalValu   CATTLE_TOTAL_PURCHASES_EU          
capture rename   CattleHerdUsedinHouseNumber    CATTLE_USED_IN_HOUSE_NO            
capture rename   CattleHerdUsedinHouseValue     CATTLE_USED_IN_HOUSE_EU            
capture rename   CattleHerdReceiptsforBullSe    var107                             
capture rename   CattleHerdSubsidiesValue       CATTLE_SUBSIDIES_EU                
