capture rename   AmountFedDairy                 FED_DAIRY_TONNES_HA                
capture rename   AmountFedCattle                FED_CATTLE_TONNES_HA               
capture rename   AmountFedSheep                 FED_SHEEP_TONNES_HA                
capture rename   AmountFedPigs                  FED_PIGS_TONNES_HA                 
capture rename   AmountFedPoultry               FED_POULTRY_TONNES_HA              
capture rename   AmountFedHorses                FED_HORSES_TONNES_HA               
capture rename   AmountFedOtherFarmyardAnimal   FED_GOATS_TONNES_HA                
capture rename   AmountFedOtherGrazingAnimals   FED_DEER_TONNES_HA                 
capture rename   AmountFedTotal                 FED_TOTAL_TONNES_HA                
