capture rename   farm                           FARM_CODE                          
capture rename   card                           junk_01_3                          
capture rename   SoilCode                       SOIL_CODE                          
capture rename   Province                       PROVINCE                           
capture rename   CountyCode                     COUNTY_CODE                        
capture rename   DED                            DED                                
capture rename   ClosingDateday                 CLOSING_DAY                        
capture rename   ClosingDatemonth               CLOSING_MONTH                      
capture rename   ClosingDateyear                CLOSING_YEAR                       
capture rename   RecorderCode                   RECORDER_CODE                      
capture rename   booknumber                     BOOK_NUMBER                        
capture rename   forceoption                    FORCE_OPTION                       
capture rename   AltitudeCode                   ALTITUDE_CODE                      
capture rename   LessFavouredAreas              LESS_FAVOURED_AREAS                
