capture rename   N                              ANALYSIS_N                         
capture rename   P                              ANALYSIS_P                         
capture rename   K                              ANALYSIS_K                         
capture rename   TotalCost                      ORIGINAL_COST_EU                   
capture rename   TotalQuantity50Kgbags          ORIGINAL_QUANTITY_50KGBAGS         
capture rename   alloccropcode1                 alloccropcode1                     
capture rename   Quantity1                      Quantity1                          
capture rename   alloccropcode2                 alloccropcode2                     
capture rename   Quantity2                      Quantity2                          
capture rename   alloccropcode3                 alloccropcode3                     
capture rename   Quantity3                      Quantity3                          
capture rename   alloccropcode4                 alloccropcode4                     
capture rename   Quantity4                      Quantity4                          
capture rename   Totalqtyused                   TOTAL_USED_ON_CROPS_50KGBAGS       
capture rename   Quantityclosinginventory       CLOSING_INVENTORY_50KGBAGS         
