capture rename   PowerMachineryTOTALOriginalG   PMA_TOTAL_ORIGINAL_GROSS_COST_EU  
capture rename   D                              PMA_TOTAL_ORIGINAL_GRANT_EU       
capture rename   PowerMachinerybeginningofyea   PMA_BegYearNetVal                 
capture rename   PowerMachineryTOTALPurchaseT   PMA_TOTAL_PURCHASE_THIS_YEAR_EU   
capture rename   PowerMachineryTOTALMajorRepa   PMA_TOTAL_MAJOR_REPAIRS_EU        
capture rename   PowerMachineryGrantrecincur    PMA_GRANTS_EU                     
capture rename   PowerMachineryTOTALSalesTr     PMA_TOTAL_SALES_TRADEINS_EU       
capture rename   PowerMachineryTOTALValue       PMA_TOTALValue                    
capture rename   PowerMachineryDepreciation     PMA_REPLACE_DEP_VALUE             
capture rename   PowerMachineryENDofyearnet     PMA_REPLACE_NET_VALUE             
