capture rename   OTHERMachineryTOTALOriginalG   TOTAL_ORIGINAL_GROSS_COST_EU       
capture rename   D                              TOTAL_ORIGINAL_GRANT_EU            
capture rename   OTHERMachinerybeginningofyea   TAKE_ON_YEAR                       
capture rename   OTHERMachineryTOTALPurchaseT   TOTAL_PURCHASE_THIS_YEAR_EU        
capture rename   OTHERMachineryTOTALMajorRepa   TOTAL_MAJOR_REPAIRS_EU             
capture rename   OTHERMachineryGrantrecincur    APPLIED_GRANT                      
capture rename   OTHERMachineryTOTALSalesTr     TOTAL_SALES_TRADEINS_EU            
capture rename   OTHERMachineryTOTALValue       WRITE_OFF_YEAR                     
capture rename   OTHERMachineryDepreciation     HIST_DEP_VALUE                     
capture rename   OTHERMachineryENDofyearnet     HIST_NET_VALUE                     
