capture rename   OpeningInventorySowsinPigNu    SOWS_IN_PIG_OP_INV_NO              
capture rename   OpeningInventorySowsinPigVa    SOWS_IN_PIG_OP_INV_PERHEAD_EU      
capture rename   OpeningInventoryGiltsinPigN    GILTS_IN_PIG_OP_INV_NO             
capture rename   OpeningInventoryGiltsinPigV    GILTS_IN_PIG_OP_INV_PERHEAD_EU     
capture rename   OpeningInventorySowsSuckling   SOWS_SUCKLING_OP_INV_NO            
capture rename   H                              SOWS_SUCKLING_OP_INV_EU            
capture rename   OpeningInventoryBonhamsNumber  BONHAMS_OP_INV_NO                  
capture rename   OpeningInventoryBonhamsValue   BONHAMS_OP_INV_PERHEAD_EU          
capture rename   OpeningInventoryWeanersNumber  WEANERS_OP_INV_NO                  
capture rename   OpeningInventoryWeanersValue   WEANERS_OP_INV_PERHEAD_EU          
capture rename   OpeningInventoryFattenersNumb  FATTENERS1_OP_INV_NO               
capture rename   OpeningInventoryFattenersWeig  FATTENERS1_OP_INV_PERHEAD_KGS      
capture rename   OpeningInventoryFattenersValu  FATTENERS1_OP_INV_PERHEAD_EU       
capture rename   P                              FATTENERS2_OP_INV_NO               
capture rename   Q                              FATTENERS2_OP_INV_PERHEAD_KGS      
capture rename   R                              FATTENERS2_OP_INV_PERHEAD_EU       
capture rename   S                              FATTENERS3_OP_INV_NO               
capture rename   T                              FATTENERS3_OP_INV_PERHEAD_KGS      
capture rename   U                              FATTENERS3_OP_INV_PERHEAD_EU       
capture rename   OpeningInventoryFatteningSows  FATTENING_SOWS_OP_INV_NO           
capture rename   W                              FATTENING_SOWS_OP_INV_EU           
capture rename   OpeningInventoryStockBoarsNu   STOCK_BOARS_OP_INV_NO              
capture rename   OpeningInventoryStockBoars     STOCK_BOARS_OP_INV_PERHEAD_EU      
capture rename   OpeningInventoryTotalNumber    TOTAL_OP_INV_NO                    
