rename	ai	AI
rename	sys	SYS
rename	t	T
rename	w	W
rename	fc	FC
rename	sclass	SCLASS
rename	fsize	FSIZE
rename	fvalue	FVALUE
rename	sex	SEX
rename	age	AGE
rename	jobtype	JOBTYPE
rename	child5	CHILD5
rename	child15	CHILD15
rename	child19	CHILD19
rename	loan	LOAN
rename	y1	Y1
rename	qtown	QTOWN
rename	qtlease	QTLEASE
rename	qtlet	QTLET
rename	qt	QT
rename	fat	FAT
rename	protein	PROTEIN
rename	landfage	LANDFAGE
rename	landfeed	LANDFEED
rename	alloc	ALLOC
rename	c	C
rename	l1	L1
rename	l2	L2
rename	l3	L3
rename	h	H
rename	y2	Y2
rename	dc	DC
rename	t1	T1
rename	t2	T2
rename	t3	T3
rename	t4	T4
rename	t5	T5
rename	t6	T6
rename	t7	T7
rename	t8	T8
rename	t9	T9
rename	t10	T10
rename	t11	T11
rename	age1	AGE1
rename	age2	AGE2
rename	age3	AGE3
rename	age4	AGE4
rename	age5	AGE5
rename	age6	AGE6
rename	age7	AGE7
rename	soil1	SOIL1
rename	soil2	SOIL2
rename	soil3	SOIL3
rename	aid	AID
rename	bull	BULL
rename	debtrat	DEBTRAT
rename	subs1	SUBS1
rename	subrat1	SUBRAT1
rename	subs2	SUBS2
rename	subrat2	SUBRAT2
rename	landrat	LANDRAT
rename	acreval	ACREVAL
rename	child	CHILD
rename	married	MARRIED
rename	offfarm	OFFFARM
rename	cowval	COWVAL
rename	exten	EXTEN
rename	extend	EXTEND
rename	size1	SIZE1
rename	size2	SIZE2
rename	size3	SIZE3
rename	size4	SIZE4
rename	size5	SIZE5
rename	intense	INTENSE
rename	decoup	DECOUP
rename	maxt	MAXT
rename	mint	MINT
rename	tlag	TLAG
rename	one	ONE
rename	ps	PS
rename	ph	PH
rename	pd	PD
rename	pl	PL
rename	pa	PA
rename	pc	PC
rename	utre	UTRE
rename	etre	ETRE
