*******************************************
* Create cattle_dairy_boarding_in_out_com
*******************************************

* d_cattle_lu_boarding_out, d_cattle_lu_boarding_in, d_dairy_lu_boarding_out, d_dairy_lu_boarding_in (USES THE svy_grazing TABLE)
sort  FARM_CODE YE_AR
keep FARM_CODE YE_AR BOARDING_OUT_CATTLE1_ANIMALS_NO BOARDING_OUT_CATTLE1_DAYS_NO BOARDING_OUT_CATTLE1_LU_EQUIV BOARDING_OUT_CATTLE2_ANIMALS_NO BOARDING_OUT_CATTLE2_DAYS_NO BOARDING_OUT_CATTLE2_LU_EQUIV BOARDING_IN_CATTLE1_ANIMALS_NO BOARDING_IN_CATTLE1_DAYS_NO BOARDING_IN_CATTLE1_LU_EQUIV BOARDING_IN_CATTLE2_ANIMALS_NO BOARDING_IN_CATTLE2_DAYS_NO BOARDING_IN_CATTLE2_LU_EQUIV COMMONAGE_CATTLE1_ANIMALS_NO COMMONAGE_CATTLE1_DAYS_NO COMMONAGE_CATTLE1_LU_EQUIV COMMONAGE_CATTLE2_ANIMALS_NO COMMONAGE_CATTLE2_DAYS_NO COMMONAGE_CATTLE2_LU_EQUIV BOARDING_OUT_DAIRY_ANIMALS_NO BOARDING_OUT_DAIRY_DAYS_NO BOARDING_IN_DAIRY_ANIMALS_NO BOARDING_IN_DAIRY_DAYS_NO COMMONAGE_DAIRY_ANIMALS_NO COMMONAGE_DAIRY_DAYS_NO COMMONAGE_DAIRY_LU_EQUIV

