*******************************************
* Create d_dairy_prod_misc_dc_eu
*******************************************

replace TRANSPORT_ALLOC_DAIRY_HERD_EU = TRANSPORT_ALLOC_DAIRY_HERD_test2
replace VET_MED_ALLOC_DAIRY_HERD_EU = VET_MED_ALLOC_DAIRY_HERD_test2
replace AI_SR_FEES_ALOC_DAIRY_HRD_EU = AI_SR_FEES_ALOC_DAIRY_HRD_test2
replace MISC_ALLOC_DAIRY_HERD_EU = MISC_ALLOC_DAIRY_HERD_test2
* replace CAS_LAB_ALLOC_DAIRY_HERD_EU = CAS_LAB_ALLOC_DAIRY_HERD_EU * sc_p_caslab_dairy

sort FARM_CODE YE_AR


*replace TOTAL_DEDUCTIONS_EU = TOTAL_DEDUCTIONS_EU * sc_p_misclv_totded

*CHANGE-7983: Create 0 variables
capture gen double TOTAL_DEDUCTIONS_EU           = 0
capture gen double SUPER_LEVY_CHARGE_EU          = 0
capture gen double SUPER_LEVY_REFUND_EU          = 0
capture gen double MILK_QUOTA_TOT_LEASED_EU      = 0
capture gen double SUPER_LEVY_CHARGE_EU          = 0
capture gen double SUPER_LEVY_REFUND_EU          = 0
capture gen double D_DAIRY_TOTAL_DIRECT_COSTS_EU = 0


gen d_dairy_prod_misc_dcost_eu = (VET_MED_ALLOC_DAIRY_HERD_EU + AI_SR_FEES_ALOC_DAIRY_HRD_EU + TRANSPORT_ALLOC_DAIRY_HERD_EU + MISC_ALLOC_DAIRY_HERD_EU + CAS_LAB_ALLOC_DAIRY_HERD_EU +  TOTAL_DEDUCTIONS_EU) + (SUPER_LEVY_CHARGE_EU - SUPER_LEVY_REFUND_EU) + MILK_QUOTA_TOT_LEASED_EU if (SUPER_LEVY_CHARGE_EU - SUPER_LEVY_REFUND_EU) >= 0
replace d_dairy_prod_misc_dcost_eu = (VET_MED_ALLOC_DAIRY_HERD_EU + AI_SR_FEES_ALOC_DAIRY_HRD_EU + TRANSPORT_ALLOC_DAIRY_HERD_EU + MISC_ALLOC_DAIRY_HERD_EU + CAS_LAB_ALLOC_DAIRY_HERD_EU + TOTAL_DEDUCTIONS_EU) + (SUPER_LEVY_CHARGE_EU) + MILK_QUOTA_TOT_LEASED_EU if d_dairy_prod_misc_dcost_eu  == .

keep FARM_CODE YE_AR VET_MED_ALLOC_DAIRY_HERD_EU AI_SR_FEES_ALOC_DAIRY_HRD_EU TRANSPORT_ALLOC_DAIRY_HERD_EU MISC_ALLOC_DAIRY_HERD_EU CAS_LAB_ALLOC_DAIRY_HERD_EU TOTAL_DEDUCTIONS_EU SUPER_LEVY_CHARGE_EU SUPER_LEVY_REFUND_EU MILK_QUOTA_TOT_LEASED_EU d_dairy_prod_misc_dcost_eu D_DAIRY_PROD_MISC_DCOST_EU D_DAIRY_TOTAL_DIRECT_COSTS_EU

sort FARM_CODE YE_AR

