*******************************************
* Create svy_cattle_2
*******************************************

gen d_cattle_lu_boarding_out = (BOARDING_OUT_CATTLE1_ANIMALS_NO * (BOARDING_OUT_CATTLE1_DAYS_NO / 365) * BOARDING_OUT_CATTLE1_LU_EQUIV) + (BOARDING_OUT_CATTLE2_ANIMALS_NO * (BOARDING_OUT_CATTLE2_DAYS_NO / 365) * BOARDING_OUT_CATTLE2_LU_EQUIV)
replace d_cattle_lu_boarding_out = 0 if d_cattle_lu_boarding_out == .

gen d_cattle_lu_boarding_in = (BOARDING_IN_CATTLE1_ANIMALS_NO * (BOARDING_IN_CATTLE1_DAYS_NO / 365) * BOARDING_IN_CATTLE1_LU_EQUIV) + (BOARDING_IN_CATTLE2_ANIMALS_NO * (BOARDING_IN_CATTLE2_DAYS_NO / 365) * BOARDING_IN_CATTLE2_LU_EQUIV)
replace d_cattle_lu_boarding_in = 0 if d_cattle_lu_boarding_in == .

gen i_cattle_lu_home_grazing = (d_cattle_livestock_units - (COMMONAGE_CATTLE1_ANIMALS_NO * (COMMONAGE_CATTLE1_DAYS_NO / 365) * COMMONAGE_CATTLE1_LU_EQUIV + COMMONAGE_CATTLE2_ANIMALS_NO * (COMMONAGE_CATTLE2_DAYS_NO / 365) * COMMONAGE_CATTLE2_LU_EQUIV)) - (d_cattle_lu_boarding_out - d_cattle_lu_boarding_in)


gen d_dairy_lu_boarding_out = BOARDING_OUT_DAIRY_ANIMALS_NO * (BOARDING_OUT_DAIRY_DAYS_NO / 365) * 1
replace d_dairy_lu_boarding_out = 0 if d_dairy_lu_boarding_out == .

gen d_dairy_lu_boarding_in = BOARDING_IN_DAIRY_ANIMALS_NO * (BOARDING_IN_DAIRY_DAYS_NO / 365) * 1
replace d_dairy_lu_boarding_in = 0 if d_dairy_lu_boarding_in == .

gen i_dairy_lu_home_grazing = d_dairy_livstk_units_inc_bulls - (COMMONAGE_DAIRY_ANIMALS_NO * (COMMONAGE_DAIRY_DAYS_NO / 365) * COMMONAGE_DAIRY_LU_EQUIV) - d_dairy_lu_boarding_out - d_dairy_lu_boarding_in

*D_DAIRY_HERD_VALUE_CHANGE_EU
gen d_dairy_herd_value_change_eu = 0
replace d_dairy_herd_value_change_eu = ((DAIRY_COWS1_CLOS_INV_NO - DAIRY_COWS1_OP_INV_NO) * DAIRY_COWS1_CLOS_INV_EU) + ((DAIRY_COWS2_CLOS_INV_NO- DAIRY_COWS2_OP_INV_NO) * DAIRY_COWS2_CLOS_INV_EU) + ((DAIRY_STOCK_BULLS_CLOS_INV_NO - DAIRY_STOCK_BULLS_OP_INV_NO) * DAIRY_STOCK_BULLS_CLOS_INV_EU) + ((DAIRY_CALVES_LT1WEEK_CLOS_INV_NO - DAIRY_CALVES_LT1WEEK_OP_INV_NO) * DAIRY_CALVES_LT1WEEK_CLOS_INV_EU) + ((DAIRY_OTHER_CLOS_INV_NO - DAIRY_OTHER_OP_INV_NO) * DAIRY_OTHER_CLOS_INV_EU)

*D_DAIRY_VALUE_DROPPED_CALVES_SOLD_TRANS_EU (RENAMED TO: D_DY_VAL_DROPD_CLVS_SLD_TRANS_EU)
gen d_dy_val_dropd_clvs_sld_trans_eu = 0
replace d_dy_val_dropd_clvs_sld_trans_eu = DAIRY_CALVES_SALES_EU + DAIRY_CALVES_TRANSFER_EU

*D_DAIRY_HERD_REPLACE_COST_EU
gen d_dairy_herd_replace_cost_eu = 0
replace d_dairy_herd_replace_cost_eu = (((DAIRY_COWS_SH_BULLS_SLS_BREED_EU + DAIRY_COWS_SH_BULLS_SALES_CUL_EU + DY_COWS_SH_BULS_TRNSFR_OUT_EU) - DY_COWS_SH_BULLS_PURCHASES_EU) - DY_COWS_SH_BULS_TRNSFR_IN_EU) + d_dairy_herd_value_change_eu


*D_SALES_INCL_HSE_CONSUMPTION_EU
gen d_sales_incl_hse_consumption_eu = 0
replace d_sales_incl_hse_consumption_eu = CATTLE_TOTAL_SALES_EU + CATTLE_USED_IN_HOUSE_EU + CATTLE_RECPTS_FOR_BULL_SRVICE_EU

*D_TRANSFER_FROM_DAIRY_HERD_EU
gen d_transfer_from_dairy_herd_eu = 0
replace d_transfer_from_dairy_herd_eu = DAIRY_CALVES_TRANSFER_EU + DY_COWS_SH_BULS_TRNSFR_OUT_EU

*D_VALUE_OF_CHANGE_OF_NUMBERS_EUR
gen d_value_of_change_of_numbers_eur = 0
replace d_value_of_change_of_numbers_eur = ((CATTLE_SUCKLER_COWS_CLOS_INV_NO - CATTLE_SUCKLER_COWS_OP_INV_NO) * CATTLE_SUCKLER_COWS_CLOS_INV_EU) + ((CATTLE_OTHER_COWS_CLOS_INV_NO - CATTLE_OTHER_COWS_OP_INV_NO) * CATTLE_OTHER_COWS_CLOS_INV_EU) + ((CATTLE_IN_CALF_HEFRS_CLOS_INV_NO - CATTLE_IN_CALF_HEIFERS_OP_INV_NO) * CATTLE_IN_CALF_HEFRS_CLOS_INV_EU) + ((CATTLE_STOCK_BULLS_CLOS_INV_NO - CATTLE_STOCK_BULLS_OP_INV_NO) * CATTLE_STOCK_BULLS_CLOS_INV_EU) + ((CATTLE_CALVS_LT6MTHS_CLOS_INV_NO - CATTLE_CALVES_LT6MTHS_OP_INV_NO) * CATTLE_CALVS_LT6MTHS_CLOS_INV_EU) + ((CATL_CALVS_6MTHS_1YR_CLOS_INV_NO - CATTLE_CALVS_6MTHS_1YR_OP_INV_NO) * CATL_CALVS_6MTHS_1YR_CLOS_INV_EU) + ((CATTLE_MALE_1_2YRS_CLOS_INV_NO - CATTLE_MALE_1_2YRS_OP_INV_NO) * CATTLE_MALE_1_2YRS_CLOS_INV_EU) + ((CATTLE_FEMALE_1_2YRS_CLOS_INV_NO - CATTLE_FEMALE_1_2YRS_OP_INV_NO) * CATTLE_FEMALE_1_2YRS_CLOS_INV_EU) + ((CATTLE_MALE_2_3YRS_CLOS_INV_NO - CATTLE_MALE_2_3YRS_OP_INV_NO) * CATTLE_MALE_2_3YRS_CLOS_INV_EU) + ((CATTLE_FEMALE_2_3YRS_CLOS_INV_NO - CATTLE_FEMALE_2_3YRS_OP_INV_NO) * CATTLE_FEMALE_2_3YRS_CLOS_INV_EU) + ((CATTLE_OTHER_CLOS_INV_NO - CATTLE_OTHER_OP_INV_NO) * CATTLE_OTHER_CLOS_INV_EU)


