*******************************************
* Create deer_goats_misc_dc_eu
*******************************************


*replace CONC_ALLOC_DEER_50KGBAGS_EU = CONC_ALLOC_DEER_50KGBAGS_test2
*replace CONC_ALLOC_GOATS_50KGBAGS_EU = CONC_ALLOC_GOATS_50KGBAGS_test2
*replace VET_MED_ETC_ALLOC_DEER_EU = VET_MED_ETC_ALLOC_DEER_test2
*replace VET_MED_ETC_ALLOC_GOATS_EU = VET_MED_ETC_ALLOC_GOATS_test2
*replace VET_MED_ETC_ALLOC_OTHER_EU = VET_MED_ETC_ALLOC_OTHER_test2
*replace MISC_INCL_TRANS_ALLOC_GOATS_EU = MISC_INCL_TRANS_ALLOC_GOATS_EU * sc_p_misclv_goats
*replace MISC_INCL_TRANS_ALLOC_OTHER_EU = MISC_INCL_TRANS_ALLOC_OTHER_EU * sc_p_misclv_other
*replace CASUAL_LABOUR_ALLOC_DEER_EU = CASUAL_LABOUR_ALLOC_DEER_EU * sc_p_caslab_deer
*replace CASUAL_LABOUR_ALLOC_GOATS_EU = CASUAL_LABOUR_ALLOC_GOATS_EU * sc_p_caslab_goats
*replace CASUAL_LABOUR_ALLOC_OTHER_EU = CASUAL_LABOUR_ALLOC_OTHER_EU * sc_p_caslab_other

*keep FARM_CODE YE_AR CONC_ALLOC_DEER_50KGBAGS_EU CONC_ALLOC_GOATS_50KGBAGS_EU CONC_ALLOC_OTHER_50KGBAGS_EU VET_MED_ETC_ALLOC_DEER_EU VET_MED_ETC_ALLOC_GOATS_EU VET_MED_ETC_ALLOC_OTHER_EU  MISC_INCL_TRANS_ALLOC_DEER_EU MISC_INCL_TRANS_ALLOC_GOATS_EU MISC_INCL_TRANS_ALLOC_OTHER_EU CASUAL_LABOUR_ALLOC_DEER_EU CASUAL_LABOUR_ALLOC_GOATS_EU CASUAL_LABOUR_ALLOC_OTHER_EU

keep FARM_CODE YE_AR *DEER* *GOAT* *OTHER*
sort FARM_CODE YE_AR

