*******************************************
* Create horses_boarding_in_out_com
*******************************************

sort  FARM_CODE YE_AR
keep FARM_CODE YE_AR BOARDING_OUT_HORSES_ANIMALS_NO  BOARDING_OUT_HORSES_DAYS_NO BOARDING_OUT_HORSES_LU_EQUIV BOARDING_IN_HORSES_ANIMALS_NO BOARDING_IN_HORSES_DAYS_NO BOARDING_IN_HORSES_LU_EQUIV COMMONAGE_HORSES_ANIMALS_NO COMMONAGE_HORSES_DAYS_NO COMMONAGE_HORSES_LU_EQUIV
