*******************************************
* Create horses_misc_dc_eu
*******************************************


replace CONC_ALLOC_HORSES_50KGBAGS_EU = CONC_ALLOC_HORSES_50KGBAGS_test2
replace TRANSPORT_ALLOC_HORSES_EU = TRANSPORT_ALLOC_HORSES_test2
replace VET_MED_ALLOC_HORSES_EU = VET_MED_ALLOC_HORSES_test2 
replace AI_SER_FEES_ALLOC_HORSES_EU = AI_SER_FEES_ALLOC_HORSES_test2
*replace MISCELLANEOUS_ALLOC_HORSES_EU = MISCELLANEOUS_ALLOC_HORSES_EU * sc_p_misclv_horses

keep FARM_CODE YE_AR CONC_ALLOC_HORSES_50KGBAGS_EU VET_MED_ALLOC_HORSES_EU AI_SER_FEES_ALLOC_HORSES_EU TRANSPORT_ALLOC_HORSES_EU MISCELLANEOUS_ALLOC_HORSES_EU 

sort FARM_CODE YE_AR
