*******************************************
* Create svy_pigs_1
*******************************************

*D_PIG_SALES_EU
gen d_pig_sales_eu = 0
replace d_pig_sales_eu = BREEDING_STOCK_SALES_EU + BONHAMS_STORES_SALES_EU + PORKERS_BACON_SALES_EU + CULL_SOWS_BOARS_SALES_EU

*D_PIG_PURCHASES
gen d_pig_purchases_eu = 0
replace d_pig_purchases_eu = BREEDING_STOCK_PURCHASES_EU + BONHAMS_STORES_PURCHASES_EU

*D_VALUE_OF_CHANGE_IN_NUMBERS_EU  ***** THIS FORMULA IS WRONG(IT IS FOR SHEEP) - BRIAN TO WRITE NEW FORMULA FOR PIGS - FOR NOW JUST USE THE VARIABLE WITHOUT DERIVATION EVEN THOUGH IT IS WRONG
*ALSO RENAME THE ABOVE "D_VALUE_OF_CHANGE_IN_NUMBERS_EU" TO "D_VALUE_OF_CHANGE_IN_NUM_PIGS_EU" AS IT IS THE SAME VARS USED FOR SHEEP.

rename D_VALUE_OF_CHANGE_IN_NUMBERS_EU D_VALUE_OF_CHANGE_IN_NUM_PIGS_EU
