*******************************************
* Create sheep_boarding_in_out_com
*******************************************

sort  FARM_CODE YE_AR
keep FARM_CODE YE_AR BOARDING_OUT_SHEEP1_ANIMALS_NO BOARDING_OUT_SHEEP1_DAYS_NO BOARDING_OUT_SHEEP1_LU_EQUIV BOARDING_OUT_SHEEP2_ANIMALS_NO BOARDING_OUT_SHEEP2_DAYS_NO BOARDING_OUT_SHEEP2_LU_EQUIV BOARDING_IN_SHEEP1_ANIMALS_NO BOARDING_IN_SHEEP1_DAYS_NO BOARDING_IN_SHEEP1_LU_EQUIV BOARDING_IN_SHEEP2_ANIMALS_NO BOARDING_IN_SHEEP2_DAYS_NO BOARDING_IN_SHEEP2_LU_EQUIV COMMONAGE_SHEEP1_ANIMALS_NO COMMONAGE_SHEEP1_DAYS_NO COMMONAGE_SHEEP1_LU_EQUIV COMMONAGE_SHEEP2_ANIMALS_NO COMMONAGE_SHEEP2_DAYS_NO COMMONAGE_SHEEP2_LU_EQUIV
