*******************************************
* Create svy_livestock_expenses_1
*******************************************

rename var11 CONC_ALLC_DARY_HRD_50KGBGS_NO
rename var12 CONC_ALLC_DARY_HRD_50KGBGS_EU
rename var33 CONC_MLK_SUB_FED_CLVS_50KGBGS_NO
rename var34 CONC_MLK_SUB_FED_CLVS_50KGBGS_EU
rename var39 AI_SR_FEES_ALOC_DAIRY_HRD_EU
rename var52 VET_MED_AI_SER_FEES_TOTALOC_EU
rename var57 MISC_ALLOC_DAIRY_HERD_EU
rename var68 MISC_INCL_TRANS_ALLOC_DEER_EU
rename var69 MISC_INCL_TRANS_ALLOC_GOATS_EU
rename var70 MISC_INCL_TRANS_ALLOC_OTHER_EU
rename var72 CAS_LAB_ALLOC_DAIRY_HERD_EU
rename var83 D_WSTE_DCOSTS_CANNOT_ALLOC
rename MISCELLANEOUS_ALLOC_POULTRY_EU MISC_ALLOC_POULTRY_EU
rename CONC_ALLOC_POULTRY_50KGBAGS_NO CONC_ALLOC_PLTRY_50KGBAGS_NO
rename CONC_ALLOC_POULTRY_50KGBAGS_EU CONC_ALLOC_PLTRY_50KGBAGS_EU
rename AI_SERVICE_FEES_ALLOC_CATTLE_EU AI_SER_FEES_ALLOC_CATTLE_EU
rename AI_SERVICE_FEES_ALLOC_SHEEP_EU AI_SER_FEES_ALLOC_SHEEP_EU
rename AI_SERVICE_FEES_ALLOC_HORSES_EU AI_SER_FEES_ALLOC_HORSES_EU
rename AI_SERVICE_FEES_ALLOC_PIGS_EU AI_SER_FEES_ALLOC_PIGS_EU
