args FC cond


local vlist ""
local vlist "`vlist' TOTAL_SGMS"
local vlist "`vlist' SGM_Farm"
local vlist "`vlist' SGM_CommonWheat"
local vlist "`vlist' d01_ecu_per_ha"
local vlist "`vlist' CY_HECTARES_HA1111 "
local vlist "`vlist' CY_HECTARES_HA1116 "
local vlist "`vlist' CY_HECTARES_HA1117"
local vlist "`vlist' SGM_Barley"
local vlist "`vlist' d04_ecu_per_ha"
local vlist "`vlist' CY_HECTARES_HA1141"
local vlist "`vlist' CY_HECTARES_HA1146 "
local vlist "`vlist' CY_HECTARES_HA1571 "
local vlist "`vlist' CY_HECTARES_HA1147 "
local vlist "`vlist' CY_HECTARES_HA1577"
local vlist "`vlist' SGM_Oats"
local vlist "`vlist' d05_ecu_per_ha"
local vlist "`vlist' CY_HECTARES_HA1151 "
local vlist "`vlist' CY_HECTARES_HA1156 "
local vlist "`vlist' CY_HECTARES_HA1157"
local vlist "`vlist' SGM_Peas"
local vlist "`vlist' d09e_1_ecu_per_ha"
local vlist "`vlist' CY_HECTARES_HA1211 "
local vlist "`vlist' CY_HECTARES_HA1271 "
local vlist "`vlist' CY_HECTARES_HA1291"
local vlist "`vlist' SGM_Potatoes"
local vlist "`vlist' d10_ecu_per_ha"
local vlist "`vlist' CY_HECTARES_HA1311 "
local vlist "`vlist' CY_HECTARES_HA1317"
local vlist "`vlist' SGM_SugarBeet"
local vlist "`vlist' d11_ecu_per_ha"
local vlist "`vlist' CY_HECTARES_HA1321 "
local vlist "`vlist' CY_HECTARES_HA1327"
local vlist "`vlist' SGM_FodderRoots"
local vlist "`vlist' d12_ecu_per_ha"
local vlist "`vlist' CY_HECTARES_HA9041 "
local vlist "`vlist' CY_HECTARES_HA9051 "
local vlist "`vlist' CY_HECTARES_HA9061 "
local vlist "`vlist' CY_HECTARES_HA9071 "
local vlist "`vlist' CY_HECTARES_HA9081"
local vlist "`vlist' SGM_Oilseed"
local vlist "`vlist' d13d1d_ecu_per_ha"
local vlist "`vlist' CY_HECTARES_HA1431 "
local vlist "`vlist' CY_HECTARES_HA1436"
local vlist "`vlist' SGM_VegOpenField"
local vlist "`vlist' d14a_ecu_per_ha"
local vlist "`vlist' CY_HECTARES_HA2211 "
local vlist "`vlist' CY_HECTARES_HA2221 "
local vlist "`vlist' CY_HECTARES_HA2231 "
local vlist "`vlist' CY_HECTARES_HA2251 "
local vlist "`vlist' CY_HECTARES_HA2261 "
local vlist "`vlist' CY_HECTARES_HA2271 "
local vlist "`vlist' CY_HECTARES_HA2281 "
local vlist "`vlist' CY_HECTARES_HA2291 "
local vlist "`vlist' CY_HECTARES_HA2311 "
local vlist "`vlist' CY_HECTARES_HA2321 "
local vlist "`vlist' CY_HECTARES_HA2341 "
local vlist "`vlist' CY_HECTARES_HA2371 "
local vlist "`vlist' CY_HECTARES_HA2381 "
local vlist "`vlist' CY_HECTARES_HA2431 "
local vlist "`vlist' CY_HECTARES_HA2441 "
local vlist "`vlist' CY_HECTARES_HA2451 "
local vlist "`vlist' CY_HECTARES_HA2461 "
local vlist "`vlist' CY_HECTARES_HA2491 "
local vlist "`vlist' CY_HECTARES_HA2511 "
local vlist "`vlist' CY_HECTARES_HA2531 "
local vlist "`vlist' CY_HECTARES_HA2601 "
local vlist "`vlist' CY_HECTARES_HA2611 "
local vlist "`vlist' CY_HECTARES_HA2631 "
local vlist "`vlist' CY_HECTARES_HA2651 "
local vlist "`vlist' CY_HECTARES_HA2991"
local vlist "`vlist' SGM_VegUnderGlass"
local vlist "`vlist' d15_ecu_per_ha"
local vlist "`vlist' CY_HECTARES_HA2215 "
local vlist "`vlist' CY_HECTARES_HA2225 "
local vlist "`vlist' CY_HECTARES_HA2235 "
local vlist "`vlist' CY_HECTARES_HA2255 "
local vlist "`vlist' CY_HECTARES_HA2265 "
local vlist "`vlist' CY_HECTARES_HA2275 "
local vlist "`vlist' CY_HECTARES_HA2285 "
local vlist "`vlist' CY_HECTARES_HA2295 "
local vlist "`vlist' CY_HECTARES_HA2315 "
local vlist "`vlist' CY_HECTARES_HA2325 "
local vlist "`vlist' CY_HECTARES_HA2345 "
local vlist "`vlist' CY_HECTARES_HA2375 "
local vlist "`vlist' CY_HECTARES_HA2385 "
local vlist "`vlist' CY_HECTARES_HA2435 "
local vlist "`vlist' CY_HECTARES_HA2445 "
local vlist "`vlist' CY_HECTARES_HA2455 "
local vlist "`vlist' CY_HECTARES_HA2465 "
local vlist "`vlist' CY_HECTARES_HA2495 "
local vlist "`vlist' CY_HECTARES_HA2515 "
local vlist "`vlist' CY_HECTARES_HA2535 "
local vlist "`vlist' CY_HECTARES_HA2605 "
local vlist "`vlist' CY_HECTARES_HA2615 "
local vlist "`vlist' CY_HECTARES_HA2635 "
local vlist "`vlist' CY_HECTARES_HA2655 "
local vlist "`vlist' CY_HECTARES_HA2995"
local vlist "`vlist' SGM_GreenMaize"
local vlist "`vlist' d18b1_ecu_per_ha"
local vlist "`vlist' CY_HECTARES_HA9021"
local vlist "`vlist' SGM_OtherGreenFodder"
local vlist "`vlist' d18b3_ecu_per_ha"
local vlist "`vlist' CY_HECTARES_HA9031"
local vlist "`vlist' SGM_Pasture"
local vlist "`vlist' f01_ecu_per_ha"
local vlist "`vlist' SGM_RoughGrazing"
local vlist "`vlist' f02_ecu_per_ha"
local vlist "`vlist' SGM_Nurseries"
local vlist "`vlist' g05_ecu_per_ha"
local vlist "`vlist' CY_HECTARES_HA6011"
local vlist "`vlist' SGM_Mushrooms"
local vlist "`vlist' i02_ecu_per_100_m2"
local vlist "`vlist' CY_HECTARES_HA1391"
local vlist "`vlist' SGM_SetAside"
local vlist "`vlist' i06a_ecu_per_ha"
local vlist "`vlist' SGM_Equidae"
local vlist "`vlist' j01_ecu_per_head"
local vlist "`vlist' D_HORSES_FOR_SGMS_AVGNO"
local vlist "`vlist' SGM_BovineLT1"
local vlist "`vlist' j02_ecu_per_head"
local vlist "`vlist' D_LT1YR_FOR_SO_AVGNO"
local vlist "`vlist' D_HERD_SIZE_AVG_NO"
local vlist "`vlist' D_COWS_AVG_NO"
local vlist "`vlist' SGM_Bovine1_2M"
local vlist "`vlist' j03_ecu_per_head"
local vlist "`vlist' D_MALE_CATTLE_1_2YRS_AVG_NO"
local vlist "`vlist' SGM_Bovine1_2F"
local vlist "`vlist' j04_ecu_per_head"
local vlist "`vlist' D_FEMALE_CATTLE_1_2YRS_AVG_NO"
local vlist "`vlist' SGM_BovineGT2M"
local vlist "`vlist' j05_ecu_per_head"
local vlist "`vlist' D_MALEGT2YRS_FOR_SGMS_AVGNO"
local vlist "`vlist' SGM_BovineGT2F"
local vlist "`vlist' j06_ecu_per_head"
local vlist "`vlist' D_FEMALEGT2YRS_FOR_SGMS_AVGNO"
local vlist "`vlist' SGM_DairyCows"
local vlist "`vlist' j07_ecu_per_head"
local vlist "`vlist' D_HERD_SIZE_AVG_NO"
local vlist "`vlist' SGM_OtherCows"
local vlist "`vlist' j08_ecu_per_head"
local vlist "`vlist' D_COWS_AVG_NO"
local vlist "`vlist' SGM_Sheep"
local vlist "`vlist' j09_ecu_per_head"
local vlist "`vlist' D_TOTAL_SHEEP_AVG_NO"
local vlist "`vlist' D_EWES_AVG_NO "
local vlist "`vlist' SGM_SheepBreedingF"
local vlist "`vlist' j09a_ecu_per_head"
local vlist "`vlist' D_EWES_AVG_NO "
local vlist "`vlist' SGM_SheepOthers"
local vlist "`vlist' j09b_ecu_per_head"
local vlist "`vlist' D_SHEEP_FOR_SGMS_AVGNO"
local vlist "`vlist' D_EWES_AVG_NO"
local vlist "`vlist' SGM_PigsLT20kg"
local vlist "`vlist' j11_ecu_per_head"
local vlist "`vlist' D_WEANERS_AVG_NO"
local vlist "`vlist' D_FEMALE_PIGS_FOR_SGMS_AVGNO "
local vlist "`vlist' SGM_PigsGT50kg"
local vlist "`vlist' j12_ecu_per_head"
local vlist "`vlist' D_FEMALE_PIGS_FOR_SGMS_AVGNO "
local vlist "`vlist' SGM_PigsOther"
local vlist "`vlist' j13_ecu_per_head"
local vlist "`vlist' D_BOARS_PIGSGT20KG_SGMS_AVGNO"
local vlist "`vlist' D_FEMALE_PIGS_FOR_SGMS_AVGNO "
local vlist "`vlist' SGM_PoultryBroil"
local vlist "`vlist' j14_ecu_per_100_hds"
local vlist "`vlist' D_POULTRY1_FOR_SGMS_AVGNO"
local vlist "`vlist' SGM_PoultryHens"
local vlist "`vlist' j15_ecu_per_100_hds"
local vlist "`vlist' D_POULTRY2_FOR_SGMS_AVGNO"
local vlist "`vlist' SGM_PoultryOther"
local vlist "`vlist' j16_ecu_per_100_hds"
local vlist "`vlist' D_POULTRY3_FOR_SGMS_AVGNO"

br FARM_CODE YE_AR SGMregion `vlist' if FARM_CODE == `FC' & `cond'
