* from standard results				
 capture rename	 	a1	 	region
 capture rename	 	a18	 	organisationalform
 capture rename	 	a2	 	subregion
 capture rename	 	a24	 	country
 capture rename	 	a26	 	sizeclass
 capture rename	 	a28	 	generalfarmtype
 capture rename	 	a29	 	principalfarmtype
 capture rename	 	a3	 	farmcode
 capture rename	 	a30	 	system
 capture rename	 	a32	 	organicfarming
 capture rename	 	a39	 	lessfavouredarea
 capture rename	 	a41	 	altitudezone
 capture rename	 	a44	 	structuralfunds
 capture rename	 	a45	 	environmentalconstraintsarea
 capture rename	 	year	 	year
 capture rename	 	a27	 	economicsizeeuro
 capture rename	 	a40	 	uaaunderirrigation
 capture rename	 	a42	 	commonageuaa
 capture rename	 	b48	 	uaainowneroccupation
 capture rename	 	b50	 	uaainsharecropping
 capture rename	 	se010	 	totallabourinputawu
 capture rename	 	se011	 	labourinputhours
 capture rename	 	se016	 	unpaidlabourinputhours
 capture rename	 	se021	 	paidlabourinputhours
 capture rename	 	se025	 	totaluaa
 capture rename	 	se030	 	renteduaa
 capture rename	 	se035	 	cerealsuaa
 capture rename	 	se041	 	otherfieldcropsuaa
 capture rename	 	se042	 	energycropsuaa
 capture rename	 	se046	 	vegetablesandflowersuaa
 capture rename	 	se050	 	vineyardsuaa
 capture rename	 	se054	 	permanentcropsuaa
 capture rename	 	se055	 	orchardsuaa
 capture rename	 	se060	 	olivegrovesuaa
 capture rename	 	se065	 	otherpermanentcropsuaa
 capture rename	 	se071	 	foragecropsuaa
 capture rename	 	se072	 	agriculturalfallowsuaa
 capture rename	 	se073	 	setasideuaa
 capture rename	 	se075	 	woodlandarea
 capture rename	 	se080	 	totallivestockunits
 capture rename	 	se085	 	dairycowslus
 capture rename	 	se090	 	othercattlelus
 capture rename	 	se095	 	sheepandgoatslus
 capture rename	 	se100	 	pigslus
 capture rename	 	se105	 	poultrylus
 capture rename	 	se110	 	wheatyield
 capture rename	 	se115	 	maizeyield
 capture rename	 	se120	 	stockingdensity
 capture rename	 	se120d	 	foragearea
 capture rename	 	se120n	 	grazinglivestock
 capture rename	 	se125	 	milkyield
 capture rename	 	se125d	 	dairycows
 capture rename	 	se125n	 	dairyproducts
 capture rename	 	se131	 	totaloutput
 capture rename	 	se135	 	totaloutputcrops
 capture rename	 	se140	 	cerealsvalue
 capture rename	 	se145	 	proteincropsvalue
 capture rename	 	se146	 	energycropsvalue
 capture rename	 	se150	 	potatoesvalue
 capture rename	 	se155	 	sugarbeetvalue
 capture rename	 	se160	 	oilseedrapevalue
 capture rename	 	se165	 	industrialcropsvalue
 capture rename	 	se170	 	vegetablesandflowersvalue
 capture rename	 	se175	 	fruitvalue
 capture rename	 	se180	 	citrusfruitvalue
 capture rename	 	se185	 	wineandgrapesvalue
 capture rename	 	se190	 	olivesandoliveoilvalue
 capture rename	 	se195	 	foragecropsvalue
 capture rename	 	se200	 	othercropoutputvalue
 capture rename	 	se206	 	totaloutputlivestock
 capture rename	 	se211	 	changesinvalueoflivestock
 capture rename	 	se216	 	cowsmilkandmilkproducts
 capture rename	 	se220	 	beefandveal
 capture rename	 	se225	 	pigmeat
 capture rename	 	se230	 	sheepandgoats
 capture rename	 	se235	 	poultrymeat
 capture rename	 	se240	 	eggs
 capture rename	 	se245	 	ewesandgoatsmilk
 capture rename	 	se251	 	otherlivestockandproducts
 capture rename	 	se256	 	otheroutput
 capture rename	 	se270	 	totalinputs
 capture rename	 	se275	 	totalintermediateconsumption
 capture rename	 	se281	 	totalspecificcosts
 capture rename	 	se285	 	seedsandplants
 capture rename	 	se290	 	seedsandplantshomegrown
 capture rename	 	se295	 	fertilisers
 capture rename	 	se300	 	cropprotection
 capture rename	 	se305	 	othercropspecific
 capture rename	 	se310	 	feedforgrazinglivestock
 capture rename	 	se315	 	feedforgrazinglivestockhomegrown
 capture rename	 	se320	 	feedforpigspoultry
 capture rename	 	se325	 	feedforpigspoultryhomegrown
 capture rename	 	se330	 	otherlivestockspecificcosts
 capture rename	 	se331	 	forestryspecificcosts
 capture rename	 	se336	 	totalfarmingoverheads
 capture rename	 	se340	 	machininerybuildingcurrentcosts
 capture rename	 	se345	 	energy
 capture rename	 	se350	 	contractwork
 capture rename	 	se356	 	otherdirectinputs
 capture rename	 	se360	 	depreciation
 capture rename	 	se365	 	totalexternalfactors
 capture rename	 	se370	 	wagespaid
 capture rename	 	se375	 	rentpaid
 capture rename	 	se380	 	interestpaid
 capture rename	 	se390	 	taxes
 capture rename	 	se395	 	vatbalanceexclinvest
 capture rename	 	se405	 	balancesubsidiestaxesinvest
 capture rename	 	se406	 	subsidiesoninvest
 capture rename	 	se407	 	paymentstodairyoutgoers
 capture rename	 	se408	 	vatoninvest
 capture rename	 	se410	 	grossfarmincome
 capture rename	 	se415	 	farmnetvalueadded
 capture rename	 	se420	 	familyfarmincome
 capture rename	 	se425	 	farmnetvalueaddedawu
 capture rename	 	se425d	 	awu
 capture rename	 	se425n	 	farmnetvalueaddedn
 capture rename	 	v116		farmnetvalueaddedn
 capture rename	 	se430	 	familyfarmincomefwu
 capture rename	 	se430d	 	fwu
 capture rename	 	se430n	 	familyfarmincomen
 capture rename	 	v119	 	familyfarmincomen
 capture rename	 	se436	 	totalassets
 capture rename	 	se441	 	totalfixedassets
 capture rename	 	se446	 	landpermananentcropsquotas
 capture rename	 	se450	 	buildings
 capture rename	 	se455	 	machinery
 capture rename	 	se460	 	breedinglivestock
 capture rename	 	se465	 	totalcurrentassets
 capture rename	 	se470	 	nonbreedinglivestock
 capture rename	 	se475	 	stockofagriculturalproducts
 capture rename	 	se480	 	othercirculatingcapital
 capture rename	 	se485	 	totalliabilities
 capture rename	 	se490	 	longmediumtermloans
 capture rename	 	se495	 	shorttermloans
 capture rename	 	se501	 	networth
 capture rename	 	se506	 	changeinnetworth
 capture rename	 	se510	 	averagefarmcapital
 capture rename	 	se516	 	grossinvestment
 capture rename	 	se521	 	netinvestment
 capture rename	 	se526	 	cashflow1
 capture rename	 	se530	 	cashflow2
 capture rename	 	se600	 	balancecurrentsubsidiestaxes
 capture rename	 	se605	 	totalsubsidiesexcludingoninvestm
 capture rename	 	se610	 	totalsubsidiesoncrops
 capture rename	 	se611	 	compensatorypaymentsareapayments
 capture rename	 	se612	 	setasidepremiums
 capture rename	 	se613	 	othercropssubsidies
 capture rename	 	se615	 	totalsubsidiesonlivestock
 capture rename	 	se616	 	subsidiesdairying
 capture rename	 	se617	 	subsidiesothercattle
 capture rename	 	se618	 	subsidiessheepgoats
 capture rename	 	se619	 	otherlivestocksubsidies
 capture rename	 	se620	 	othersubsidies
 capture rename	 	se621	 	environmentalsubsidies
 capture rename	 	se622	 	lfasubsidies
 capture rename	 	se623	 	otherruraldevelopmentpayments
 capture rename	 	se625	 	subsidiesonintermediateconsumpti
 capture rename	 	se626	 	subsidiesonexternalfactors
 capture rename	 	se630	 	decoupledpayments
 capture rename	 	se631	 	singlefarmpayment
 capture rename	 	se632	 	singleareapayment
 capture rename	 	se640	 	additionalaid
 capture rename	 	sys02	 	farmsrepresented
 capture rename	 	sys03	 	samplefarms
 capture rename	 	sys04	 	exchangerate
	 		 	

* from 2nd data request			 	
 capture rename	 	a1	 	region
 capture rename	 	a2	 	subregion
 capture rename	 	a24	 	country
 capture rename	 	a3	 	farmcode
 capture rename	 	year	 	year
 capture rename	 	c01aw	 	unpaidregholdermgr1awu
 capture rename	 	c01hr	 	unpaidregholdermgr1ahr
 capture rename	 	c01yr	 	unpaidregholdermgr1yb
 capture rename	 	c02aw	 	unpaidregholdermgr2awu
 capture rename	 	c02hr	 	unpaidregholdermgr2ahr
 capture rename	 	c02yr	 	unpaidregholdermgr2yb
 capture rename	 	c03aw	 	unpaidregholdermgr3awu
 capture rename	 	c03hr	 	unpaidregholdermgr3ahr
 capture rename	 	c03yr	 	unpaidregholdermgr3yb
 capture rename	 	c09aw	 	regpaidlabourmgrawu
 capture rename	 	c09hr	 	regpaidlabourmgrahr
 capture rename	 	c09yr	 	regpaidmanagerage
 capture rename	 	g96bv	 	permanentcropsbv
 capture rename	 	g96cv	 	permanentcropscv
 capture rename	 	g96dp	 	permanentcropsdp
 capture rename	 	g96ig	 	permanentcropsig
 capture rename	 	g96sa	 	permanentcropssa
 capture rename	 	g96su	 	permanentcropssu
 capture rename	 	h104a	 	longandmediumtermloansa
 capture rename	 	h104b	 	longandmediumtermloansb
 capture rename	 	h104c	 	longandmediumtermloansc
 capture rename	 	h104d	 	longandmediumtermloansd
 capture rename	 	h104e	 	longandmediumtermloanse
 capture rename	 	h104f	 	longandmediumtermloansf
 capture rename	 	h104g	 	longandmediumtermloansg
 capture rename	 	h104h	 	longandmediumtermloansh
 capture rename	 	h105a	 	shorttermloanscreditorsa
 capture rename	 	h105b	 	shorttermloanscreditorsb
 capture rename	 	h105c	 	shorttermloanscreditorsc
 capture rename	 	h105d	 	shorttermloanscreditorsd
 capture rename	 	h105e	 	shorttermloanscreditorse
 capture rename	 	h105f	 	shorttermloanscreditorsf
 capture rename	 	h105g	 	shorttermloanscreditorsg
 capture rename	 	h105h	 	shorttermloanscreditorsh
 capture rename	 	h106a	 	totaldebtsa
 capture rename	 	h106b	 	totaldebtsb
 capture rename	 	h106c	 	totaldebtsc
 capture rename	 	h106d	 	totaldebtsd
 capture rename	 	h106e	 	totaldebtse
 capture rename	 	h106f	 	totaldebtsf
 capture rename	 	h106g	 	totaldebtsg
 capture rename	 	h106h	 	totaldebtsh
 capture rename	 	jc132	 	subsidiesforoilseed
 capture rename	 	jc156	 	subsforpermanentcropsunde
 capture rename	 	jc158	 	subsidiesforotherpermanent
 capture rename	 	jc331	 	subsidiesforrape
 capture rename	 	jc332	 	subsidiesforsunflower
 capture rename	 	jc333	 	subsidiesforsoja
 capture rename	 	jc334	 	subsidiesforother
 capture rename	 	jc670	 	singlepayment
 capture rename	 	jc680	 	singleareapayment
 capture rename	 	jc700	 	subsbeef
 capture rename	 	jc800	 	subsenvironment
 capture rename	 	jc820	 	subsforlfa
 capture rename	 	jc835	 	supporttoadvisoryservices
 capture rename	 	jc953	 	subsotherruraldev
 capture rename	 	jc955	 	additionalaid
 capture rename	 	k131aa	 	sugarbeetaa
 capture rename	 	k131bv	 	sugarbeetbv
 capture rename	 	k131cv	 	sugarbeetcv
 capture rename	 	k131fc	 	sugarbeetfc
 capture rename	 	k131qq	 	sugarbeetqq
 capture rename	 	k131sa	 	sugarbeetsa
 capture rename	 	k131ta	 	sugarbeetta
 capture rename	 	k131tp	 	sugarbeettp
 capture rename	 	k132aa	 	oilseedaa
 capture rename	 	k132bv	 	oilseedbv
 capture rename	 	k132cv	 	oilseedcv
 capture rename	 	k132fc	 	oilseedfc
 capture rename	 	k132fu	 	oilseedfu
 capture rename	 	k132qq	 	oilseedqq
 capture rename	 	k132sa	 	oilseedsa
 capture rename	 	k132ta	 	oilseedta
 capture rename	 	k132tp	 	oilseedtp
 capture rename	 	k146aa	 	fallowlandaa
 capture rename	 	k146bv	 	fallowlandbv
 capture rename	 	k146cv	 	fallowlandcv
 capture rename	 	k146fc	 	fallowlandfc
 capture rename	 	k146fu	 	fallowlandfu
 capture rename	 	k146ouaa	 	obligatoryuncultivaa
 capture rename	 	k146oubv	 	obligatoryuncultivbv
 capture rename	 	k146oucv	 	obligatoryuncultivcv
 capture rename	 	k146oufc	 	obligatoryuncultivfc
 capture rename	 	k146oufu	 	obligatoryuncultivfu
 capture rename	 	k146ouqq	 	obligatoryuncultivqq
 capture rename	 	k146ousa	 	obligatoryuncultivsa
 capture rename	 	k146outp	 	obligatoryuncultivtp
 capture rename	 	k146qq	 	fallowlandqq
 capture rename	 	k146sa	 	fallowlandsa
 capture rename	 	k146tp	 	fallowlandtp
 capture rename	 	k158aa	 	othpermcropsaa
 capture rename	 	k158bv	 	othpermcropsbv
 capture rename	 	k158cv	 	othpermcropscv
 capture rename	 	k158fc	 	othpermcropsfc
 capture rename	 	k158fu	 	othpermcropsfu
 capture rename	 	k158qq	 	othpermcropsqq
 capture rename	 	k158sa	 	othpermcropssa
 capture rename	 	k158tp	 	othpermcropstp
 capture rename	 	k177bv	 	contractworkforothersbv
 capture rename	 	k177cv	 	contractworkforotherscv
 capture rename	 	k177fc	 	contractworkforothersfc
 capture rename	 	k177fu	 	contractworkforothersfu
 capture rename	 	k177qq	 	contractworkforothersqq
 capture rename	 	k177sa	 	contractworkforotherssa
 capture rename	 	k177tp	 	contractworkforotherstp
 capture rename	 	k331aa	 	rapeaa
 capture rename	 	k331bv	 	rapebv
 capture rename	 	k331cv	 	rapecv
 capture rename	 	k331fc	 	rapefc
 capture rename	 	k331fu	 	rapefu
 capture rename	 	k331qq	 	rapeqq
 capture rename	 	k331sa	 	rapesa
 capture rename	 	k331tp	 	rapetp
 capture rename	 	k332aa	 	sunfloweraa
 capture rename	 	k332bv	 	sunflowerbv
 capture rename	 	k332cv	 	sunflowercv
 capture rename	 	k332fc	 	sunflowerfc
 capture rename	 	k332fu	 	sunflowerfu
 capture rename	 	k332qq	 	sunflowerqq
 capture rename	 	k332sa	 	sunflowersa
 capture rename	 	k332tp	 	sunflowertp
 capture rename	 	k333aa	 	soyaaa
 capture rename	 	k333bv	 	soyabv
 capture rename	 	k333cv	 	soyacv
 capture rename	 	k333fc	 	soyafc
 capture rename	 	k333fu	 	soyafu
 capture rename	 	k333qq	 	soyaqq
 capture rename	 	k333sa	 	soyasa
 capture rename	 	k333tp	 	soyatp
 capture rename	 	k334aa	 	otheraa
 capture rename	 	k334bv	 	otherbv
 capture rename	 	k334cv	 	othercv
 capture rename	 	k334fc	 	otherfc
 capture rename	 	k334fu	 	otherfu
 capture rename	 	k334qq	 	otherqq
 capture rename	 	k334sa	 	othersa
 capture rename	 	k334tp	 	othertp
 capture rename	 	k346aa	 	sugarcaneaa
 capture rename	 	k346bv	 	sugarcanebv
 capture rename	 	k346cv	 	sugarcanecv
 capture rename	 	k346fc	 	sugarcanefc
 capture rename	 	k346fu	 	sugarcanefu
 capture rename	 	k346qq	 	sugarcaneqq
 capture rename	 	k346sa	 	sugarcanesa
 capture rename	 	k346tp	 	sugarcanetp
 capture rename	 	k364aa	 	flaxnotfibflaxaa
 capture rename	 	k364bv	 	flaxnotfibflaxbv
 capture rename	 	k364cv	 	flaxnotfibflaxcv
 capture rename	 	k364fc	 	flaxnotfibflaxfc
 capture rename	 	k364fu	 	flaxnotfibflaxfu
 capture rename	 	k364qq	 	flaxnotfibflaxqq
 capture rename	 	k364sa	 	flaxnotfibflaxsa
 capture rename	 	k364tp	 	flaxnotfibflaxtp
 capture rename	 	kforstaa	 	forestryaa
 capture rename	 	kforstbv	 	forestrybv
 capture rename	 	kforstcv	 	forestrycv
 capture rename	 	kforstfc	 	forestryfc
 capture rename	 	kforstfu	 	forestryfu
 capture rename	 	kforstqq	 	forestryqq
 capture rename	 	kforstsa	 	forestrysa
 capture rename	 	kforsttp	 	forestrytp
 capture rename	 	knfcaa	 	totnfoodcrsetasaraa
 capture rename	 	knfcbv	 	totnfoodcrsetasarbv
 capture rename	 	knfccv	 	totnfoodcrsetasarcv
 capture rename	 	knfcfc	 	totnfoodcrsetasarfc
 capture rename	 	knfcfu	 	totnfoodcrsetasarfu
 capture rename	 	knfcqq	 	totnfoodcrsetasarqq
 capture rename	 	knfcsa	 	totnfoodcrsetasarsa
 capture rename	 	knfctp	 	totnfoodcrsetasartp
 capture rename	 	l421a	 	qusugarbeetpurchase
 capture rename	 	l421b	 	qusugarbeetsales
 capture rename	 	l421c	 	qusugarbeetopeningval
 capture rename	 	l421d	 	qusugarbeetdepreciation
 capture rename	 	l421e	 	qusugarbeetclosingval
 capture rename	 	l421f	 	qusugarbeettaxes
 capture rename	 	l421g	 	qusugarbeetrentpaid
 capture rename	 	l421h	 	qusugarbeetrentreceived
 capture rename	 	l421i	 	qusugarbeetquantity
 capture rename	 	m603aa	 	compensationoilseedcropsaa
 capture rename	 	m603cp	 	compensationoilseedcropscp
 capture rename	 	m603ry	 	compensationoilseedcropsry
 capture rename	 	m623aa	 	compirroilseedcropsaa
 capture rename	 	m623cp	 	compirroilseedcropscp
 capture rename	 	m623ry	 	compirroilseedcropsry
 capture rename	 	m650aa	 	sanonfoodonsaaa
 capture rename	 	m650cp	 	sanonfoodonsacp
 capture rename	 	m650ry	 	sanonfoodonsary
 capture rename	 	m655aa	 	energycropsaa
 capture rename	 	m655cp	 	energycropscp
 capture rename	 	m670aa	 	spdetailsaa
 capture rename	 	m674aa	 	spspecentitlaa
 capture rename	 	m680aa	 	singleareapaa
 capture rename	 	sys02	 	farmsrepresented
 capture rename	 	sys03	 	samplefarms
 capture rename	 	sys04	 	exchangerate


* from 3rd data request			 	
capture rename 		d23av		CalvesforFattAV
capture rename 		d23bn		CalvesforFattBN
capture rename 		d23bv		CalvesforFattBV
capture rename 		d23cn		CalvesforFattCN
capture rename 		d23cv		CalvesforFattCV
capture rename 		d23dg		CalvesforFattDG
capture rename 		d23dr		CalvesforFattDR
capture rename 		d23lu		CalvesforFattLU
capture rename 		d23pi		CalvesforFattPI
capture rename 		d24av		OtherCattleLT1yrAV
capture rename 		d24bn		OtherCattleLT1yrBN
capture rename 		d24bv		OtherCattleLT1yrBV
capture rename 		d24cn		OtherCattleLT1yrCN
capture rename 		d24cv		OtherCattleLT1yrCV
capture rename 		d24dg		OtherCattleLT1yrDG
capture rename 		d24dr		OtherCattleLT1yrDR
capture rename 		d24lu		OtherCattleLT1yrLU
capture rename 		d24pi		OtherCattleLT1yrPI
capture rename 		d25av		malecattle1LT2yrsAV
capture rename 		d25bn		malecattle1LT2yrsBN
capture rename 		d25bv		malecattle1LT2yrsBV
capture rename 		d25cn		malecattle1LT2yrsCN
capture rename 		d25cv		malecattle1LT2yrsCV
capture rename 		d25dg		malecattle1LT2yrsDG
capture rename 		d25dr		malecattle1LT2yrsDR
capture rename 		d25lu		malecattle1LT2yrsLU
capture rename 		d25pi		malecattle1LT2yrsPI
capture rename 		d26av		femalecattle1LT2yrsAV
capture rename 		d26bn		femalecattle1LT2yrsBN
capture rename 		d26bv		femalecattle1LT2yrsBV
capture rename 		d26cn		femalecattle1LT2yrsCN
capture rename 		d26cv		femalecattle1LT2yrsCV
capture rename 		d26dg		femalecattle1LT2yrsDG
capture rename 		d26dr		femalecattle1LT2yrsDR
capture rename 		d26lu		femalecattle1LT2yrsLU
capture rename 		d26pi		femalecattle1LT2yrsPI
capture rename 		d27av		malecattleGTE2yrsAV
capture rename 		d27bn		malecattleGTE2yrsBN
capture rename 		d27bv		malecattleGTE2yrsBV
capture rename 		d27cn		malecattleGTE2yrsCN
capture rename 		d27cv		malecattleGTE2yrsCV
capture rename 		d27dg		malecattleGTE2yrsDG
capture rename 		d27dr		malecattleGTE2yrsDR
capture rename 		d27lu		malecattleGTE2yrsLU
capture rename 		d27pi		malecattleGTE2yrsPI
capture rename 		d28av		breedingheifersAV
capture rename 		d28bn		breedingheifersBN
capture rename 		d28bv		breedingheifersBV
capture rename 		d28cn		breedingheifersCN
capture rename 		d28cv		breedingheifersCV
capture rename 		d28dg		breedingheifersDG
capture rename 		d28dr		breedingheifersDR
capture rename 		d28lu		breedingheifersLU
capture rename 		d28pi		breedingheifersPI
capture rename 		d29av		heifersforfatteningAV
capture rename 		d29bn		heifersforfatteningBN
capture rename 		d29bv		heifersforfatteningBV
capture rename 		d29cn		heifersforfatteningCN
capture rename 		d29cv		heifersforfatteningCV
capture rename 		d29dg		heifersforfatteningDG
capture rename 		d29dr		heifersforfatteningDR
capture rename 		d29lu		heifersforfatteningLU
capture rename 		d29pi		heifersforfatteningPI
capture rename 		d30av		dairycowsAV
capture rename 		d30bn		dairycowsBN
capture rename 		d30bv		dairycowsBV
capture rename 		d30cn		dairycowsCN
capture rename 		d30cv		dairycowsCV
capture rename 		d30dg		dairycowsDG
capture rename 		d30dr		dairycowsDR
capture rename 		d30pi		dairycowsPI
capture rename 		d31av		culldairycowsAV
capture rename 		d31bn		culldairycowsBN
capture rename 		d31bv		culldairycowsBV
capture rename 		d31cn		culldairycowsCN
capture rename 		d31cv		culldairycowsCV
capture rename 		d31dg		culldairycowsDG
capture rename 		d31dr		culldairycowsDR
capture rename 		d31lu		culldairycowsLU
capture rename 		d31pi		culldairycowsPI
capture rename 		d32av		othercowsAV
capture rename 		d32bn		othercowsBN
capture rename 		d32bv		othercowsBV
capture rename 		d32cn		othercowsCN
capture rename 		d32cv		othercowsCV
capture rename 		d32dg		othercowsDG
capture rename 		d32dr		othercowsDR
capture rename 		d32lu		othercowsLU
capture rename 		d32pi		othercowsPI
capture rename 		d40pi		ewesPI
capture rename 		d41av		othersheepAV
capture rename 		d41bn		othersheepBN
capture rename 		d41bv		othersheepBV
capture rename 		d41cn		othersheepCN
capture rename 		d41cv		othersheepCV
capture rename 		d41dg		othersheepDG
capture rename 		d41dr		othersheepDR
capture rename 		d41lu		othersheepLU
capture rename 		d41pi		othersheepPI
capture rename 		e52fc		cattleFC
capture rename 		e52no		cattleNO
capture rename 		e52pu		cattlePU
capture rename 		e52sa		cattleSA
capture rename 		e52to		cattleTO
capture rename 		e54dr		sheepDR
capture rename 		e54fc		sheepFC
capture rename 		e54no		sheepNO
capture rename 		e54pu		sheepPU
capture rename 		e54sa		sheepSA
capture rename 		e54to		sheepTO
capture rename 		f61		upkeepofmachequipment
capture rename 		f62		motorfuelandlubricants
capture rename 		f64		confeedforgrazlivpurch
capture rename 		f65		coarsefoddergrazlivpurch
capture rename 		f78		upkeeplandimprovandbuild
capture rename 		f79		electricity
capture rename 		f80		heatingfuels
capture rename 		f81		water
capture rename 		f82		insurance
capture rename 		f86		rentalvalue
capture rename 		g95bv		agriculturallandBV
capture rename 		g95cv		agriculturallandCV
capture rename 		g99ag		acqcostsquotasothrightAG
capture rename 		g99an		acqcostsquotasothrightAN
capture rename 		g99bv		acqcostsquotasothrightBV
capture rename 		g99cv		acqcostsquotasothrightCV
capture rename 		g99dp		acqcostsquotasothrightDP
capture rename 		g99ig		acqcostsquotasothrightIG
capture rename 		g99sa		acqcostsquotasothrightSA
capture rename 		g99su		acqcostsquotasothrightSU
capture rename 		jc64		Subsforconcentfeedingstuffs
capture rename 		jc65		Subsforcoarsefodderpurchas
capture rename 		jc74		Subsforfertilizersandsoil
capture rename 		jc75		Subsforcropprotectionprodu
capture rename 		jc770		DairyPremium
capture rename 		jc78		Subsforlandimprovbuildi
capture rename 		k147aa		temporarygrassAA
capture rename 		k147bv		temporarygrassBV
capture rename 		k147cv		temporarygrassCV
capture rename 		k147fc		temporarygrassFC
capture rename 		k147fu		temporarygrassFU
capture rename 		k147qq		temporarygrassQQ
capture rename 		k147sa		temporarygrassSA
capture rename 		k147tp		temporarygrassTP
capture rename 		k150aa		meadopermpastAA
capture rename 		k150bv		meadopermpastBV
capture rename 		k150cv		meadopermpastCV
capture rename 		k150fc		meadopermpastFC
capture rename 		k150fu		meadopermpastFU
capture rename 		k150qq		meadopermpastQQ
capture rename 		k150sa		meadopermpastSA
capture rename 		k150tp		meadopermpastTP
capture rename 		k151aa		roughgrazingAA
capture rename 		k151bv		roughgrazingBV
capture rename 		k151cv		roughgrazingCV
capture rename 		k151fc		roughgrazingFC
capture rename 		k151fu		roughgrazingFU
capture rename 		k151qq		roughgrazingQQ
capture rename 		k151sa		roughgrazingSA
capture rename 		k151tp		roughgrazingTP
capture rename 		l401a		milkquotapurchases
capture rename 		l401b		milkquotasales
capture rename 		l401c		milkquotaopenvaluation
capture rename 		l401d		milkquotadepreciation
capture rename 		l401e		milkquotaclosingvaluation
capture rename 		l401f		milkquotataxes
capture rename 		l401g		milkquotarentpaid
capture rename 		l401h		milkquotarentreceived
capture rename 		l401i		milkquotaquant100kg
capture rename 		l402a		qusucklercowprempurch
capture rename 		l402b		qusucklercowpremsales
capture rename 		l402c		qusucklercowpremopvalue
capture rename 		l402d		qusucklercowpremdeprec
capture rename 		l402e		qusucklercowpremclosvalue
capture rename 		l402f		qusucklercowpremtaxes
capture rename 		l402g		qusucklercowpremrentpaid
capture rename 		l402h		qusucklercowpremrentrec
capture rename 		l402i		qusucklercowpremheads
capture rename 		l403a		qumalecattleprempurchases
capture rename 		l403b		qumalecattlepremsales
capture rename 		l403c		qumalecattlepremopenvalue
capture rename 		l403d		qumalecattlepremdeprec
capture rename 		l403e		qumalecattlepremclosvalue
capture rename 		l403f		qumalecattlepremtaxes
capture rename 		l403g		qumalecattlepremrentpaid
capture rename 		l403h		qumalecattlepremrentrec


* from 4th data version (got it from Fiona later... had been misplaced)
capture rename 		d22av		horsesAV
capture rename 		d22bn		horsesBN
capture rename 		d22bv		horsesBV
capture rename 		d22cn		horsesCN
capture rename 		d22cv		horsesCV
capture rename 		d22dg		horsesDG
capture rename 		d22dr		horsesDR
capture rename 		d22lu		horsesLU
capture rename 		d22pi		horsesPI

capture rename 		d30av		dairycowsAV
capture rename 		d30bn		dairycowsBN
capture rename 		d30bv		dairycowsBV
capture rename 		d30cn		dairycowsCN
capture rename 		d30cv		dairycowsCV
capture rename 		d30dg		dairycowsDG
capture rename 		d30dr		dairycowsDR
capture rename 		d30lu		dairycowsLU
capture rename 		d30pi		dairycowsPI

capture rename 		d38av		goatsbreedingfemAV
capture rename 		d38bn		goatsbreedingfemBN
capture rename 		d38bv		goatsbreedingfemBV
capture rename 		d38cn		goatsbreedingfemCN
capture rename 		d38cv		goatsbreedingfemCV
capture rename 		d38dg		goatsbreedingfemDG
capture rename 		d38dr		goatsbreedingfemDR
capture rename 		d38lu		goatsbreedingfemLU
capture rename 		d38pi		goatsbreedingfemPI

capture rename 		d39av		othergoatsAV
capture rename 		d39bn		othergoatsBN
capture rename 		d39bv		othergoatsBV
capture rename 		d39cn		othergoatsCN
capture rename 		d39cv		othergoatsCV
capture rename 		d39dg		othergoatsDG
capture rename 		d39dr		othergoatsDR
capture rename 		d39lu		othergoatsLU
capture rename 		d39pi		othergoatsPI

capture rename 		d40av		ewesAV
capture rename 		d40bn		ewesBN
capture rename 		d40bv		ewesBV
capture rename 		d40cn		ewesCN
capture rename 		d40cv		ewesCV
capture rename 		d40dg		ewesDG
capture rename 		d40dr		ewesDR
capture rename 		d40lu		ewesLU
capture rename 		d40pi		ewesP

capture rename 		k144aa		fodderrootsbrassicasAA
capture rename 		k144bv		fodderrootsbrassicasBV
capture rename 		k144cv		fodderrootsbrassicasCV
capture rename 		k144fc		fodderrootsbrassicasFC
capture rename 		k144fu		fodderrootsbrassicasFU
capture rename 		k144qq		fodderrootsbrassicasQQ
capture rename 		k144sa		fodderrootsbrassicasSA
capture rename 		k144tp		fodderrootsbrassicasTP

capture rename 		k145aa		othforageplantsAA
capture rename 		k145bv		othforageplantsBV
capture rename 		k145cv		othforageplantsCV
capture rename 		k145fc		othforageplantsFC
capture rename 		k145fu		othforageplantsFU
capture rename 		k145qq		othforageplantsQQ
capture rename 		k145sa		othforageplantsSA
capture rename 		k145tp		othforageplantsTP

capture rename 		k148aa		otharabcropsAA
capture rename 		k148bv		otharabcropsBV
capture rename 		k148cv		otharabcropsCV
capture rename 		k148fc		otharabcropsFC
capture rename 		k148fu		otharabcropsFU
capture rename 		k148qq		otharabcropsQQ
capture rename 		k148sa		otharabcropsSA
capture rename 		k148tp		otharabcropsTP

capture rename 		k149aa		leasedtoothersAA
capture rename 		k149bv		leasedtoothersBV
capture rename 		k149cv		leasedtoothersCV
capture rename 		k149fc		leasedtoothersFC
capture rename 		k149fu		leasedtoothersFU
capture rename 		k149qq		leasedtoothersQQ
capture rename 		k149sa		leasedtoothersSA
capture rename 		k149tp		leasedtoothersTP

capture rename 		n24sn		othcattleLT12mSN
capture rename 		n24sv		othcattleLT12mSV

capture rename 		se005		economicsizeesu
capture rename 		se015		unpaidlabourawu
capture rename 		se020		paidlabourawu
capture rename 		se110d 		commonwheatAA
capture rename 		se110n 		commonwheatQQ
capture rename 		se115d 		grainmaizeAA
capture rename 		se115n 		grainmaizeQQ
capture rename 		se260 		farmhouseconsumption
capture rename 		se265  		farmuse
capture rename 		sys12  		farmsrepresentedclu
capture rename 		sys13 		samplefarmsclu


 
