* from standard results    
capture label variable  region   a1
capture label variable  organisationalform   a18
capture label variable  subregion   a2
capture label variable  country   a24
capture label variable  sizeclass   a26
capture label variable  generalfarmtype   a28
capture label variable  principalfarmtype   a29
capture label variable  farmcode   a3
capture label variable  system   a30 
capture label variable  organicfarming   a32
capture label variable  lessfavouredarea   a39
capture label variable  altitudezone   a41
capture label variable  structuralfunds   a44
capture label variable  environmentalconstraintsarea   a45
capture label variable  year   year
capture label variable  economicsize   a27
capture label variable  uaaunderirrigation   a40
capture label variable  commonageuaa   a42
capture label variable  uaainowneroccupation   b48
capture label variable  uaainsharecropping   b50
capture label variable  totallabourinputawu   se010
capture label variable  labourinputhours   se011
capture label variable  unpaidlabourinputhours   se016
capture label variable  paidlabourinputhours   se021
capture label variable  totaluaa   se025
capture label variable  renteduaa   se030
capture label variable  cerealsuaa   se035
capture label variable  otherfieldcropsuaa   se041
capture label variable  energycropsuaa   se042
capture label variable  vegetablesandflowersuaa   se046
capture label variable  vineyardsuaa   se050
capture label variable  permanentcropsuaa   se054
capture label variable  orchardsuaa   se055
capture label variable  olivegrovesuaa   se060
capture label variable  otherpermanentcropsuaa   se065
capture label variable  foragecropsuaa   se071
capture label variable  agriculturalfallowsuaa   se072
capture label variable  setasideuaa   se073
capture label variable  woodlandarea   se075
capture label variable  totallivestockunits   se080
capture label variable  dairycowslus   se085
capture label variable  othercattlelus   se090
capture label variable  sheepandgoatslus   se095
capture label variable  pigslus   se100
capture label variable  poultrylus   se105
capture label variable  wheatyield   se110
capture label variable  maizeyield   se115
capture label variable  stockingdensity   se120
capture label variable  foragearea   se120d
capture label variable  grazinglivestock   se120n
capture label variable  milkyield   se125
capture label variable  dairycows   se125d
capture label variable  dairyproducts   se125n
capture label variable  totaloutput   se131
capture label variable  totaloutputcrops   se135
capture label variable  cerealsvalue   se140
capture label variable  proteincropsvalue   se145
capture label variable  energycropsvalue   se146
capture label variable  potatoesvalue   se150
capture label variable  sugarbeetvalue   se155
capture label variable  oilseedrapevalue   se160
capture label variable  industrialcropsvalue   se165
capture label variable  vegetablesandflowersvalue   se170
capture label variable  fruitvalue   se175
capture label variable  citrusfruitvalue   se180
capture label variable  wineandgrapesvalue   se185
capture label variable  olivesandoliveoilvalue   se190
capture label variable  foragecropsvalue   se195
capture label variable  othercropoutputvalue   se200
capture label variable  totaloutputlivestock   se206
capture label variable  changesinvalueoflivestock   se211
capture label variable  cowsmilkandmilkproducts   se216
capture label variable  beefandveal   se220
capture label variable  pigmeat   se225
capture label variable  sheepandgoats   se230
capture label variable  poultrymeat   se235
capture label variable  eggs   se240
capture label variable  ewesandgoatsmilk   se245
capture label variable  otherlivestockandproducts   se251
capture label variable  otheroutput   se256
capture label variable  totalinputs   se270
capture label variable  totalintermediateconsumption   se275
capture label variable  totalspecificcosts   se281
capture label variable  seedsandplants   se285
capture label variable  seedsandplantshomegrown   se290
capture label variable  fertilisers   se295
capture label variable  cropprotection   se300
capture label variable  othercropspecific   se305
capture label variable  feedforgrazinglivestock   se310
capture label variable  feedforgrazinglivestockhomegrown   se315
capture label variable  feedforpigspoultry   se320
capture label variable  feedforpigspoultryhomegrown   se325
capture label variable  otherlivestockspecificcosts   se330
capture label variable  forestryspecificcosts   se331
capture label variable  totalfarmingoverheads   se336
capture label variable  machininerybuildingcurrentcosts   se340
capture label variable  energy   se345
capture label variable  contractwork   se350
capture label variable  otherdirectinputs   se356
capture label variable  depreciation   se360
capture label variable  totalexternalfactors   se365
capture label variable  wagespaid   se370
capture label variable  rentpaid   se375
capture label variable  interestpaid   se380
capture label variable  taxes   se390
capture label variable  vatbalanceexclinvest   se395
capture label variable  balancesubsidiestaxesinvest   se405
capture label variable  subsidiesoninvest   se406
capture label variable  paymentstodairyoutgoers   se407
capture label variable  vatoninvest   se408
capture label variable  grossfarmincome   se410
capture label variable  farmnetvalueadded   se415
capture label variable  familyfarmincome   se420
capture label variable  farmnetvalueaddedawu   se425
capture label variable  awu   se425d
capture label variable  farmnetvalueaddedn   se425n
capture label variable  familyfarmincomefwu   se430
capture label variable  fwu   se430d
capture label variable  familyfarmincomen   se430n
capture label variable  totalassets   se436
capture label variable  totalfixedassets   se441
capture label variable  landpermananentcropsquotas   se446
capture label variable  buildings   se450
capture label variable  machinery   se455
capture label variable  breedinglivestock   se460
capture label variable  totalcurrentassets   se465
capture label variable  nonbreedinglivestock   se470
capture label variable  stockofagriculturalproducts   se475
capture label variable  othercirculatingcapital   se480
capture label variable  totalliabilities   se485
capture label variable  longmediumtermloans   se490
capture label variable  shorttermloans   se495
capture label variable  networth   se501
capture label variable  changeinnetworth   se506
capture label variable  averagefarmcapital   se510
capture label variable  grossinvestment   se516
capture label variable  netinvestment   se521
capture label variable  cashflow1   se526
capture label variable  cashflow2   se530
capture label variable  balancecurrentsubsidiestaxes   se600
capture label variable  totalsubsidiesexcludingoninvestm   se605
capture label variable  totalsubsidiesoncrops   se610
capture label variable  compensatorypaymentsareapayments   se611
capture label variable  setasidepremiums   se612
capture label variable  othercropssubsidies   se613
capture label variable  totalsubsidiesonlivestock   se615
capture label variable  subsidiesdairying   se616
capture label variable  subsidiesothercattle   se617
capture label variable  subsidiessheepgoats   se618
capture label variable  otherlivestocksubsidies   se619
capture label variable  othersubsidies   se620
capture label variable  environmentalsubsidies   se621
capture label variable  lfasubsidies   se622
capture label variable  otherruraldevelopmentpayments   se623
capture label variable  subsidiesonintermediateconsumpti   se625
capture label variable  subsidiesonexternalfactors   se626
capture label variable  decoupledpayments   se630
capture label variable  singlefarmpayment   se631
capture label variable  singleareapayment   se632
capture label variable  additionalaid   se640
capture label variable  farmsrepresented   sys02
capture label variable  samplefarms   sys03
capture label variable  exchangerate   sys04
     
* from 2nd data request     
capture label variable  region   a1
capture label variable  subregion   a2
capture label variable  country   a24
capture label variable  farmcode   a3
capture label variable  year   year
capture label variable  unpaidregholdermgr1awu   c01aw
capture label variable  unpaidregholdermgr1ahr   c01hr
capture label variable  unpaidregholdermgr1yb   c01yr
capture label variable  unpaidregholdermgr2awu   c02aw
capture label variable  unpaidregholdermgr2ahr   c02hr
capture label variable  unpaidregholdermgr2yb   c02yr
capture label variable  unpaidregholdermgr3awu   c03aw
capture label variable  unpaidregholdermgr3ahr   c03hr
capture label variable  unpaidregholdermgr3yb   c03yr
capture label variable  regpaidlabourmgrawu   c09aw
capture label variable  regpaidlabourmgrahr   c09hr
capture label variable  regpaidmanagerage   c09yr
capture label variable  permanentcropsbv   g96bv
capture label variable  permanentcropscv   g96cv
capture label variable  permanentcropsdp   g96dp
capture label variable  permanentcropsig   g96ig
capture label variable  permanentcropssa   g96sa
capture label variable  permanentcropssu   g96su
capture label variable  longandmediumtermloansa   h104a
capture label variable  longandmediumtermloansb   h104b
capture label variable  longandmediumtermloansc   h104c
capture label variable  longandmediumtermloansd   h104d
capture label variable  longandmediumtermloanse   h104e
capture label variable  longandmediumtermloansf   h104f
capture label variable  longandmediumtermloansg   h104g
capture label variable  longandmediumtermloansh   h104h
capture label variable  shorttermloanscreditorsa   h105a
capture label variable  shorttermloanscreditorsb   h105b
capture label variable  shorttermloanscreditorsc   h105c
capture label variable  shorttermloanscreditorsd   h105d
capture label variable  shorttermloanscreditorse   h105e
capture label variable  shorttermloanscreditorsf   h105f
capture label variable  shorttermloanscreditorsg   h105g
capture label variable  shorttermloanscreditorsh   h105h
capture label variable  totaldebtsa   h106a
capture label variable  totaldebtsb   h106b
capture label variable  totaldebtsc   h106c
capture label variable  totaldebtsd   h106d
capture label variable  totaldebtse   h106e
capture label variable  totaldebtsf   h106f
capture label variable  totaldebtsg   h106g
capture label variable  totaldebtsh   h106h
capture label variable  subsidiesforoilseed   jc132
capture label variable  subsforpermanentcropsunde   jc156
capture label variable  subsidiesforotherpermanent   jc158
capture label variable  subsidiesforrape   jc331
capture label variable  subsidiesforsunflower   jc332
capture label variable  subsidiesforsoja   jc333
capture label variable  subsidiesforother   jc334
capture label variable  singlepayment   jc670
capture label variable  singleareapayment   jc680
capture label variable  subsbeef   jc700
capture label variable  subsenvironment   jc800
capture label variable  subsforlfa   jc820
capture label variable  supporttoadvisoryservices   jc835
capture label variable  subsotherruraldev   jc953
capture label variable  additionalaid   jc955
capture label variable  sugarbeetaa   k131aa
capture label variable  sugarbeetbv   k131bv
capture label variable  sugarbeetcv   k131cv
capture label variable  sugarbeetfc   k131fc
capture label variable  sugarbeetqq   k131qq
capture label variable  sugarbeetsa   k131sa
capture label variable  sugarbeetta   k131ta
capture label variable  sugarbeettp   k131tp
capture label variable  oilseedaa   k132aa
capture label variable  oilseedbv   k132bv
capture label variable  oilseedcv   k132cv
capture label variable  oilseedfc   k132fc
capture label variable  oilseedfu   k132fu
capture label variable  oilseedqq   k132qq
capture label variable  oilseedsa   k132sa
capture label variable  oilseedta   k132ta
capture label variable  oilseedtp   k132tp
capture label variable  fallowlandaa   k146aa
capture label variable  fallowlandbv   k146bv
capture label variable  fallowlandcv   k146cv
capture label variable  fallowlandfc   k146fc
capture label variable  fallowlandfu   k146fu
capture label variable  obligatoryuncultivaa   k146ouaa
capture label variable  obligatoryuncultivbv   k146oubv
capture label variable  obligatoryuncultivcv   k146oucv
capture label variable  obligatoryuncultivfc   k146oufc
capture label variable  obligatoryuncultivfu   k146oufu
capture label variable  obligatoryuncultivqq   k146ouqq
capture label variable  obligatoryuncultivsa   k146ousa
capture label variable  obligatoryuncultivtp   k146outp
capture label variable  fallowlandqq   k146qq
capture label variable  fallowlandsa   k146sa
capture label variable  fallowlandtp   k146tp
capture label variable  othpermcropsaa   k158aa
capture label variable  othpermcropsbv   k158bv
capture label variable  othpermcropscv   k158cv
capture label variable  othpermcropsfc   k158fc
capture label variable  othpermcropsfu   k158fu
capture label variable  othpermcropsqq   k158qq
capture label variable  othpermcropssa   k158sa
capture label variable  othpermcropstp   k158tp
capture label variable  contractworkforothersbv   k177bv
capture label variable  contractworkforotherscv   k177cv
capture label variable  contractworkforothersfc   k177fc
capture label variable  contractworkforothersfu   k177fu
capture label variable  contractworkforothersqq   k177qq
capture label variable  contractworkforotherssa   k177sa
capture label variable  contractworkforotherstp   k177tp
capture label variable  rapeaa   k331aa
capture label variable  rapebv   k331bv
capture label variable  rapecv   k331cv
capture label variable  rapefc   k331fc
capture label variable  rapefu   k331fu
capture label variable  rapeqq   k331qq
capture label variable  rapesa   k331sa
capture label variable  rapetp   k331tp
capture label variable  sunfloweraa   k332aa
capture label variable  sunflowerbv   k332bv
capture label variable  sunflowercv   k332cv
capture label variable  sunflowerfc   k332fc
capture label variable  sunflowerfu   k332fu
capture label variable  sunflowerqq   k332qq
capture label variable  sunflowersa   k332sa
capture label variable  sunflowertp   k332tp
capture label variable  soyaaa   k333aa
capture label variable  soyabv   k333bv
capture label variable  soyacv   k333cv
capture label variable  soyafc   k333fc
capture label variable  soyafu   k333fu
capture label variable  soyaqq   k333qq
capture label variable  soyasa   k333sa
capture label variable  soyatp   k333tp
capture label variable  otheraa   k334aa
capture label variable  otherbv   k334bv
capture label variable  othercv   k334cv
capture label variable  otherfc   k334fc
capture label variable  otherfu   k334fu
capture label variable  otherqq   k334qq
capture label variable  othersa   k334sa
capture label variable  othertp   k334tp
capture label variable  sugarcaneaa   k346aa
capture label variable  sugarcanebv   k346bv
capture label variable  sugarcanecv   k346cv
capture label variable  sugarcanefc   k346fc
capture label variable  sugarcanefu   k346fu
capture label variable  sugarcaneqq   k346qq
capture label variable  sugarcanesa   k346sa
capture label variable  sugarcanetp   k346tp
capture label variable  flaxnotfibflaxaa   k364aa
capture label variable  flaxnotfibflaxbv   k364bv
capture label variable  flaxnotfibflaxcv   k364cv
capture label variable  flaxnotfibflaxfc   k364fc
capture label variable  flaxnotfibflaxfu   k364fu
capture label variable  flaxnotfibflaxqq   k364qq
capture label variable  flaxnotfibflaxsa   k364sa
capture label variable  flaxnotfibflaxtp   k364tp
capture label variable  forestryaa   kforstaa
capture label variable  forestrybv   kforstbv
capture label variable  forestrycv   kforstcv
capture label variable  forestryfc   kforstfc
capture label variable  forestryfu   kforstfu
capture label variable  forestryqq   kforstqq
capture label variable  forestrysa   kforstsa
capture label variable  forestrytp   kforsttp
capture label variable  totnfoodcrsetasaraa   knfcaa
capture label variable  totnfoodcrsetasarbv   knfcbv
capture label variable  totnfoodcrsetasarcv   knfccv
capture label variable  totnfoodcrsetasarfc   knfcfc
capture label variable  totnfoodcrsetasarfu   knfcfu
capture label variable  totnfoodcrsetasarqq   knfcqq
capture label variable  totnfoodcrsetasarsa   knfcsa
capture label variable  totnfoodcrsetasartp   knfctp
capture label variable  qusugarbeetpurchase   l421a
capture label variable  qusugarbeetsales   l421b
capture label variable  qusugarbeetopeningval   l421c
capture label variable  qusugarbeetdepreciation   l421d
capture label variable  qusugarbeetclosingval   l421e
capture label variable  qusugarbeettaxes   l421f
capture label variable  qusugarbeetrentpaid   l421g
capture label variable  qusugarbeetrentreceived   l421h
capture label variable  qusugarbeetquantity   l421i
capture label variable  compensationoilseedcropsaa   m603aa
capture label variable  compensationoilseedcropscp   m603cp
capture label variable  compensationoilseedcropsry   m603ry
capture label variable  compirroilseedcropsaa   m623aa
capture label variable  compirroilseedcropscp   m623cp
capture label variable  compirroilseedcropsry   m623ry
capture label variable  sanonfoodonsaaa   m650aa
capture label variable  sanonfoodonsacp   m650cp
capture label variable  sanonfoodonsary   m650ry
capture label variable  energycropsaa   m655aa
capture label variable  energycropscp   m655cp
capture label variable  spdetailsaa   m670aa
capture label variable  spspecentitlaa   m674aa
capture label variable  singleareapaa   m680aa
capture label variable  farmsrepresented   sys02
capture label variable  samplefarms   sys03
capture label variable  exchangerate  sys04
