label define ms3 1 `"BEL"', modify
label define ms3 2 `"BGR"', modify
label define ms3 3 `"CYP"', modify
label define ms3 4 `"CZE"', modify
label define ms3 5 `"DAN"', modify
label define ms3 6 `"DEU"', modify
label define ms3 7 `"ESP"', modify
label define ms3 8 `"EST"', modify
label define ms3 9 `"FRA"', modify
label define ms3 10 `"HUN"', modify
label define ms3 11 `"ITA"', modify
label define ms3 12 `"LTU"', modify
label define ms3 13 `"LUX"', modify
label define ms3 14 `"LVA"', modify
label define ms3 15 `"NED"', modify
label define ms3 16 `"OST"', modify
label define ms3 17 `"POL"', modify
label define ms3 18 `"POR"', modify
label define ms3 19 `"SUO"', modify
label define ms3 20 `"ROU"', modify
label define ms3 21 `"SVE"', modify
label define ms3 22 `"SVK"', modify
label define ms3 23 `"SVN"', modify
label define ms3 24 `"UKI"', modify
label define ms3 25 `"IRE"', modify
