capture rename   farmcode                          farmcode   
capture rename   SOIL_CODE                         ffsolcod   
capture rename   BOOK_NUMBER                       ffbookno   
capture rename   LAND_OWNED_HA                     fsizldow   
capture rename   LAND_RENTED_IN_HA                 fsizldrt   
capture rename   LAND_RENTED_IN_EU                 forntcon   
capture rename   LAND_LET_OUT_HA                   fsizldlt   
capture rename   LAND_LET_OUT_EU                   fincldlt   
capture rename   LAND_FARMED_HA                    fsizunad   
capture rename   ANNUITIES_EU                      foannuit   
capture rename   ROUGH_GRAZING_HA                  fsizrgac   
capture rename   WOODLAND_HA                       fsizfort   
capture rename   PASTURE_EQUIV_ROUGH_HA            fsizrgeq   
capture rename   HAY_1ST_GROUND_CUT_HA             fsiz1hay   
capture rename   HAY_2ND_GROUND_CUT_HA             fsiz2hay   
capture rename   HAY_3RD_GROUND_CUT_HA             fsiz3hay   
capture rename   SIL_1ST_GROUND_CUT_HA             fsizslg1   
capture rename   SIL_2ND_GROUND_CUT_HA             fsizslg2   
capture rename   SIL_3RD_GROUND_CUT_HA             fsizslg3   
capture rename   FERT_USED_VALUE_EU                fdferfil   
capture rename   WHOLE_MILK_SOLD_TO_CREAMERY_LT    doslcmgl   
capture rename   WHOLE_MILK_SOLD_TO_CREAMERY_EU    doslcmvl   
capture rename   CREAMERY_BONUSES_EU               domlkbon   
capture rename   DAIRY_CALVES_SALES_NO             docfslno   
capture rename   DAIRY_CALVES_SALES_EU             docfslvl   
capture rename   DAIRY_CALVES_TRANSFER_NO          docftfno   
capture rename   DAIRY_CALVES_TRANSFER_EU          docftfvl   
capture rename   DAIRY_SUPPORT_VALUE_EU            dosubsvl   
capture rename   CATTLE_CALVES_PURCHASES_NO        coprcfno   
capture rename   CATTLE_CALVES_PURCHASES_EU        coprcfvl   
capture rename   CATTLE_WEANLINGS_PURCHASES_NO     coprwnno   
capture rename   CATTLE_WEANLINGS_PURCHASES_EU     coprwnvl   
capture rename   CATTLE_BREED_REPLACE_PURCH_NO     coprbhno   
capture rename   CATTLE_BREED_REPLACE_PURCH_EU     coprbhvl   
capture rename   CATTLE_OTHER_PURCHASES_NO         coprocno   
capture rename   CATTLE_OTHER_PURCHASES_EU         coprocvl   
capture rename   CATTLE_TOTAL_PURCHASES_NO         copurcno   
capture rename   CATTLE_TOTAL_PURCHASES_EU         copurval   
capture rename   CATTLE_RCPT_BULL_SERVICES_EU      coserrec   
capture rename   CATTLE_CALVES_SALES_NO            coslcfno   
capture rename   CATTLE_CALVES_SALES_EU            coslcfvl   
capture rename   CATTLE_WEANLINGS_SALES_NO         coslwnno   
capture rename   CATTLE_WEANLINGS_SALES_EU         coslwnvl   
capture rename   CATTLE_OTHER_SALES_NO             coslocno   
capture rename   CATTLE_OTHER_SALES_EU             coslocvl   
capture rename   CATTLE_TOTAL_SALES_NO             cosltotn   
capture rename   CATTLE_TOTAL_SALES_EU             cosltotv   
capture rename   BIRTHS_JAN_NO                     dpcfbjan   
capture rename   BIRTHS_FEB_NO                     dpcfbfeb   
capture rename   BIRTHS_MAR_NO                     dpcfbmar   
capture rename   BIRTHS_APR_NO                     dpcfbapr   
capture rename   BIRTHS_MAY_NO                     dpcfbmay   
capture rename   BIRTHS_JUN_NO                     dpcfbjun   
capture rename   BIRTHS_JUL_NO                     dpcfbjul   
capture rename   BIRTHS_AUG_NO                     dpcfbaug   
capture rename   BIRTHS_SEP_NO                     dpcfbsep   
capture rename   BIRTHS_OCT_NO                     dpcfboct   
capture rename   BIRTHS_NOV_NO                     dpcfbnov   
capture rename   BIRTHS_DEC_NO                     dpcfbdec   
capture rename   BIRTHS_TOTAL_NO                   dpcfbtot   
capture rename   DEATHS_LT6MTHS_NO                 cpdthclf   
capture rename   DEATHS_GT6MTHS_NO                 cpdthc6m   
capture rename   DEATHS_CATTLE_HERD_COWS_NO        cpdthcow   
capture rename   DEATHS_CALVES_AT_BIRTH_NO         cpdthbir   
capture rename   WOOL_OP_INV_VALUE_EU              spopinvw   
capture rename   WOOL_CLOS_INV_VALUE_EU            spclinvw   
capture rename   EWES_RAMS_PURCHASES_NO            soprerno   
capture rename   EWES_RAMS_PURCHASES_EU            soprervl   
capture rename   BREEDING_HOGGETS_PURCHASES_NO     soprbhno   
capture rename   BREEDING_HOGGETS_PURCHASES_EU     soprbhvl   
capture rename   STORE_LAMBS_PURCHASES_NO          soprslno   
capture rename   STORE_LAMBS_PURCHASES_EU          soprslvl   
capture rename   FAT_LAMBS_SALES_NO                soslflno   
capture rename   FAT_LAMBS_SALES_EU                soslflvl   
capture rename   STORE_LAMBS_SALES_NO              soslslno   
capture rename   STORE_LAMBS_SALES_EU              soslslvl   
capture rename   FAT_HOGGETS_SALES_NO              soslhgno   
capture rename   FAT_HOGGETS_SALES_EU              soslhgvl   
capture rename   BREEDING_HOGGETS_SALES_NO         soslbhno   
capture rename   BREEDING_HOGGETS_SALES_EU         soslbhvl   
capture rename   CULL_EWES_RAMS_SALES_NO           soslerno   
capture rename   CULL_EWES_RAMS_SALES_EU           soslervl   
capture rename   BREEDING_EWES_SALES_NO            soslbeno   
capture rename   BREEDING_EWES_SALES_EU            soslbevl   
capture rename   SHEEP_USED_IN_HOUSE_NO            soconhno   
capture rename   SHEEP_USED_IN_HOUSE_EU            soconhvl   
capture rename   WOOL_SALES_VALUE_EU               soslwlvl   
capture rename   EWE_BREED_CODE                    spbreede   
capture rename   RAM_BREED_CODE                    spbreedr   
capture rename   HILL_LOWLAND_CODE                 sphillow   
capture rename   SHEEP_SHORN_NO                    spshorn    
capture rename   EWE_LAMBS_TAKING_RAM_NO           spnoewlr   
capture rename   BARREN_EWES_NO                    spnobnew   
capture rename   EWES_MATED_HORMONE_TREATED_NO     spewmhor   
capture rename   FAT_LAMBS_SOLD_PRE_JUNE1_NO       spnofls1   
capture rename   EWES_IN_LAMB_PURCHASES_NO         spprilen   
capture rename   EWES_IN_LAMB_SALES_NO             spslinen   
capture rename   EWES_AT_FOOT_LAMBS_PURCHASES_NO   spprelfn   
capture rename   EWES_AT_FOOT_LAMBS_SALES_NO       spslelfn   
capture rename   LAMBS_AT_FOOT_PURCHASES_NO        spprlafn   
capture rename   LAMBS_AT_FOOT_SALES_NO            spsllafn   
capture rename   BIRTHS_LIVE_NO                    ppbirbon   
capture rename   DEATHS_EWES_NO                    spewedth   
capture rename   DEATHS_LAMBS_PRE_WEANING_NO       splamdth   
capture rename   FARROWINGS_NO                     ppfarwno   
capture rename   BIRTHS_LIVE_NO                    ppbirbon   
capture rename   DEATHS_PRE_WEANING_NO             ppdthbon   
capture rename   DEATHS_FATTENERS_NO               ppdthfpg   
capture rename   DEATHS_OTHERS_NO                  ppdthoth   
capture rename   PIGS_USED_IN_HOUSE_NO             soconhno   
capture rename   PIGS_USED_IN_HOUSE_EU             soconhvl   
capture rename   BREEDING_STOCK_PURCHASES_NO       ppclass    
capture rename   BONHAMS_STORES_PURCHASES_NO       poprwnno   
capture rename   BONHAMS_STORES_PURCHASES_EU       poprwnvl   
capture rename   BREEDING_STOCK_SALES_NO           poslbpno   
capture rename   BONHAMS_STORES_SALES_NO           poslwnno   
capture rename   BONHAMS_STORES_SALES_EU           poslwnvl   
capture rename   PORKERS_BACON_SALES_NO            poslfpno   
capture rename   PORKERS_BACON_SALES_EU            poslfpvl   
capture rename   ORDINARY_FOWL_PURCHASES_EU        eoprplyv   
capture rename   OTHER_FOWL_PURCHASES_EU           eoprothf   
capture rename   ORDINARY_FOWL_SALES_EU            fslothlv   
capture rename   OTHER_FOWL_SALES_EU               eoslothf   
capture rename   POULTRY_SUBSIDIES_VALUE_EU        eosubsid   
capture rename   HORSES_EQUINES_PURCHASES_EU       hopurchh   
capture rename   HORSES_EQUINES_SUBS_RCPT_EU       fsubhors   
capture rename   CONC_OP_INV_50KGBAGS_NO           icopinvq   
capture rename   CONC_OP_INV_50KGBAGS_EU           icopinvv   
capture rename   CONC_PURCHASED_50KGBAGS_NO        icpurqty   
capture rename   CONC_PURCHASED_50KGBAGS_EU        icpurval   
capture rename   CONC_ALLOCATED_50KGBAGS_NO        icallqty   
capture rename   CONC_ALLOCATED_50KGBAGS_EU        icallval   
capture rename   CONC_CLOS_INV_50KGBAGS_NO         icclinvq   
capture rename   CONC_CLOS_INV_50KGBAGS_EU         icclinvv   
capture rename   CONC_ALLOC_DAIRY_HERD_50KG_NO     icalldyq   
capture rename   CONC_ALLOC_DAIRY_HERD_50KG_EU     icalldyv   
capture rename   CONC_ALLOC_CATTLE_50KGBAGS_NO     icallcqt   
capture rename   CONC_ALLOC_CATTLE_50KGBAGS_EU     icallcvl   
capture rename   CONC_ALLOC_SHEEP_50KGBAGS_NO      icallsqt   
capture rename   CONC_ALLOC_SHEEP_50KGBAGS_EU      icallsvl   
capture rename   CONC_ALLOC_HORSES_50KGBAGS_NO     icallhqt   
capture rename   CONC_ALLOC_HORSES_50KGBAGS_EU     icallhvl   
capture rename   CONC_ALLOC_PIGS_50KGBAGS_NO       icallpgq   
capture rename   CONC_ALLOC_PIGS_50KGBAGS_EU       icallpgv   
capture rename   CONC_ALLOC_POULTRY_50KGBAGS_NO    icallpyq   
capture rename   CONC_ALLOC_POULTRY_50KGBAGS_EU    icallpyv   
capture rename   CONC_ALLOC_OTHER_50KGBAGS_NO      icallolq   
capture rename   CONC_ALLOC_OTHER_50KGBAGS_EU      icallolv   
capture rename   CONC_ALLOC_WASTE_50KGBAGS_NO      icwasteq   
capture rename   CONC_ALLOC_WASTE_50KGBAGS_EU      icwastev   
capture rename   CONC_MILK_SUB_FED_CALVES_50KG_NO  icmksubq   
capture rename   CONC_MILK_SUB_FED_CALVES_50KG_EU  icmksubv   
capture rename   VET_MED_AI_OP_INV_EU              ivmopinv   
capture rename   VET_MED_AI_PURCHASED_EU           ivmpurch   
capture rename   VET_MED_AI_CLOS_INV_EU            ivmclinv   
capture rename   VET_MED_ALLOC_PIGS_EU             ivmallpg   
capture rename   AI_SERVICE_FEES_ALLOC_PIGS_EU     iaisfpig   
capture rename   VET_MED_ETC_ALLOC_POULTRY_EU      ivmallpy   
capture rename   VET_MED_ALLOC_DAIRY_HERD_EU       ivmalldy   
capture rename   AI_FEES_ALLOC_DAIRY_HERD_EU       iaisfdy   // slight name difference    
capture rename   AI_SR_FEES_ALOC_DAIRY_HRD_EU      iaisfdy   // slight name difference
capture rename   VET_MED_ALLOC_CATTLE_EU           ivmallc    
capture rename   AI_SERVICE_FEES_ALLOC_CATTLE_EU   iaisfcat   
capture rename   VET_MED_ALLOC_SHEEP_EU            ivmallsp   
capture rename   AI_SERVICE_FEES_ALLOC_SHEEP_EU    iaisfshp   
capture rename   VET_MED_ALLOC_HORSES_EU           ivmallh    
capture rename   AI_SERVICE_FEES_ALLOC_HORSES_EU   iaisfhrs   
capture rename   VET_MED_AI_FEES_TOTAL_ALLOC_EU    ivmalltl   
capture rename   TRANSPORT_ALLOC_PIGS_EU           itepigs    
capture rename   MISCELLANEOUS_ALLOC_PIGS_EU       imiscpig   
capture rename   TRANSPORT_ALLOC_POULTRY_EU        itepolty   
capture rename   MISCELLANEOUS_ALLOC_POULTRY_EU    imiscpty   
capture rename   TRANSPORT_ALLOC_DAIRY_HERD_EU     itedairy   
capture rename   MISC_ALLOC_DAIRY_HERD_EU          imiscdry   
capture rename   TRANSPORT_ALLOC_CATTLE_EU         itecattl   
capture rename   MISCELLANEOUS_ALLOC_CATTLE_EU     imiscctl   
capture rename   TRANSPORT_ALLOC_SHEEP_EU          itesheep   
capture rename   MISCELLANEOUS_ALLOC_SHEEP_EU      imiscshp   
capture rename   TRANSPORT_ALLOC_HORSES_EU         itehorse   
capture rename   MISCELLANEOUS_ALLOC_HORSES_EU     imischrs   
capture rename   TRANS_MISC_EXP_TOTAL_ALLOC_EU     itemcall   
capture rename   MISC_GRANTS_SUBSIDIES_EU          fgrtsubs   
capture rename   TOTAL_MISC_RECEIPTS_EU            fmiscrec   
capture rename   ELECTRICITY_FARM_SHARE_EU         foelecfs   
capture rename   TELEPHONE_FARM_SHARE_EU           fophonfs   
capture rename   FARM_SHARE_PERCENTAGE             fcarshar   
capture rename   MACHINERY_FUEL_LUBS_OP_INV_EU     foopinfl   
capture rename   MACHINERY_FUEL_LUBS_PURCHASES_EU  fopurflv   
capture rename   MACHINERY_FUEL_LUBS_CLOS_INV_EU   foclinfl   
capture rename   MACHINERY_MINOR_REPAIRS_EU        fomacrpr   
capture rename   MACHINERY_TAX_EU                  fomactax   
capture rename   MACHINERY_INSURANCE_EU            fomacins   
capture rename   BUILDINGS_REPAIRS_UPKEEP_EU       fobldmnt   
capture rename   BUILDINGS_FIRE_INSURANCE_EU       fobldins   
capture rename   LAND_GENERAL_UPKEEP_EU            foupkpld   
capture rename   CAS_LAB_ALLOC_DAIRY_HERD_EU       flabccdy   
capture rename   CAS_LAB_ALLOC_CATTLE_EU           flabccct   
capture rename   CAS_LAB_ALLOC_SHEEP_EU            flabccsh   
capture rename   CAS_LAB_ALLOC_PIGS_EU             flabccpg   
capture rename   CAS_LAB_ALLOC_POULTRY_EU          flabccpy   
capture rename   CAS_LAB_ALLOC_OTHER_EU            flabccol   
capture rename   CAS_LAB_NON_ALLOCABLE_EU          flabccna   
capture rename   CAS_LAB_TOTAL_ALLOC_EU            flabcctl   
capture rename   E_LOAN_OPENING_BALANCE_EU         fbelopbl   
capture rename   N_LOAN_AMOUNT_BORROWED_EU         fbnlamtb   
capture rename   PMA_TOTAL_PURCHASE_THIS_YEAR_EU   faprpmac   
capture rename   PMA_TOTAL_MAJOR_REPAIRS_EU        famrpmac   
capture rename   PMA_GRANTS_EU                     fagrpmac   
capture rename   PMA_TOTAL_SALES_TRADEINS_EU       faslpmac   
capture rename   OMA_TOTAL_PURCHASE_THIS_YEAR_EU   fapromac   
capture rename   OMA_TOTAL_MAJOR_REPAIRS_EU        famromac   
capture rename   OMA_GRANTS_EU                     fagromac   
capture rename   OMA_TOTAL_SALES_TRADEINS_EU       faslomac   
capture rename   BLD_NEW_BUILDINGS_EU              factnbld   
capture rename   BLD_TOTAL_MAJOR_REPAIRS_EU        famrblds   
capture rename   BLD_GRANTS_EU                     fagrblds   
capture rename   LAN_TOTAL_MAJOR_IMPROVEMENTS_EU   faldimpr   
capture rename   LAN_GRANTS_EU                     fagrlimp   
capture rename   PERM_CROPS_ORIG_GRANTS_EU         fagrpcrp   
capture rename   PERM_CROPS_MAJOR_IMPROVEMENTS_EU  fapcpimp   
capture rename   LAND_VALUE_EST_BEG_OF_YEAR_EU     favlfrby   
capture rename   LAND_VALUE_PURCHASES_HA           faprldac   
capture rename   LAND_VALUE_PURCHASES_EU           faprldvl   
capture rename   LAND_VALUE_SALES_HA               faslldac   
capture rename   LAND_VALUE_SALES_EU               faslldvl   
capture rename   TEAGASC_ADVISORY_FEES_EU          foadvfee   
*capture rename   :                                 ffszsyst   
capture rename   D_LABOUR_UNITS_TOTAL              flabtotl   
capture rename   D_STANDARD_MAN_DAYS               flabsmds   
capture rename   LAND_VALUE_EST_END_OF_YEAR_EU     fainvfrm   
capture rename   D_INVESTMENT_IN_MACHINERY         fainvmch   
capture rename   D_INVESTMENT_IN_BUILDINGS         fainvbld   
capture rename   D_INV_IN_LIMPROVEMENTS            fainvlim   
capture rename   D_VALUE_OF_FAMILY_LABOUR_EU       fvalflab   
capture rename   D_TOTAL_CASUAL_LABOUR_EU          fdcaslab   
capture rename   D_HIRED_LABOUR_CASUAL_EXCL_EU     fohirlab   
capture rename   D_INTRST_PAY_INCL_HP_INTEREST_EU  fointpay   // slight name difference
capture rename   D_INT_PAY_INCL_HP_INT_EU          fointpay   // slight name difference  
capture rename   D_MACHINE_OPERATING_EXPENSES_EU   fomacopt   // slight name difference   
capture rename   D_MACHINERY_OPERATING_EXP_EU      fomacopt   // slight name difference   
capture rename   BUILDINGS_REPAIRS_UPKEEP_EU       fobldmnt   
capture rename   LAND_GENERAL_UPKEEP_EU            foupkpld   
capture rename   D_INSURANCE_EU                    foinsure   
capture rename   D_FUEL_LUBS_EU                    fofuellu   
capture rename   ELECTRICITY_FARM_SHARE_EU         foelecfs   
capture rename   TELEPHONE_FARM_SHARE_EU           fophonfs   
*capture rename  :                                 fortfmer   
*capture rename  :                                 fortnfer   
capture rename   D_MISC_OVERHEAD_COSTS_EU          fomiscel   
capture rename   D_DAIRY_GROSS_OUTPUT_EU           fdairygo   
capture rename   D_GROSS_OUTPUT_CATTLE_EU          fcatlego   
capture rename   D_GROSS_OUTPUT_SHEEP_AND_WOOL_EU  fsheepgo   
capture rename   D_TOTAL_CROPS_GROSS_OUTPUT_EU     fcropsgo   
capture rename   D_CROP_LIVESTOCK_GROSS_OUTPUT_EU  fcplivgo   
capture rename   D_TOTAL_CASUAL_LABOUR_EU          fdcaslab   
capture rename   D_EXPENDITURE_ON_LIME_EU          foexlime   
capture rename   D_MACHINERY_RATES_EU              forates    
capture rename   D_HERD_SIZE_AVG_NO                dpavnohd   
capture rename   D_TOTAL_MILK_PRODUCTION_LT        dotomkgl   
capture rename   D_TOTAL_MILK_PRODUCTION_EU        dotomkvl   
capture rename   D_CONCENTRATES_FED_DAIRY_EU       ddconval   
capture rename   D_DAIRY_PASTURE_EU                ddpastur   
capture rename   D_FARM_GROSS_OUTPUT               farmgo     
capture rename   D_DAIRY_WINTER_FORAGE_EU          ddwinfor   
capture rename   D_BUTTER_FAT_MILK_KGS             dabotfat   
capture rename   D_PROTEIN_MILK_KGS                daproten   
capture rename   D_FORAGE_AREA_HA                  daforare   
capture rename   D_ALL_BULLS_AVG_NO                dpavnobl   
capture rename   D_FEED_AREA_EQUIV_HA              dafedare   
capture rename   D_CLOS_INV_DAIRY_HERD_EU          dpclinvd   
