capture rename   farmcode   farmcode                          
capture rename   ffsolcod   SOIL_CODE                         
capture rename   ffbookno   BOOK_NUMBER                       
capture rename   fsizldow   LAND_OWNED_HA                     
capture rename   fsizldrt   LAND_RENTED_IN_HA                 
capture rename   forntcon   LAND_RENTED_IN_EU                 
capture rename   fsizldlt   LAND_LET_OUT_HA                   
capture rename   fincldlt   LAND_LET_OUT_EU                   
capture rename   fsizunad   LAND_FARMED_HA                    
capture rename   foannuit   ANNUITIES_EU                      
capture rename   fsizrgac   ROUGH_GRAZING_HA                  
capture rename   fsizfort   WOODLAND_HA                       
capture rename   fsizrgeq   PASTURE_EQUIV_ROUGH_HA            
capture rename   fsiz1hay   HAY_1ST_GROUND_CUT_HA             
capture rename   fsiz2hay   HAY_2ND_GROUND_CUT_HA             
capture rename   fsiz3hay   HAY_3RD_GROUND_CUT_HA             
capture rename   fsizslg1   SIL_1ST_GROUND_CUT_HA             
capture rename   fsizslg2   SIL_2ND_GROUND_CUT_HA             
capture rename   fsizslg3   SIL_3RD_GROUND_CUT_HA             
capture rename   fdferfil   FERT_USED_VALUE_EU                
capture rename   doslcmgl   WHOLE_MILK_SOLD_TO_CREAMERY_LT    
capture rename   doslcmvl   WHOLE_MILK_SOLD_TO_CREAMERY_EU    
capture rename   domlkbon   CREAMERY_BONUSES_EU               
capture rename   docfslno   DAIRY_CALVES_SALES_NO             
capture rename   docfslvl   DAIRY_CALVES_SALES_EU             
capture rename   docftfno   DAIRY_CALVES_TRANSFER_NO          
capture rename   docftfvl   DAIRY_CALVES_TRANSFER_EU          
capture rename   dosubsvl   DAIRY_SUPPORT_VALUE_EU            
capture rename   coprcfno   CATTLE_CALVES_PURCHASES_NO        
capture rename   coprcfvl   CATTLE_CALVES_PURCHASES_EU        
capture rename   coprwnno   CATTLE_WEANLINGS_PURCHASES_NO     
capture rename   coprwnvl   CATTLE_WEANLINGS_PURCHASES_EU     
capture rename   coprbhno   CATTLE_BREED_REPLACE_PURCH_NO     
capture rename   coprbhvl   CATTLE_BREED_REPLACE_PURCH_EU     
capture rename   coprocno   CATTLE_OTHER_PURCHASES_NO         
capture rename   coprocvl   CATTLE_OTHER_PURCHASES_EU         
capture rename   copurcno   CATTLE_TOTAL_PURCHASES_NO         
capture rename   copurval   CATTLE_TOTAL_PURCHASES_EU         
capture rename   coserrec   CATTLE_RCPT_BULL_SERVICES_EU      
capture rename   coslcfno   CATTLE_CALVES_SALES_NO            
capture rename   coslcfvl   CATTLE_CALVES_SALES_EU            
capture rename   coslwnno   CATTLE_WEANLINGS_SALES_NO         
capture rename   coslwnvl   CATTLE_WEANLINGS_SALES_EU         
capture rename   coslocno   CATTLE_OTHER_SALES_NO             
capture rename   coslocvl   CATTLE_OTHER_SALES_EU             
capture rename   cosltotn   CATTLE_TOTAL_SALES_NO             
capture rename   cosltotv   CATTLE_TOTAL_SALES_EU             
capture rename   dpcfbjan   BIRTHS_JAN_NO                     
capture rename   dpcfbfeb   BIRTHS_FEB_NO                     
capture rename   dpcfbmar   BIRTHS_MAR_NO                     
capture rename   dpcfbapr   BIRTHS_APR_NO                     
capture rename   dpcfbmay   BIRTHS_MAY_NO                     
capture rename   dpcfbjun   BIRTHS_JUN_NO                     
capture rename   dpcfbjul   BIRTHS_JUL_NO                     
capture rename   dpcfbaug   BIRTHS_AUG_NO                     
capture rename   dpcfbsep   BIRTHS_SEP_NO                     
capture rename   dpcfboct   BIRTHS_OCT_NO                     
capture rename   dpcfbnov   BIRTHS_NOV_NO                     
capture rename   dpcfbdec   BIRTHS_DEC_NO                     
capture rename   dpcfbtot   BIRTHS_TOTAL_NO                   
capture rename   cpdthclf   DEATHS_LT6MTHS_NO                 
capture rename   cpdthc6m   DEATHS_GT6MTHS_NO                 
capture rename   cpdthcow   DEATHS_CATTLE_HERD_COWS_NO        
capture rename   cpdthbir   DEATHS_CALVES_AT_BIRTH_NO         
capture rename   spopinvw   WOOL_OP_INV_VALUE_EU              
capture rename   spclinvw   WOOL_CLOS_INV_VALUE_EU            
capture rename   soprerno   EWES_RAMS_PURCHASES_NO            
capture rename   soprervl   EWES_RAMS_PURCHASES_EU            
capture rename   soprbhno   BREEDING_HOGGETS_PURCHASES_NO     
capture rename   soprbhvl   BREEDING_HOGGETS_PURCHASES_EU     
capture rename   soprslno   STORE_LAMBS_PURCHASES_NO          
capture rename   soprslvl   STORE_LAMBS_PURCHASES_EU          
capture rename   soslflno   FAT_LAMBS_SALES_NO                
capture rename   soslflvl   FAT_LAMBS_SALES_EU                
capture rename   soslslno   STORE_LAMBS_SALES_NO              
capture rename   soslslvl   STORE_LAMBS_SALES_EU              
capture rename   soslhgno   FAT_HOGGETS_SALES_NO              
capture rename   soslhgvl   FAT_HOGGETS_SALES_EU              
capture rename   soslbhno   BREEDING_HOGGETS_SALES_NO         
capture rename   soslbhvl   BREEDING_HOGGETS_SALES_EU         
capture rename   soslerno   CULL_EWES_RAMS_SALES_NO           
capture rename   soslervl   CULL_EWES_RAMS_SALES_EU           
capture rename   soslbeno   BREEDING_EWES_SALES_NO            
capture rename   soslbevl   BREEDING_EWES_SALES_EU            
capture rename   soconhno   SHEEP_USED_IN_HOUSE_NO            
capture rename   soconhvl   SHEEP_USED_IN_HOUSE_EU            
capture rename   soslwlvl   WOOL_SALES_VALUE_EU               
capture rename   spbreede   EWE_BREED_CODE                    
capture rename   spbreedr   RAM_BREED_CODE                    
capture rename   sphillow   HILL_LOWLAND_CODE                 
capture rename   spshorn    SHEEP_SHORN_NO                    
capture rename   spnoewlr   EWE_LAMBS_TAKING_RAM_NO           
capture rename   spnobnew   BARREN_EWES_NO                    
capture rename   spewmhor   EWES_MATED_HORMONE_TREATED_NO     
capture rename   spnofls1   FAT_LAMBS_SOLD_PRE_JUNE1_NO       
capture rename   spprilen   EWES_IN_LAMB_PURCHASES_NO         
capture rename   spslinen   EWES_IN_LAMB_SALES_NO             
capture rename   spprelfn   EWES_AT_FOOT_LAMBS_PURCHASES_NO   
capture rename   spslelfn   EWES_AT_FOOT_LAMBS_SALES_NO       
capture rename   spprlafn   LAMBS_AT_FOOT_PURCHASES_NO        
capture rename   spsllafn   LAMBS_AT_FOOT_SALES_NO            
capture rename   ppbirbon   BIRTHS_LIVE_NO                    
capture rename   spewedth   DEATHS_EWES_NO                    
capture rename   splamdth   DEATHS_LAMBS_PRE_WEANING_NO       
capture rename   ppfarwno   FARROWINGS_NO                     
capture rename   ppbirbon   BIRTHS_LIVE_NO                    
capture rename   ppdthbon   DEATHS_PRE_WEANING_NO             
capture rename   ppdthfpg   DEATHS_FATTENERS_NO               
capture rename   ppdthoth   DEATHS_OTHERS_NO                  
capture rename   soconhno   PIGS_USED_IN_HOUSE_NO             
capture rename   soconhvl   PIGS_USED_IN_HOUSE_EU             
capture rename   ppclass    BREEDING_STOCK_PURCHASES_NO       
capture rename   poprwnno   BONHAMS_STORES_PURCHASES_NO       
capture rename   poprwnvl   BONHAMS_STORES_PURCHASES_EU       
capture rename   poslbpno   BREEDING_STOCK_SALES_NO           
capture rename   poslwnno   BONHAMS_STORES_SALES_NO           
capture rename   poslwnvl   BONHAMS_STORES_SALES_EU           
capture rename   poslfpno   PORKERS_BACON_SALES_NO            
capture rename   poslfpvl   PORKERS_BACON_SALES_EU            
capture rename   eoprplyv   ORDINARY_FOWL_PURCHASES_EU        
capture rename   eoprothf   OTHER_FOWL_PURCHASES_EU           
capture rename   fslothlv   ORDINARY_FOWL_SALES_EU            
capture rename   eoslothf   OTHER_FOWL_SALES_EU               
capture rename   eosubsid   POULTRY_SUBSIDIES_VALUE_EU        
capture rename   hopurchh   HORSES_EQUINES_PURCHASES_EU       
capture rename   fsubhors   HORSES_EQUINES_SUBS_RCPT_EU       
capture rename   icopinvq   CONC_OP_INV_50KGBAGS_NO           
capture rename   icopinvv   CONC_OP_INV_50KGBAGS_EU           
capture rename   icpurqty   CONC_PURCHASED_50KGBAGS_NO        
capture rename   icpurval   CONC_PURCHASED_50KGBAGS_EU        
capture rename   icallqty   CONC_ALLOCATED_50KGBAGS_NO        
capture rename   icallval   CONC_ALLOCATED_50KGBAGS_EU        
capture rename   icclinvq   CONC_CLOS_INV_50KGBAGS_NO         
capture rename   icclinvv   CONC_CLOS_INV_50KGBAGS_EU         
capture rename   icalldyq   CONC_ALLOC_DAIRY_HERD_50KG_NO     
capture rename   icalldyv   CONC_ALLOC_DAIRY_HERD_50KG_EU     
capture rename   icallcqt   CONC_ALLOC_CATTLE_50KGBAGS_NO     
capture rename   icallcvl   CONC_ALLOC_CATTLE_50KGBAGS_EU     
capture rename   icallsqt   CONC_ALLOC_SHEEP_50KGBAGS_NO      
capture rename   icallsvl   CONC_ALLOC_SHEEP_50KGBAGS_EU      
capture rename   icallhqt   CONC_ALLOC_HORSES_50KGBAGS_NO     
capture rename   icallhvl   CONC_ALLOC_HORSES_50KGBAGS_EU     
capture rename   icallpgq   CONC_ALLOC_PIGS_50KGBAGS_NO       
capture rename   icallpgv   CONC_ALLOC_PIGS_50KGBAGS_EU       
capture rename   icallpyq   CONC_ALLOC_POULTRY_50KGBAGS_NO    
capture rename   icallpyv   CONC_ALLOC_POULTRY_50KGBAGS_EU    
capture rename   icallolq   CONC_ALLOC_OTHER_50KGBAGS_NO      
capture rename   icallolv   CONC_ALLOC_OTHER_50KGBAGS_EU      
capture rename   icwasteq   CONC_ALLOC_WASTE_50KGBAGS_NO      
capture rename   icwastev   CONC_ALLOC_WASTE_50KGBAGS_EU      
capture rename   icmksubq   CONC_MILK_SUB_FED_CALVES_50KG_NO  
capture rename   icmksubv   CONC_MILK_SUB_FED_CALVES_50KG_EU  
capture rename   ivmopinv   VET_MED_AI_OP_INV_EU              
capture rename   ivmpurch   VET_MED_AI_PURCHASED_EU           
capture rename   ivmclinv   VET_MED_AI_CLOS_INV_EU            
capture rename   ivmallpg   VET_MED_ALLOC_PIGS_EU             
capture rename   iaisfpig   AI_SERVICE_FEES_ALLOC_PIGS_EU     
capture rename   ivmallpy   VET_MED_ETC_ALLOC_POULTRY_EU      
capture rename   ivmalldy   VET_MED_ALLOC_DAIRY_HERD_EU       
capture rename   iaisfdy    AI_FEES_ALLOC_DAIRY_HERD_EU       
capture rename   ivmallc    VET_MED_ALLOC_CATTLE_EU           
capture rename   iaisfcat   AI_SERVICE_FEES_ALLOC_CATTLE_EU   
capture rename   ivmallsp   VET_MED_ALLOC_SHEEP_EU            
capture rename   iaisfshp   AI_SERVICE_FEES_ALLOC_SHEEP_EU    
capture rename   ivmallh    VET_MED_ALLOC_HORSES_EU           
capture rename   iaisfhrs   AI_SERVICE_FEES_ALLOC_HORSES_EU   
capture rename   ivmalltl   VET_MED_AI_FEES_TOTAL_ALLOC_EU    
capture rename   itepigs    TRANSPORT_ALLOC_PIGS_EU           
capture rename   imiscpig   MISCELLANEOUS_ALLOC_PIGS_EU       
capture rename   itepolty   TRANSPORT_ALLOC_POULTRY_EU        
capture rename   imiscpty   MISCELLANEOUS_ALLOC_POULTRY_EU    
capture rename   itedairy   TRANSPORT_ALLOC_DAIRY_HERD_EU     
capture rename   imiscdry   MISC_ALLOC_DAIRY_HERD_EU          
capture rename   itecattl   TRANSPORT_ALLOC_CATTLE_EU         
capture rename   imiscctl   MISCELLANEOUS_ALLOC_CATTLE_EU     
capture rename   itesheep   TRANSPORT_ALLOC_SHEEP_EU          
capture rename   imiscshp   MISCELLANEOUS_ALLOC_SHEEP_EU      
capture rename   itehorse   TRANSPORT_ALLOC_HORSES_EU         
capture rename   imischrs   MISCELLANEOUS_ALLOC_HORSES_EU     
capture rename   itemcall   TRANS_MISC_EXP_TOTAL_ALLOC_EU     
capture rename   fgrtsubs   MISC_GRANTS_SUBSIDIES_EU          
capture rename   fmiscrec   TOTAL_MISC_RECEIPTS_EU            
capture rename   foelecfs   ELECTRICITY_FARM_SHARE_EU         
capture rename   fophonfs   TELEPHONE_FARM_SHARE_EU           
capture rename   fcarshar   FARM_SHARE_PERCENTAGE             
capture rename   foopinfl   MACHINERY_FUEL_LUBS_OP_INV_EU     
capture rename   fopurflv   MACHINERY_FUEL_LUBS_PURCHASES_EU  
capture rename   foclinfl   MACHINERY_FUEL_LUBS_CLOS_INV_EU   
capture rename   fomacrpr   MACHINERY_MINOR_REPAIRS_EU        
capture rename   fomactax   MACHINERY_TAX_EU                  
capture rename   fomacins   MACHINERY_INSURANCE_EU            
capture rename   fobldmnt   BUILDINGS_REPAIRS_UPKEEP_EU       
capture rename   fobldins   BUILDINGS_FIRE_INSURANCE_EU       
capture rename   foupkpld   LAND_GENERAL_UPKEEP_EU            
capture rename   flabccdy   CAS_LAB_ALLOC_DAIRY_HERD_EU       
capture rename   flabccct   CAS_LAB_ALLOC_CATTLE_EU           
capture rename   flabccsh   CAS_LAB_ALLOC_SHEEP_EU            
capture rename   flabccpg   CAS_LAB_ALLOC_PIGS_EU             
capture rename   flabccpy   CAS_LAB_ALLOC_POULTRY_EU          
capture rename   flabccol   CAS_LAB_ALLOC_OTHER_EU            
capture rename   flabccna   CAS_LAB_NON_ALLOCABLE_EU          
capture rename   flabcctl   CAS_LAB_TOTAL_ALLOC_EU            
capture rename   fbelopbl   E_LOAN_OPENING_BALANCE_EU         
capture rename   fbnlamtb   N_LOAN_AMOUNT_BORROWED_EU         
capture rename   faprpmac   PMA_TOTAL_PURCHASE_THIS_YEAR_EU   
capture rename   famrpmac   PMA_TOTAL_MAJOR_REPAIRS_EU        
capture rename   fagrpmac   PMA_GRANTS_EU                     
capture rename   faslpmac   PMA_TOTAL_SALES_TRADEINS_EU       
capture rename   fapromac   OMA_TOTAL_PURCHASE_THIS_YEAR_EU   
capture rename   famromac   OMA_TOTAL_MAJOR_REPAIRS_EU        
capture rename   fagromac   OMA_GRANTS_EU                     
capture rename   faslomac   OMA_TOTAL_SALES_TRADEINS_EU       
capture rename   factnbld   BLD_NEW_BUILDINGS_EU              
capture rename   famrblds   BLD_TOTAL_MAJOR_REPAIRS_EU        
capture rename   fagrblds   BLD_GRANTS_EU                     
capture rename   faldimpr   LAN_TOTAL_MAJOR_IMPROVEMENTS_EU   
capture rename   fagrlimp   LAN_GRANTS_EU                     
capture rename   fagrpcrp   PERM_CROPS_ORIG_GRANTS_EU         
capture rename   fapcpimp   PERM_CROPS_MAJOR_IMPROVEMENTS_EU  
capture rename   favlfrby   LAND_VALUE_EST_BEG_OF_YEAR_EU     
capture rename   faprldac   LAND_VALUE_PURCHASES_HA           
capture rename   faprldvl   LAND_VALUE_PURCHASES_EU           
capture rename   faslldac   LAND_VALUE_SALES_HA               
capture rename   faslldvl   LAND_VALUE_SALES_EU               
capture rename   foadvfee   TEAGASC_ADVISORY_FEES_EU          
capture rename   ffszsyst   :                                 
capture rename   flabtotl   D_LABOUR_UNITS_TOTAL              
capture rename   flabsmds   D_STANDARD_MAN_DAYS               
capture rename   fainvfrm   LAND_VALUE_EST_END_OF_YEAR_EU     
capture rename   fainvmch   D_INVESTMENT_IN_MACHINERY         
capture rename   fainvbld   D_INVESTMENT_IN_BUILDINGS         
capture rename   fainvlim   D_INV_IN_LIMPROVEMENTS            
capture rename   fvalflab   D_VALUE_OF_FAMILY_LABOUR_EU       
capture rename   fdcaslab   D_TOTAL_CASUAL_LABOUR_EU          
capture rename   fohirlab   D_HIRED_LABOUR_CASUAL_EXCL_EU     
capture rename   fointpay   D_INT_PAY_INCL_HP_INT_EU          
capture rename   fomacopt   D_MACHINERY_OPERATING_EXP_EU      
capture rename   fobldmnt   BUILDINGS_REPAIRS_UPKEEP_EU       
capture rename   foupkpld   LAND_GENERAL_UPKEEP_EU            
capture rename   foinsure   D_INSURANCE_EU                    
capture rename   fofuellu   D_FUEL_LUBS_EU                    
capture rename   foelecfs   ELECTRICITY_FARM_SHARE_EU         
capture rename   fophonfs   TELEPHONE_FARM_SHARE_EU           
*capture rename  fortfmer   :                                 
*capture rename  fortnfer   :                                 
capture rename   fomiscel   D_MISC_OVERHEAD_COSTS_EU          
capture rename   fdairygo   D_DAIRY_GROSS_OUTPUT_EU           
capture rename   fcatlego   D_GROSS_OUTPUT_CATTLE_EU          
capture rename   fsheepgo   D_GROSS_OUTPUT_SHEEP_AND_WOOL_EU  
capture rename   fcropsgo   D_TOTAL_CROPS_GROSS_OUTPUT_EU     
capture rename   fcplivgo   D_CROP_LIVESTOCK_GROSS_OUTPUT_EU  
capture rename   fdcaslab   D_TOTAL_CASUAL_LABOUR_EU          
capture rename   foexlime   D_EXPENDITURE_ON_LIME_EU          
capture rename   forates    D_MACHINERY_RATES_EU              
capture rename   dpavnohd   D_HERD_SIZE_AVG_NO                
capture rename   dotomkgl   D_TOTAL_MILK_PRODUCTION_LT        
capture rename   dotomkvl   D_TOTAL_MILK_PRODUCTION_EU        
capture rename   ddconval   D_CONCENTRATES_FED_DAIRY_EU       
capture rename   ddpastur   D_DAIRY_PASTURE_EU                
capture rename   farmgo     D_FARM_GROSS_OUTPUT               
capture rename   ddwinfor   D_DAIRY_WINTER_FORAGE_EU          
capture rename   dabotfat   D_BUTTER_FAT_MILK_KGS             
capture rename   daproten   D_PROTEIN_MILK_KGS                
capture rename   daforare   D_FORAGE_AREA_HA                  
capture rename   dpavnobl   D_ALL_BULLS_AVG_NO                
capture rename   dafedare   D_FEED_AREA_EQUIV_HA              
capture rename   dpclinvd   D_CLOS_INV_DAIRY_HERD_EU          
