capture rename   ClosingInventoryNumberEwes     EWES_CLOS_INV_NO                  
capture rename   ClosingInventoryHeadEwes       EWES_CLOS_INV_EU                  
capture rename   ClosingInventoryNumberLambsb   LAMBS_PRE_WEANING_CLOS_INV_NO     
capture rename   ClosingInventoryLambsbeforeW   LAMBS_PRE_WEANING_CLOS_INV_EU     
capture rename   ClosingInventoryNumberOtherl   LAMBS_LT1YR_CLOS_INV_NO           
capture rename   ClosingInventoryHeadOtherl     LAMBS_LT1YR_CLOS_INV_EU           
capture rename   ClosingInventoryNumberSheep1   SHEEP_1_2YRS_CLOS_INV_NO          
capture rename   ClosingInventoryHeadSheep1     SHEEP_1_2YRS_CLOS_INV_EU          
capture rename   ClosingInventoryNumberSheepo   SHEEP_GT2YRS_CLOS_INV_NO          
capture rename   ClosingInventoryHeadSheepo     SHEEP_GT2YRS_CLOS_INV_EU          
capture rename   ClosingInventoryNumberRams     RAMS_CLOS_INV_NO                  
capture rename   ClosingInventoryHeadRams       RAMS_CLOS_INV_EU                  
capture rename   ClosingInventoryNumberTotal    TOTAL_CLOS_INV_NO                 
capture rename   ClosingInventoryQuantityWool   WOOL_CLOS_INV_QTY_KGS             
capture rename   ClosingInventoryWoolValue      WOOL_CLOS_INV_VALUE_EU            
