capture rename   FarmBuildingsTOTALOriginalGr   BLD_ORIGINAL_GROSS_COST_EU        
capture rename   D                              BLD_ORIGINAL_GRANT_EU             
capture rename   FarmBuildingsbeginningofyear   BLD_BegYearNetVal                 
capture rename   FarmBuildingsNewThisYear       BLD_NEW_BUILDINGS_EU              
capture rename   FarmBuildingsTOTALMajorRepai   BLD_TOTAL_MAJOR_REPAIRS_EU        
capture rename   FarmBuildingsGrantrecforinv    BLD_GRANTS_EU                     
capture rename   FarmBuildingsDepreciation      BLD_REPLACE_DEP_VALUE             
capture rename   FarmBuildingsendValue          BLD_REPLACE_NET_VALUE             
capture rename   K                              BLD_GrantRecPrevYear              
