capture rename   OpeningInventoryQuantity50kg   FERT_OP_INV_QTY_BAGS              
capture rename   OpeningInventoryTotalValue     FERT_OP_INV_VALUE_EU              
capture rename   PurchasedduringYearQuantity5   FERT_PURCH_QTY_BAGS               
capture rename   PurchasedduringYearTotalValue  FERT_PURCH_VALUE_EU               
capture rename   UsedduringYearQuantity50kg     FERT_USED_QTY_BAGS                
capture rename   UsedduringYearTotalValue       FERT_USED_VALUE_EU                
capture rename   WasteQuantity50kgBags          FERT_WASTE_QTY_BAGS               
capture rename   WasteTotalValue                FERT_WASTE_VALUE_EU               
capture rename   ClosingInventoryQuantity50kg   FERT_CLOSING_INV_QTY_BAGS         
capture rename   ClosingInventoryTotalValue     FERT_CLOSING_INV_VALUE_EU         
capture rename   LimeOpeningInventoryTonnes     LIME_OP_INV_QTY_TONNES            
capture rename   LimeOpeningInventory           LIME_OP_INV_VALUE_EU              
capture rename   LimePurchasedduringYearTonne   LIME_PURCH_QTY_TONNES             
capture rename   LimePurchasedduringYear        LIME_PURCH_VALUE_EU               
capture rename   LimeClosingInventoryTonnes     LIME_CLOSING_INV_QTY_TONNES       
capture rename   LimeClosingInventory           LIME_CLOSING_INV_VALUE_EU         
capture rename   SlurryandorFYMpurchases        SLURRY_FYM_PURCH_VALUE_EU         
capture rename   OtherCropExpensesOpeningInve   OTHER_CROP_EXP_OP_INV_VALUE_EU    
capture rename   OtherCropExpensesClosingInve   OTHER_CROP_EXP_CLOS_INV_VALUE_EU  
