capture rename   OpeningInventoryNumberDairyC   DAIRY_COWS1_OP_INV_NO             
capture rename   OpeningInventoryValueDairyCo   DAIRY_COWS1_OP_INV_EU             
capture rename   E                              DAIRY_COWS2_OP_INV_NO             
capture rename   F                              DAIRY_COWS2_OP_INV_EU             
capture rename   OpeningInventoryNumberDairyS   DAIRY_STOCK_BULLS_OP_INV_NO       
capture rename   OpeningInventoryValueDairySt   DAIRY_STOCK_BULLS_OP_INV_EU       
capture rename   OpeningInventoryNumberCalves   DAIRY_CALVES_LT1WEEK_OP_INV_NO    
capture rename   OpeningInventoryValueCalvesl   DAIRY_CALVES_LT1WEEK_OP_INV_EU    
capture rename   OpeningInventoryNumberOther    DAIRY_OTHER_OP_INV_NO             
capture rename   OpeningInventoryValueOther     DAIRY_OTHER_OP_INV_EU             
capture rename   OpeningInventoryTotalNumber    DAIRY_TOTAL_OP_INV_NO             
