capture rename   DairycowsinmilkJanuary         LIQUID_LITRES_SOLD_JAN_LT         
capture rename   DairycowsinmilkFebruary        LIQUID_LITRES_SOLD_FEB_LT         
capture rename   DairycowsinmilkMarch           LIQUID_LITRES_SOLD_MAR_LT         
capture rename   DairycowsinmilkApril           LIQUID_LITRES_SOLD_APR_LT         
capture rename   DairycowsinmilkMay             LIQUID_LITRES_SOLD_MAY_LT         
capture rename   DairycowsinmilkJune            LIQUID_LITRES_SOLD_JUN_LT         
capture rename   DairycowsinmilkJuly            LIQUID_LITRES_SOLD_JUL_LT         
capture rename   DairycowsinmilkAugust          LIQUID_LITRES_SOLD_AUG_LT         
capture rename   DairycowsinmilkSeptember       LIQUID_LITRES_SOLD_SEP_LT         
capture rename   DairycowsinmilkOctober         LIQUID_LITRES_SOLD_OCT_LT         
capture rename   DairycowsinmilkNovember        LIQUID_LITRES_SOLD_NOV_LT         
capture rename   DairycowsinmilkDecember        LIQUID_LITRES_SOLD_DEC_LT         
capture rename   DairycowsinmilkTotal           LIQUID_LITRES_SOLD_LT_SUBCARD     
