capture rename   DairyheifierscalvingdownJanu   junk_29_435                       
capture rename   DairyheifierscalvingdownFebr   junk_29_436                       
capture rename   DairyheifierscalvingdownMarc   junk_29_437                       
capture rename   DairyheifierscalvingdownApri   junk_29_438                       
capture rename   DairyheifierscalvingdownMay    junk_29_439                       
capture rename   DairyheifierscalvingdownJune   junk_29_440                       
capture rename   DairyheifierscalvingdownJuly   junk_29_441                       
capture rename   DairyheifierscalvingdownAugu   junk_29_442                       
capture rename   DairyheifierscalvingdownSept   junk_29_443                       
capture rename   DairyheifierscalvingdownOcto   junk_29_444                       
capture rename   DairyheifierscalvingdownNove   junk_29_445                       
capture rename   DairyheifierscalvingdownDece   junk_29_446                       
capture rename   DairyheifierscalvingdownTota   junk_29_447                       
