label define ms2 1 `"BE"', modify
label define ms2 2 `"BG"', modify
label define ms2 3 `"CY"', modify
label define ms2 4 `"CZ"', modify
label define ms2 5 `"DK"', modify
label define ms2 6 `"DE"', modify
label define ms2 7 `"ES"', modify
label define ms2 8 `"EE"', modify
label define ms2 9 `"FR"', modify
label define ms2 10 `"HU"', modify
label define ms2 11 `"IT"', modify
label define ms2 12 `"LT"', modify
label define ms2 13 `"LU"', modify
label define ms2 14 `"LV"', modify
label define ms2 15 `"NL"', modify
label define ms2 16 `"AT"', modify
label define ms2 17 `"PL"', modify
label define ms2 18 `"PT"', modify
label define ms2 19 `"FI"', modify
label define ms2 20 `"RO"', modify
label define ms2 21 `"SE"', modify
label define ms2 22 `"SK"', modify
label define ms2 23 `"SI"', modify
label define ms2 24 `"UK"', modify
label define ms2 25 `"IE"', modify
