rename	advisefee	foadvfee
rename	sys	ffszsyst
rename	fc	farmcode
rename	sclass	ffsolcod
rename	size3	fsizunad
rename	labunits	flabtotl
rename	mandays	flabsmds
rename	farmvaluee	fainvfrm
rename	machinee	fainvmch
rename	buildingse	fainvbld
rename	landimpe	fainvlim
rename	labfame	fvalflab
rename	labcase	fdcaslab
rename	conacree	forntcon
rename	hiredlabe	fohirlab
rename	intereste	fointpay
rename	opexmachinery	fomacopt
rename	opexbuildings	fobldmnt
rename	upkeepe	foupkpld
rename	limee	foexlime
rename	annuitiese	foannuit
rename	ratee	forates
rename	insurancee	foinsure
rename	fuellubse	fofuellu
rename	esbe	foelecfs
rename	phonee	fophonfs
rename	rentretirefame	fortfmer
rename	rentretirenonfame	fortnfer
rename	miscoverheade	fomiscel
rename	dairyinggrossoutput	fdairygo
rename	cattlegrossoutput	fcatlego
rename	sheepgrossoutput	fsheepgo
rename	cropsgrossoutput	fcropsgo
rename	cropandlivegrossoutput	fcplivgo
rename	othergrantsandsubs	fgrntsub
rename	aidairy	iaisfdy
rename	aicattle	iaisfcat
rename	aisheep	iaisfshp
rename	maritalstat	ogmarsth
rename	hohsex	ogsexhld
rename	age	ogagehld
rename	offjobtype	oojobhld
rename	offjobinc	ooinchld
rename	childunder5	oanolt5y
rename	childunder15	oano515y
rename	childunder19	oano1619
rename	loan	fbelclbl
		
rename	sub1	fsubhors
rename	sub2	fsubtbco
rename	sub3	fsubforh
rename	sub4	fsubesag
rename	sub5	fsubyfig
rename	sub6	fsubreps
rename	sub7	fsubscno
rename	sub8	fsubscen
rename	sub9	fsubsccp
rename	sub10	fsubscpp
rename	sub11	fsubsctp
rename	sub12	fsub10no
rename	sub13	fsub10en
rename	sub14	fsub10cp
rename	sub15	fsub10pp
rename	sub16	fsub10tp
rename	sub17	fsub22no
rename	sub18	fsub22en
rename	sub19	fsub22cp
rename	sub20	fsub22pp
rename	sub21	fsub22tp
rename	sub22	fsubspno
rename	sub23	fsubspen
rename	sub24	fsubspcp
rename	sub25	fsubsppp
rename	sub26	fsubsptp
rename	sub27	fsubexno
rename	sub28	fsubexen
rename	sub29	fsubexcp
rename	sub30	fsubexpp
rename	sub31	fsubextp
rename	sub32	fsubchno
rename	sub33	fsubchen
rename	sub34	fsubchcp
rename	sub35	fsubchpp
rename	sub36	fsubchtp
rename	sub37	fsubepno
rename	sub38	fsubepen
rename	sub39	fsubepcp
rename	sub40	fsubeppp
rename	sub41	fsubeptp
rename	sub42	fsubshno
rename	sub43	fsubshen
rename	sub44	fsubshcp
rename	sub45	fsubshpp
rename	sub46	fsubshtp
rename	sub47	fsubgpcm
rename	sub48	fsubtups
rename	sub49	fsubasac
rename	sub50	fsubaspd
rename	sub51	fsubascp
rename	sub52	fsubaspp
rename	sub53	fsubastp
rename	sub54	fsubcaac
rename	sub55	fsubcapd
rename	sub56	fsubcacp
rename	sub57	fsubcapp
rename	sub58	fsubcatp
rename	sub59	fsubrpac
rename	sub60	fsubrppd
rename	sub61	fsubrpcp
rename	sub62	fsubrppp
rename	sub63	fsubrptp
rename	sub64	fsubpbac
rename	sub65	fsubpbpd
rename	sub66	fsubpbcp
rename	sub67	fsubpbpp
rename	sub68	fsubpbtp
rename	sub69	fsubliac
rename	sub70	fsublipd
rename	sub71	fsublicp
rename	sub72	fsublipp
rename	sub73	fsublitp
rename	sub74	fsubmzac
rename	sub75	fsubmzpd
rename	sub76	fsubmzcp
rename	sub77	fsubmzpp
rename	sub78	fsubmztp
rename	sub79	fsubvstp
		
rename	DYave	dpavnohd
rename	DYbullave	dpavnobl
rename	DYcloseinv	dpclinvd
rename	DYmilkgal	dotomkgl
rename	DYmilke	dotomkvl
rename	DYsubs	dosubsvl
rename	DYconcentrates	ddconval
rename	DYpasture	ddpastur
rename	DYwinfor	ddwinfor
rename	DYmisccosts	ddmiscdc
rename	DYownquota	dqownqty
rename	DYleasedquota	dqrentgl
rename	DYletquota	dqletgal
rename	DYquota	dqcuryer
rename	DYfat	dabotfat
rename	DYprotein	daproten
rename	DYforagearea	daforare
rename	DYfeedarea	dafedare


