capture rename   ClosingInventorySowsinPigNu    SOWS_IN_PIG_CLOS_INV_NO           
capture rename   ClosingInventorySowsinPigVa    SOWS_IN_PIG_CLOS_INV_PERHEAD_EU   
capture rename   ClosingInventoryGiltsinPigN    GILTS_IN_PIG_CLOS_INV_NO          
capture rename   ClosingInventoryGiltsinPigV    GILTS_IN_PIG_CLOS_INV_PERHEAD_EU  
capture rename   ClosingInventorySowsSuckling   SOWS_SUCKLING_CLOS_INV_NO         
capture rename   H                              SOWS_SUCKLING_CLOS_INV_EU         
capture rename   ClosingInventoryBonhamsNumber  BONHAMS_CLOS_INV_NO               
capture rename   ClosingInventoryBonhamsValue   BONHAMS_CLOS_INV_PERHEAD_EU       
capture rename   ClosingInventoryWeanersNumber  WEANERS_CLOS_INV_NO               
capture rename   ClosingInventoryWeanersValue   WEANERS_CLOS_INV_PERHEAD_EU       
capture rename   ClosingInventoryFattenersNumb  FATTENERS1_CLOS_INV_NO            
capture rename   ClosingInventoryFattenersWeig  FATTENERS1_CLOS_INV_PERHEAD_KGS   
capture rename   ClosingInventoryFattenersValu  FATTENERS1_CLOS_INV_PERHEAD_EU    
capture rename   P                              FATTENERS2_CLOS_INV_NO            
capture rename   Q                              FATTENERS2_CLOS_INV_PERHEAD_KGS   
capture rename   R                              FATTENERS2_CLOS_INV_PERHEAD_EU    
capture rename   S                              FATTENERS3_CLOS_INV_NO            
capture rename   T                              FATTENERS3_CLOS_INV_PERHEAD_KGS   
capture rename   U                              FATTENERS3_CLOS_INV_PERHEAD_EU    
capture rename   ClosingInventoryFatteningSows  FATTENING_SOWS_CLOS_INV_NO        
capture rename   W                              FATTENING_SOWS_CLOS_INV_EU        
capture rename   ClosingInventoryStockBoarsNu   STOCK_BOARS_CLOS_INV_NO           
capture rename   ClosingInventoryStockBoars     STOCK_BOARS_CLOS_INV_PERHEAD_EU   
capture rename   ClosingInventoryTotalNumber    TOTAL_CLOS_INV_NO                 
