capture rename   closingInventoryNumberDairyC   DAIRY_COWS1_CLOS_INV_NO           
capture rename   closingInventoryValueDairyCo   DAIRY_COWS1_CLOS_INV_EU           
capture rename   E                              DAIRY_COWS2_CLOS_INV_NO           
capture rename   F                              DAIRY_COWS2_CLOS_INV_EU           
capture rename   closingInventoryNumberDairyS   DAIRY_STOCK_BULLS_CLOS_INV_NO     
capture rename   closingInventoryValueDairySt   DAIRY_STOCK_BULLS_CLOS_INV_EU     
capture rename   closingInventoryNumberCalves   DAIRY_CALVES_LT1WEEK_CLOS_INV_NO  
capture rename   closingInventoryValueCalvesl   DAIRY_CALVES_LT1WEEK_CLOS_INV_EU  
capture rename   closingInventoryNumberOther    DAIRY_OTHER_CLOS_INV_NO           
capture rename   closingInventoryValueOther     DAIRY_OTHER_CLOS_INV_EU           
capture rename   closingInventoryTotalNumber    DAIRY_TOTAL_CLOS_INV_NO           
