capture rename   OpeningInventoryNumberEwes     EWES_OP_INV_NO                    
capture rename   OpeningInventoryHeadEwes       EWES_OP_INV_EU                    
capture rename   OpeningInventoryNumberLambsb   LAMBS_PRE_WEANING_OP_INV_NO       
capture rename   OpeningInventoryLambsbeforeW   LAMBS_PRE_WEANING_OP_INV_EU       
capture rename   OpeningInventoryNumberOtherl   LAMBS_LT1YR_OP_INV_NO             
capture rename   OpeningInventoryHeadOtherl     LAMBS_LT1YR_OP_INV_EU             
capture rename   OpeningInventoryNumberSheep1   SHEEP_1_2YRS_OP_INV_NO            
capture rename   OpeningInventoryHeadSheep1     SHEEP_1_2YRS_OP_INV_EU            
capture rename   OpeningInventoryNumberSheepo   SHEEP_GT2YRS_OP_INV_NO            
capture rename   OpeningInventoryHeadSheepo     SHEEP_GT2YRS_OP_INV_EU            
capture rename   OpeningInventoryNumberRams     RAMS_OP_INV_NO                    
capture rename   OpeningInventoryHeadRams       RAMS_OP_INV_EU                    
capture rename   OpeningInventoryNumberTotal    TOTAL_OP_INV_NO                   
capture rename   OpeningInventoryQuantityWool   WOOL_OP_INV_QTY_KGS               
capture rename   OpeningInventoryWoolValue      WOOL_OP_INV_VALUE_EU              
