capture rename   LandOwnedAcres                 LAND_OWNED_HA                     
capture rename   LandRentedInAcres              LAND_RENTED_IN_HA                 
capture rename   LandRentedIn                   LAND_RENTED_IN_EU                 
capture rename   LandLetOutAcresAcres           LAND_LET_OUT_HA                   
capture rename   LandLetOut                     LAND_LET_OUT_EU                   
capture rename   LandFarmedAcres                LAND_FARMED_HA                    
capture rename   ratevaluationoflandowned       RATEABLE_VALUATION_EU             
capture rename   buildingvaluation              BUILDING_VALUATION_EU             
capture rename   totalvaluation                 TOTAL_VALUATION_EU                
capture rename   ratesforyear                   RATES_FOR_YEAR_EU                 
capture rename   Annuities                      ANNUITIES_EU                      
