capture rename   OTHERMachineryTOTALOriginalG   OMA_TOTAL_ORIGINAL_GROSS_COST_EU  
capture rename   D                              OMA_TOTAL_ORIGINAL_GRANT_EU       
capture rename   OTHERMachinerybeginningofyea   OMA_BegYearNetVal                 
capture rename   OTHERMachineryTOTALPurchaseT   OMA_TOTAL_PURCHASE_THIS_YEAR_EU   
capture rename   OTHERMachineryTOTALMajorRepa   OMA_TOTAL_MAJOR_REPAIRS_EU        
capture rename   OTHERMachineryGrantrecincur    OMA_GRANTS_EU                     
capture rename   OTHERMachineryTOTALSalesTr     OMA_TOTAL_SALES_TRADEINS_EU       
capture rename   OTHERMachineryTOTALValue       OMA_TOTALValue                    
capture rename   OTHERMachineryDepreciation     OMA_REPLACE_DEP_VALUE             
capture rename   OTHERMachineryENDofyearnet     OMA_REPLACE_NET_VALUE             
