capture rename   Paidcasuallabourallocatedto    CAS_LAB_ALLOC_DAIRY_HERD_EU       
capture rename   D                              CAS_LAB_ALLOC_CATTLE_EU           
capture rename   E                              CAS_LAB_ALLOC_SHEEP_EU            
capture rename   F                              CAS_LAB_ALLOC_PIGS_EU             
capture rename   G                              CAS_LAB_ALLOC_POULTRY_EU          
capture rename   H                              CAS_LAB_ALLOC_OTHER_EU            
capture rename   PaidcasuallabourNonAllocable   CAS_LAB_NON_ALLOCABLE_EU          
capture rename   J                              CROP1_CODE                        
capture rename   K                              ALLOCATED_TO_CROP1_EU             
capture rename   L                              CROP2_CODE                        
capture rename   M                              ALLOCATED_TO_CROP2_EU             
capture rename   N                              CROP3_CODE                        
capture rename   O                              ALLOCATED_TO_CROP3_EU             
capture rename   P                              CROP4_CODE                        
capture rename   Q                              ALLOCATED_TO_CROP4_EU             
capture rename   R                              CROP5_CODE                        
capture rename   S                              ALLOCATED_TO_CROP5_EU             
capture rename   T                              CROP6_CODE                        
capture rename   U                              ALLOCATED_TO_CROP6_EU             
capture rename   PaidcasuallabourTotalAllocat   CAS_LAB_TOTAL_ALLOC_EU            
