
matrix MISSVARS = (0, 0)

capture confirm variable foadvfee
capture confirm variable ffszsyst
capture confirm variable farmcode
capture confirm variable ffsolcod
capture confirm variable fsizunad
capture confirm variable flabtotl
capture confirm variable flabsmds
capture confirm variable fainvfrm
capture confirm variable fainvmch
capture confirm variable fainvbld
capture confirm variable fainvlim
capture confirm variable fvalflab
capture confirm variable fdcaslab
capture confirm variable forntcon
capture confirm variable fohirlab
capture confirm variable fointpay
capture confirm variable fomacopt
capture confirm variable fobldmnt
capture confirm variable foupkpld
capture confirm variable foexlime
capture confirm variable foannuit
capture confirm variable forates
capture confirm variable foinsure
capture confirm variable fofuellu
capture confirm variable foelecfs
capture confirm variable fophonfs
capture confirm variable fortfmer
capture confirm variable fortnfer
capture confirm variable fomiscel
capture confirm variable fdairygo
capture confirm variable fcatlego
capture confirm variable fsheepgo
capture confirm variable fcropsgo
capture confirm variable fcplivgo
capture confirm variable fgrntsub
capture confirm variable iaisfdy
capture confirm variable iaisfcat
capture confirm variable iaisfshp
capture confirm variable ogmarsth
capture confirm variable ogsexhld
capture confirm variable ogagehld
capture confirm variable oojobhld
capture confirm variable ooinchld
capture confirm variable oanolt5y
capture confirm variable oano515y
capture confirm variable oano1619
capture confirm variable fbelclbl
capture confirm variable fsubhors
capture confirm variable fsubtbco
capture confirm variable fsubforh
capture confirm variable fsubesag
capture confirm variable fsubyfig
capture confirm variable fsubreps
capture confirm variable fsubscno
capture confirm variable fsubscen
capture confirm variable fsubsccp
capture confirm variable fsubscpp
capture confirm variable fsubsctp
capture confirm variable fsub10no
capture confirm variable fsub10en
capture confirm variable fsub10cp
capture confirm variable fsub10pp
capture confirm variable fsub10tp
capture confirm variable fsub22no
capture confirm variable fsub22en
capture confirm variable fsub22cp
capture confirm variable fsub22pp
capture confirm variable fsub22tp
capture confirm variable fsubspno
capture confirm variable fsubspen
capture confirm variable fsubspcp
capture confirm variable fsubsppp
capture confirm variable fsubsptp
capture confirm variable fsubexno
capture confirm variable fsubexen
capture confirm variable fsubexcp
capture confirm variable fsubexpp
capture confirm variable fsubextp
capture confirm variable fsubchno
capture confirm variable fsubchen
capture confirm variable fsubchcp
capture confirm variable fsubchpp
capture confirm variable fsubchtp
capture confirm variable fsubepno
capture confirm variable fsubepen
capture confirm variable fsubepcp
capture confirm variable fsubeppp
capture confirm variable fsubeptp
capture confirm variable fsubshno
capture confirm variable fsubshen
capture confirm variable fsubshcp
capture confirm variable fsubshpp
capture confirm variable fsubshtp
capture confirm variable fsubgpcm
capture confirm variable fsubtups
capture confirm variable fsubasac
capture confirm variable fsubaspd
capture confirm variable fsubascp
capture confirm variable fsubaspp
capture confirm variable fsubastp
capture confirm variable fsubcaac
capture confirm variable fsubcapd
capture confirm variable fsubcacp
capture confirm variable fsubcapp
capture confirm variable fsubcatp
capture confirm variable fsubrpac
capture confirm variable fsubrppd
capture confirm variable fsubrpcp
capture confirm variable fsubrppp
capture confirm variable fsubrptp
capture confirm variable fsubpbac
capture confirm variable fsubpbpd
capture confirm variable fsubpbcp
capture confirm variable fsubpbpp
capture confirm variable fsubpbtp
capture confirm variable fsubliac
capture confirm variable fsublipd
capture confirm variable fsublicp
capture confirm variable fsublipp
capture confirm variable fsublitp
capture confirm variable fsubmzac
capture confirm variable fsubmzpd
capture confirm variable fsubmzcp
capture confirm variable fsubmzpp
capture confirm variable fsubmztp
capture confirm variable fsubvstp
capture confirm variable dpavnohd
capture confirm variable dpavnobl
capture confirm variable dpclinvd
capture confirm variable dotomkgl
capture confirm variable dotomkvl
capture confirm variable dosubsvl
capture confirm variable ddconval
capture confirm variable ddpastur
capture confirm variable ddwinfor
capture confirm variable ddmiscdc
capture confirm variable dqownqty
capture confirm variable dqrentgl
capture confirm variable dqletgal
capture confirm variable dqcuryer
capture confirm variable dabotfat
capture confirm variable daproten
capture confirm variable daforare
capture confirm variable dafedare
