
local vlist "`vlist' cffrmcod"
local vlist "`vlist' year"
local vlist "`vlist' cosubsid"
local vlist "`vlist' cs10mtbf"
local vlist "`vlist' cs22mtbf"
local vlist "`vlist' csextens"
local vlist "`vlist' csheadag"
local vlist "`vlist' csmctopu"
local vlist "`vlist' csslaugh"
local vlist "`vlist' cssuckcw"
local vlist "`vlist' dogpcomp"
local vlist "`vlist' dosubsvl"
local vlist "`vlist' dqcomlrd"
local vlist "`vlist' fainvbld"
local vlist "`vlist' fainvfrm"
local vlist "`vlist' fainvlim"
local vlist "`vlist' fainvmch"
local vlist "`vlist' farmdc"
local vlist "`vlist' farmffi"
local vlist "`vlist' farmgm"
local vlist "`vlist' farmgo"
local vlist "`vlist' farmohct"
local vlist "`vlist' fbelclbl"
local vlist "`vlist' fcatledc"
local vlist "`vlist' fcatlegm"
local vlist "`vlist' fcatlego"
local vlist "`vlist' fcropsdc"
local vlist "`vlist' fcropsgo"
local vlist "`vlist' fdairydc"
local vlist "`vlist' fdairygm"
local vlist "`vlist' fdairygo"
local vlist "`vlist' fdcaslab"
local vlist "`vlist' ffodcpdc"
local vlist "`vlist' ffodcpgm"
local vlist "`vlist' ffodcpgo"
local vlist "`vlist' ffsolcod"
local vlist "`vlist' esusize"
local vlist "`vlist' uaasize"
local vlist "`vlist' farmsys"
local vlist "`vlist' dsampcell"
local vlist "`vlist' duaasize"
local vlist "`vlist' duaapub"
local vlist "`vlist' fgrntsub"
local vlist "`vlist' fhorsedc"
local vlist "`vlist' fhorsegm"
local vlist "`vlist' fhorsego"
local vlist "`vlist' flabsmds"
local vlist "`vlist' flabtotl"
local vlist "`vlist' flivstdc"
local vlist "`vlist' flivstgm"
local vlist "`vlist' flivstgo"
local vlist "`vlist' fmisccdc"
local vlist "`vlist' fmisccgo"
local vlist "`vlist' foadvfee"
local vlist "`vlist' foannuit"
local vlist "`vlist' fobldmnt"
local vlist "`vlist' foelecfs"
local vlist "`vlist' foexlime"
local vlist "`vlist' fofuellu"
local vlist "`vlist' fohirlab"
local vlist "`vlist' v61"
local vlist "`vlist' fointpay"
local vlist "`vlist' fomacopt"
local vlist "`vlist' fomiscel"
local vlist "`vlist' fophonfs"
local vlist "`vlist' forates"
local vlist "`vlist' forntcon"
local vlist "`vlist' fortfmer"
local vlist "`vlist' fortnfer"
local vlist "`vlist' fotherdc"
local vlist "`vlist' fothergm"
local vlist "`vlist' fothergo"
local vlist "`vlist' foupkpld"
local vlist "`vlist' fpigsdc"
local vlist "`vlist' fpigsgm"
local vlist "`vlist' fpigsgo"
local vlist "`vlist' fpoultdc"
local vlist "`vlist' fpoultgm"
local vlist "`vlist' fpoultgo"
local vlist "`vlist' fsheepdc"
local vlist "`vlist' fsheepgm"
local vlist "`vlist' fsheepgo"
local vlist "`vlist' fsizuaa"
local vlist "`vlist' fsizunad"
local vlist "`vlist' fsubastp"
local vlist "`vlist' fsubcatp"
local vlist "`vlist' fsubchen"
local vlist "`vlist' fsubchpp"
local vlist "`vlist' fsubesag"
local vlist "`vlist' fsubhors"
local vlist "`vlist' fsublitp"
local vlist "`vlist' fsubmztp"
local vlist "`vlist' fsubpbtp"
local vlist "`vlist' fsubreps"
local vlist "`vlist' fsubrptp"
local vlist "`vlist' fsubsctp"
local vlist "`vlist' fsubtbco"
local vlist "`vlist' fsubvstp"
local vlist "`vlist' fsubyfig"
local vlist "`vlist' fvalflab"
local vlist "`vlist' iaisfcat"
local vlist "`vlist' iaisfdy"
local vlist "`vlist' iaisfshp"
local vlist "`vlist' oano1619"
local vlist "`vlist' oano2024"
local vlist "`vlist' oano2544"
local vlist "`vlist' oano4564"
local vlist "`vlist' oano515y"
local vlist "`vlist' oanoge65"
local vlist "`vlist' oanohshm"
local vlist "`vlist' oanolt5y"
local vlist "`vlist' ogagehld"
local vlist "`vlist' ogmarsth"
local vlist "`vlist' ogsexhld"
local vlist "`vlist' ooinchld"
local vlist "`vlist' oojobhld"
local vlist "`vlist' oojobsps"
local vlist "`vlist' posubsid"
local vlist "`vlist' cfuser02"
local vlist "`vlist' sosubsid"
local vlist "`vlist' wt"


foreach var of local vlist{
    capture confirm variable `var'
    if _rc!= 0 {
        local novar "`novar' `var'"
    }
    
    else {
        di "Both data have the variable `var'"
    }
}

foreach var of local novar {
        di "79-83 data doesn't have the variable `var'"
}

macro list _novar
