capture rename   LiquidMilkSoldWholesalegals    LqMilkSoldWSALE_LT                   
capture rename   LiquidMilkSoldWholesale        LqMilkSoldWSALE_EU                   
capture rename   LiquidMilkSoldRetailgals       LqMilkSoldRETAIL_LT                  
capture rename   LiquidMilkSoldRetail           LqMilkSoldRETAIL_EU                  
capture rename   LiquidMilkPurchasedforResale   LqMilkPurchRESALE_LT                 
capture rename   H                              LqMilkPurchRESALE_EU                 
capture rename   SkimMilksoldGals               SKIM_MILK_SOLD_LT                    
capture rename   SkimMilksold                   SKIM_MILK_SOLD_EU                    
capture rename   SkimMilkFedtoCalvesGals        SKIM_MILK_FED_CALVES_LT              
capture rename   SkimMilkFedtoCalves            SKIM_MILK_FED_CALVES_EU              
capture rename   SkimMilkFedtoPigsGals          SKIM_MILK_FED_PIGS_LT                
capture rename   SkimMilkFedtoPigs              SKIM_MILK_FED_PIGS_EU                
capture rename   SkimMilkFedtoPoultryGals       SKIM_MILK_FED_POULTRY_LT             
capture rename   SkimMilkFedtoPoultry           SKIM_MILK_FED_POULTRY_EU             
