capture rename   Wholemilksoldtocreamerylitr    WHOLE_MILK_SOLD_TO_CREAMERY_LT       
capture rename   Wholemilksoldtocreamery        WHOLE_MILK_SOLD_TO_CREAMERY_EU       
capture rename   Bonuses                        CREAMERY_BONUSES_EU                  
capture rename   TotalQuantityButterFatkgs      CREAMERY_TOT_BUTTER_FAT_LT           
capture rename   AverageButterFat               AVERAGE_BUTTERFAT_PERCENT            
capture rename   FedToCalves                    CREAMERY_FED_CALVES_LT               
capture rename   FedToPigs                      CREAMERY_FED_PIGS_LT                 
capture rename   FedToPoultry                   CREAMERY_FED_POULTRY_LT              
capture rename   ButterSoldHomemadekgs          CREAMERY_BUTTER_SOLD_LBS             
capture rename   ButterSoldHomemade             CREAMERY_BUTTER_SOLD_EU              
capture rename   CreamSoldPints                 CreamSoldPints                       
capture rename   CreamSold                      CreamSold                            
