capture rename   PoultryOpeningInventoryLayers  LAYERS_OP_INV_NO                     
capture rename   D                              LAYERS_OP_INV_PERUNIT_EU             
capture rename   PoultryOpeningInventoryChicks  CHICKS_PULLETS_OP_INV_NO             
capture rename   F                              CHICKS_PULLETS_OP_INV_EU             
capture rename   PoultryOpeningInventoryTable   TABLE_FOWL_OP_INV_NO                 
capture rename   H                              TABLE_FOWL_OP_INV_PERUNIT_EU         
capture rename   OpeningInventoryTotalNumber    TOTAL_ORDINARY_FOWL_OP_INV_NO        
capture rename   OpeningInventoryTurkeysNumber  TURKEYS_OP_INV_NO                    
capture rename   OpeningInventoryTurkeysValue   TURKEYS_OP_INV_PERUNIT_EU            
capture rename   OpeningInventoryGeeseNumber    GEESE_OP_INV_NO                      
capture rename   OpeningInventoryGeeseValueun   GEESE_OP_INV_PERUNIT_EU              
capture rename   OpeningInventoryDucksNumber    DUCKS_OP_INV_NO                      
capture rename   OpeningInventoryDucksValueu    DUCKS_OP_INV_PERUNIT_EU              
capture rename   OpeningInventoryOthersNumber   OTHERS_OP_INV_NO                     
capture rename   OpeningInventoryOthersValueu   OTHERS_OP_INV_PERUNIT_EU             
capture rename   OpeningInventoryotherfowlTot   TOTAL_OTHER_FOWL_OP_INV_NO           
