capture rename   PurchasedbulkyfeedOpeningInv   OP_INV1_OR_PURCHASED2                
capture rename   PurchasedbulkyfeedCode         BULKYFEED_CODE                       
capture rename   PurchasedbulkyfeedCodst        BULKYFEED_COST_EU                    
capture rename   PurchasedbulkyfeedQuantity     BULKYFEED_QUANTITY                   
capture rename   PurchasedbulkyfeedAllocatedt   ALLOC_DAIRY_HERD_QTY                 
capture rename   H                              ALLOC_CATTLE_QTY                     
capture rename   I                              ALLOC_SHEEP_QTY                      
capture rename   J                              ALLOC_HORSES_QTY                     
capture rename   K                              ALLOC_PIGS_QTY                       
capture rename   L                              ALLOC_POULTRY_QTY                    
capture rename   OtherGrazingLivestock          OTHER_GRAZING_LIVESTOCK              
capture rename   N                              ALLOC_WASTE_QTY                      
capture rename   O                              ALLOC_TOTAL_QTY                      
capture rename   PurchasedbulkyfeedClosingInv   CLOS_INV_QUANTITY                    
