capture rename   HorsesOtherEquinesPurchases    HORSES_EQUINES_PURCHASES_EU          
capture rename   HorsesOtherEquinesSales        HORSES_EQUINES_SALES_EU              
capture rename   HorsesOtherEquinesOtherRec     HORSES_EQUINES_STUD_FEES_RCPT_EU     
capture rename   HorsesOtherEquinesSubsidi      HORSES_EQUINES_SUBS_RCPT_EU          
capture rename   OtherLivestockPurchases        OTHER_LIVESTOCK_PURCHASES_EU         
capture rename   OtherLivestockSales            OTHER_LIVESTOCK_SALES_EU             
capture rename   OtherLivestockAllowancesiuse   OTHER_LVSTCK_ALLOW_INCL_HOUSE_EU     
capture rename   OtherLivestockAllowanceswages  junk_46_731                          
capture rename   OtherLivestockAllowancesother  junk_46_732                          
capture rename   MonthTotalNoHorsesDraug        MTH12_TOTAL_HORSES_DRAUGHT_NO        
capture rename   MonthTotalNoHorsesUnder        MTH12_TOTAL_HORSES_LT2YR_NO          
capture rename   MonthTotalNooverOver2          MTH12_TOTAL_HORSES_GT2YR_NO          
capture rename   MonthTotalNoPonies             MTH12_TOTAL_PONIES_NO                
capture rename   MonthTotalNoMulesJenne         MTH12_TOTAL_MULES_JENNETS_NO         
capture rename   Asses                          MTH12_TOTAL_ASSES_NO                 
capture rename   MonthTotalNoT                  MTH12_TOTAL_HORSES_EQUINES_NO        
