capture rename   HorsesOpeningInventoryBreedin  HORSES_BREEDING_STOCK1_OP_INV_NO     
capture rename   D                              HORSES_BREEDING_STOCK1_OP_INV_EU     
capture rename   E                              HORSES_BREEDING_STOCK2_OP_INV_NO     
capture rename   F                              HORSES_BREED_STOCK2_OP_INV_EU        
capture rename   HorsesOpeningInventoryOtherS   HORSES_OTHER_STOCK1_OP_INV_NO        
capture rename   H                              HORSES_OTHER_STOCK1_OP_INV_EU        
capture rename   HorsesOpeningInventoryNumber   HORSES1_OP_INV_NO                    
capture rename   HorsesOpeningInventoryValue    HORSES1_OP_INV_PERUNIT_EU            
capture rename   K                              HORSES2_OP_INV_NO                    
capture rename   L                              HORSES2_OP_INV_PERUNIT_EU            
capture rename   M                              HORSES3_OP_INV_NO                    
capture rename   N                              HORSES3_OP_INV_PERUNIT_EU            
capture rename   O                              HORSES4_OP_INV_NO                    
capture rename   P                              HORSES4_OP_INV_PERUNIT_EU            
capture rename   HorsesOpeningInventoryTotal    TOTAL_HORSES_OP_INV_NO               
capture rename   OpeningInventoryCode           OP_INV_CODE                          
capture rename   OpeningInventoryNumber         OP_INV_NO                            
capture rename   OpeningInventoryValuehd        OP_INV_PERUNIT_EU                    
capture rename   OpeningInventoryBreedingAnima  BREEDING_ANIMALS_OP_INV_CODE         
capture rename   V                              BREEDING_ANIMALS_OP_INV_NO           
capture rename   W                              BREED_OP_INV_EU                      
capture rename   OpeningInventoryOthersCode     OTHERS_OP_INV_CODE                   
capture rename   OpeningInventoryOthersNumber   OTHERS_OP_INV_NO                     
capture rename   OpeningInventoryOthersValueh   OTHERS_OP_INV_PERUNIT_EU             
