capture rename   AllowancesWholeMilkhouselit    ALLOW_WHOLE_MILK_HOUSE_LT            
capture rename   AllowancesWholeMilkhouse       ALLOW_WHOLE_MILK_HOUSE_EU            
capture rename   AllowancesWholeMilkwageslit    ALLOW_WHOLE_MILK_WAGES_LT            
capture rename   AllowancesWholeMilkwages       ALLOW_WHOLE_MILK_WAGES_EU            
capture rename   AllowancesWholeMilkotherlit    ALLOW_WHOLE_MILK_OTHER_LT            
capture rename   AllowancesWholeMilkother       ALLOW_WHOLE_MILK_OTHER_EU            
capture rename   AllowancesButterhousekgs       ALLOW_BUTTER_HOUSE_KG                
capture rename   AllowancesButterhouse          ALLOW_BUTTER_HOUSE_EU                
capture rename   AllowancesButterwageskgs       ALLOW_BUTTER_WAGES_KG                
capture rename   AllowancesButterwages          ALLOW_BUTTER_WAGES_EU                
capture rename   AllowancesButterotherkgs       ALLOW_BUTTER_OTHER_KG                
capture rename   AllowancesButterother          ALLOW_BUTTER_OTHER_EU                
capture rename   AllowancesCreamhouselit        ALLOW_OTHER_DAIRY_HOUSE_LT           
capture rename   AllowancesCreamhouse           ALLOW_OTHER_DAIRY_HOUSE_EU           
capture rename   AllowancesCreamwageslit        ALLOW_OTHER_DAIRY_WAGES_LT           
capture rename   AllowancesCreamwages           ALLOW_OTHER_DAIRY_WAGES_EU           
