capture rename   HorsesClosingInventoryBreedin  HORSES_BREED_STOCK1_CLOS_INV_NO      
capture rename   D                              HORSES_BREED_STOCK1_CLOS_INV_EU      
capture rename   E                              HORSES_BREED_STOCK2_CLOS_INV_NO      
capture rename   F                              HORSES_BREED_STOCK2_CLOS_INV_EU      
capture rename   HorsesClosingInventoryOtherS   HORSES_OTHER_STOCK1_CLOS_INV_NO      
capture rename   H                              HORSES_OTHER_STOCK1_CLOS_INV_EU      
capture rename   HorsesClosingInventoryNumber   HORSES1_CLOS_INV_NO                  
capture rename   HorsesClosingInventoryValue    HORSES1_CLOS_INV_PERUNIT_EU          
capture rename   K                              HORSES2_CLOS_INV_NO                  
capture rename   L                              HORSES2_CLOS_INV_PERUNIT_EU          
capture rename   M                              HORSES3_CLOS_INV_NO                  
capture rename   N                              HORSES3_CLOS_INV_PERUNIT_EU          
capture rename   O                              HORSES4_CLOS_INV_NO                  
capture rename   P                              HORSES4_CLOS_INV_PERUNIT_EU          
capture rename   HorsesClosingInventoryTotal    TOTAL_HORSES_CLOS_INV_NO             
capture rename   ClosingInventoryNumber         CLOS_INV_NO                          
capture rename   ClosingInventoryValuehd        CLOS_INV_PERUNIT_EU                  
capture rename   ClosingInventoryBreedingAnima  BREED_CLOS_INV_NO                    
capture rename   U                              BREED_CLOS_INV_EU                    
capture rename   ClosingInventoryOthersNumber   OTHERS_CLOS_INV_NO                   
capture rename   ClosingInventoryOthersValueh   OTHERS_CLOS_INV_PERUNIT_EU           
