*capture rename  N                              N                                    
*capture rename  P                              P                                    
*capture rename  K                              K                                    
*capture rename  TotalCost                      TotalCost                            
*capture rename  TotalQuantity50Kgbags          TotalQuantity50Kgbags                
*capture rename  alloccropcode1                 alloccropcode1                       
*capture rename  Quantity1                      Quantity1                            
*capture rename  alloccropcode2                 alloccropcode2                       
*capture rename  Quantity2                      Quantity2                            
*capture rename  alloccropcode3                 alloccropcode3                       
*capture rename  Quantity3                      Quantity3                            
*capture rename  alloccropcode4                 alloccropcode4                       
*capture rename  Quantity4                      Quantity4                            
*capture rename  Totalqtyused                   Totalqtyused                         
*capture rename  Quantityclosinginventory       Quantityclosinginventory             
