capture rename   FarmBuildingsTOTALOriginalGr   FarmBuildingsTOTALOriginalGr         
capture rename   D                              junk_65_956                          
capture rename   FarmBuildingsbeginningofyear   FarmBuildingsbeginningofyear         
capture rename   FarmBuildingsNewThisYear       factnbld                             
capture rename   FarmBuildingsTOTALMajorRepai   famrblds                             
capture rename   FarmBuildingsGrantrecforinv    fagrblds                             
capture rename   FarmBuildingsDepreciation      FarmBuildingsDepreciation            
capture rename   FarmBuildingsendValue          FarmBuildingsendValue                
capture rename   K                              junk_65_963                          
