capture rename   TotalTillageCropsfromCard5     TOTAL_TILLAGE_CROPS_HA               
capture rename   TotalPasture                   TOTAL_PASTURE_HA                     
capture rename   ley                            TOTAL_PASTURE_LEY_HA                 
capture rename   permanentpasture               TOTAL_PASTURE_PERMANENT_HA           
capture rename   RoughGrazing                   ROUGH_GRAZING_HA                     
capture rename   FallowinclSetaside             FALLOW_SETASIDE_HA                   
capture rename   HouseGarden                    HOUSE_GARDEN_HA                      
capture rename   Woodland                       WOODLAND_HA                          
capture rename   AreanotinAgriculture           D_REMAINDER_OF_FARM_HA               
capture rename   OtherAreas                     OTHER_LAND_USE_HA                    
capture rename   AreaunderglassHeated           AREA_UNDER_GLASS_HEATED              
capture rename   AreaunderglassUnheated         AREA_UNDER_GLASS_UNHEATED            
capture rename   Totallandfarmedabove           junk_03_44                           
capture rename   PastureEquivalentofRoughGraz   PASTURE_EQUIV_ROUGH_HA               
