capture rename   code1                          C47_CODE_1                           
capture rename   NoofUnits1                     C47_UNITS_NO_1                       
capture rename   ValUnit1                       C47_VAL_PER_UNIT_1                   
capture rename   code2                          C47_CODE_2                           
capture rename   NoofUnits2                     C47_UNITS_NO_2                       
capture rename   ValUnit2                       C47_VAL_PER_UNIT_2                   
capture rename   code3                          C47_CODE_3                           
capture rename   NoofUnits3                     C47_UNITS_NO_3                       
capture rename   ValUnit3                       C47_VAL_PER_UNIT_3                   
capture rename   code4                          C47_CODE_4                           
capture rename   NoofUnits4                     C47_UNITS_NO_4                       
capture rename   ValUnit4                       C47_VAL_PER_UNIT_4                   
capture rename   code5                          C47_CODE_5                           
capture rename   NoofUnits5                     C47_UNITS_NO_5                       
capture rename   ValUnit5                       C47_VAL_PER_UNIT_5                   
capture rename   ToTalUnits                     C47_TOTAL_UNITS                      
