capture rename   BoardinginDairyCattleNoo       BOARDING_IN_DAIRY_CATTLE1_NO         
capture rename   D                              BOARDING_IN_DAIRY_CATTLE1_DAYS       
capture rename   BoardinginDairyCattle          BOARDING_IN_DAIRY_CATTLE1_EU         
capture rename   BoardinginDairyCattleLU        BOARDING_IN_DAIRY_CATTLE1_LU_EQ      
capture rename   G                              BOARDING_IN_DAIRY_CATTLE2_NO         
capture rename   H                              BOARDING_IN_DAIRY_CATTLE2_DAYS       
capture rename   I                              BOARDING_IN_DAIRY_CATTLE2_EU         
capture rename   J                              BOARDING_IN_DAIRY_CATTLE2_LU_EQ      
capture rename   K                              BOARDING_IN_DAIRY_CATTLE3_NO         
capture rename   L                              BOARDING_IN_DAIRY_CATTLE3_DAYS       
capture rename   M                              BOARDING_IN_DAIRY_CATTLE3_EU         
capture rename   N                              BOARDING_IN_DAIRY_CATTLE3_LU_EQ      
capture rename   BoardinginSheep1NoofAnima      BOARDING_IN_SHEEP1_ANIMALS_NO        
capture rename   BoardinginSheep1NoofDays       BOARDING_IN_SHEEP1_DAYS_NO           
capture rename   BoardinginSheep1               BOARDING_IN_SHEEP1_EU                
capture rename   BoardinginSheep1LUEquival      BOARDING_IN_SHEEP1_LU_EQUIV          
capture rename   BoardinginSheep2NoofAnima      BOARDING_IN_SHEEP2_ANIMALS_NO        
capture rename   BoardinginSheep2NoofDays       BOARDING_IN_SHEEP2_DAYS_NO           
capture rename   BoardinginSheep2               BOARDING_IN_SHEEP2_EU                
capture rename   BoardinginSheep2LUEquival      BOARDING_IN_SHEEP2_LU_EQUIV          
capture rename   BoardinginHorsesNoofAnimal     BOARDING_IN_HORSES_ANIMALS_NO        
capture rename   BoardinginHorsesNoofDays       BOARDING_IN_HORSES_DAYS_NO           
capture rename   BoardinginHorses               BOARDING_IN_HORSES_EU                
capture rename   BoardinginHorsesLUEquivale     BOARDING_IN_HORSES_LU_EQUIV          
