capture rename   CattleHerdSalesCalvesNumber    CATTLE_CALVES_SALES_NO               
capture rename   CattleHerdSalesCalvesValue     CATTLE_CALVES_SALES_EU               
capture rename   CattleHerdSalesWeanlingsNumb   CATTLE_WEANLINGS_SALES_NO            
capture rename   CattleHerdSalesWeanlingsValu   CATTLE_WEANLINGS_SALES_EU            
capture rename   CattleHerdSalesStoresNumb      CATTLE_STORES_SALES_NO               
capture rename   CattleHerdSalesStoresValu      CATTLE_STORES_SALES_EU               
capture rename   CattleHerdSalesFinishedsNum    CATTLE_FINISHED_SALES_NO             
capture rename   CattleHerdSalesFinishedsVal    CATTLE_FINISHED_SALES_EU             
capture rename   CattleHerdSalesBreedHerdCul    CATTLE_BREED_HERD_CULLS_SALES_NO     
capture rename   L                              CATTLE_BREED_HERD_CULLS_SALES_EU     
capture rename   CattleHerdSalesOtherNumber     CATTLE_OTHER_SALES_NO                
capture rename   CattleHerdSalesOtherValue      CATTLE_OTHER_SALES_EU                
capture rename   CattleHerdSalesTotalNumber     CATTLE_TOTAL_SALES_NO                
capture rename   CattleHerdSalesTotalValue      CATTLE_TOTAL_SALES_EU                
