capture rename   PurchasesEwesRamsNumber        EWES_RAMS_PURCHASES_NO               
capture rename   PurchasesEwesRamsTotalvalu     EWES_RAMS_PURCHASES_EU               
capture rename   PurchasesBreedingHoggetsNumbe  BREEDING_HOGGETS_PURCHASES_NO        
capture rename   PurchasesBreedingHoggetsTotal  BREEDING_HOGGETS_PURCHASES_EU        
capture rename   PurchasesStoreLambsNumber      STORE_LAMBS_PURCHASES_NO             
capture rename   PurchasesStoreLambsTotalvalu   STORE_LAMBS_PURCHASES_EU             
capture rename   SalesFatLambsNumber            FAT_LAMBS_SALES_NO                   
capture rename   SalesFatLambsTotalvalue        FAT_LAMBS_SALES_EU                   
capture rename   SalesStoreLambsNumber          STORE_LAMBS_SALES_NO                 
capture rename   SalesStoreLambsTotalvalue      STORE_LAMBS_SALES_EU                 
capture rename   SalesFatHoggetsNumber          FAT_HOGGETS_SALES_NO                 
capture rename   SalesFatHoggetsTotalvalue      FAT_HOGGETS_SALES_EU                 
capture rename   SalesBreedingHoggetsNumber     BREEDING_HOGGETS_SALES_NO            
capture rename   SalesBreedingHoggetsTotalval   BREEDING_HOGGETS_SALES_EU            
capture rename   SalesCullEwesRamsNumber        CULL_EWES_RAMS_SALES_NO              
capture rename   SalesCullEwesRamsTotalval      CULL_EWES_RAMS_SALES_EU              
capture rename   SalesBreedingEwesNumber        BREEDING_EWES_SALES_NO               
capture rename   SalesBreedingEwesTotalvalue    BREEDING_EWES_SALES_EU               
capture rename   SheepUsedInHouseNumber         SHEEP_USED_IN_HOUSE_NO               
capture rename   SheepUsedInHouseTotalvalue     SHEEP_USED_IN_HOUSE_EU               
capture rename   SheepSubsidies                 TOTAL_SUBSIDIES_EU                   
capture rename   WoolSalesKgs                   WOOL_SALES_QTY_KGS                   
capture rename   WoolSales                      WOOL_SALES_VALUE_EU                  
