capture rename   OTHERMachineryTOTALOriginalG   OTHERMachineryTOTALOriginalG         
capture rename   D                              junk_64_946                          
capture rename   OTHERMachinerybeginningofyea   OTHERMachinerybeginningofyea         
capture rename   OTHERMachineryTOTALPurchaseT   fapromac                             
capture rename   OTHERMachineryTOTALMajorRepa   famromac                             
capture rename   OTHERMachineryGrantrecincur    fagromac                             
capture rename   OTHERMachineryTOTALSalesTr     faslomac                             
capture rename   OTHERMachineryTOTALValue       OTHERMachineryTOTALValue             
capture rename   OTHERMachineryDepreciation     OTHERMachineryDepreciation           
capture rename   OTHERMachineryENDofyearnet     OTHERMachineryENDofyearnet           
