capture rename   CommonageDairyCattleNoof       junk_08_108                          
capture rename   D                              junk_08_109                          
capture rename   CommonageDairyCattle           junk_08_110                          
capture rename   CommonageDairyCattleLUEq       junk_08_111                          
capture rename   G                              junk_08_112                          
capture rename   H                              junk_08_113                          
capture rename   I                              junk_08_114                          
capture rename   J                              junk_08_115                          
capture rename   K                              junk_08_116                          
capture rename   L                              junk_08_117                          
capture rename   M                              junk_08_118                          
capture rename   N                              junk_08_119                          
capture rename   CommonageSheep1NoofAnimals     COMMONAGE_SHEEP1_ANIMALS_NO          
capture rename   CommonageSheep1NoofDays        COMMONAGE_SHEEP1_DAYS_NO             
capture rename   CommonageSheep1                COMMONAGE_SHEEP1_EU                  
capture rename   CommonageSheep1LUEquivalen     COMMONAGE_SHEEP1_LU_EQUIV            
capture rename   CommonageSheep2NoofAnimals     COMMONAGE_SHEEP2_ANIMALS_NO          
capture rename   CommonageSheep2NoofDays        COMMONAGE_SHEEP2_DAYS_NO             
capture rename   CommonageSheep2                COMMONAGE_SHEEP2_EU                  
capture rename   CommonageSheep2LUEquivalen     COMMONAGE_SHEEP2_LU_EQUIV            
capture rename   CommonageHorsesNoofAnimals     COMMONAGE_HORSES_ANIMALS_NO          
capture rename   CommonageHorsesNoofDays        COMMONAGE_HORSES_DAYS_NO             
capture rename   CommonageHorses                COMMONAGE_HORSES_EU                  
capture rename   CommonageHorsesLUEquivalent    COMMONAGE_HORSES_LU_EQUIV            
