capture rename   PowerMachineryTOTALOriginalG   PowerMachineryTOTALOriginalG         
capture rename   D                              junk_63_936                          
capture rename   PowerMachinerybeginningofyea   PowerMachinerybeginningofyea         
capture rename   PowerMachineryTOTALPurchaseT   faprpmac                             
capture rename   PowerMachineryTOTALMajorRepa   famrpmac                             
capture rename   PowerMachineryGrantrecincur    fagrpmac                             
capture rename   PowerMachineryTOTALSalesTr     faslpmac                             
capture rename   PowerMachineryTOTALValue       PowerMachineryTOTALValue             
capture rename   PowerMachineryDepreciation     PowerMachineryDepreciation           
capture rename   PowerMachineryENDofyearnet     PowerMachineryENDofyearnet           
