*capture rename  exceptionlaprofitinformerper   junk_69_985                          
capture rename   exceptionlalossinformerperio   junk_69_986                          
capture rename   exceptionlaprofitonclearance   junk_69_987                          
capture rename   exceptionlalossonclearancesa   junk_69_988                          
capture rename   exceptionlaprofitonamountsdu   junk_69_989                          
capture rename   exceptionlalossonamountsdue    junk_69_990                          
capture rename   exceptionlaprofitonprofitl     junk_69_991                          
capture rename   exceptionlalossonprofitlos     junk_69_992                          
capture rename   familysettlement               junk_69_993                          
capture rename   ptherdebts                     junk_69_994                          
capture rename   creditors                      junk_69_995                          
capture rename   other                          junk_69_996                          
capture rename   cashonhand                     junk_69_997                          
capture rename   investments                    junk_69_998                          
capture rename   debtors                        junk_69_999                          
capture rename   R                              junk_69_1000                         
