capture rename   PurchasesOrdinaryFowlNumber    ORDINARY_FOWL_PURCHASES_NO           
capture rename   PurchasesOrdinaryFowlValue     ORDINARY_FOWL_PURCHASES_EU           
capture rename   PurchasesOtherFowlNumber       OTHER_FOWL_PURCHASES_NO              
capture rename   PurchasesOtherFowlValue        OTHER_FOWL_PURCHASES_EU              
capture rename   SalesOrdinaryFowlNumber        ORDINARY_FOWL_SALES_NO               
capture rename   SalesOrdinaryFowlValue         ORDINARY_FOWL_SALES_EU               
capture rename   SalesOtherFowlNumber           OTHER_FOWL_SALES_NO                  
capture rename   SalesOtherFowlValue            OTHER_FOWL_SALES_EU                  
capture rename   SalesHenEggsDozenNumber        HEN_EGG_DOZEN_SALES_NO               
capture rename   SalesHenEggsDozenValue         HEN_EGG_DOZEN_SALES_EU               
capture rename   SalesOtherEggsDozenNumber      OTHER_EGG_DOZEN_SALES_NO             
capture rename   SalesOtherEggsDozenValue       OTHER_EGG_DOZEN_SALES_EU             
capture rename   Subsidies                      POULTRY_SUBSIDIES_VALUE_EU           
