capture rename   MonthTotalDairyCows            MTH12_TOTAL_DAIRY_COWS_NO            
capture rename   MonthTotalDairyStockBulls      MTH12_TOTAL_DAIRY_STOCK_BULLS_NO     
capture rename   MonthTotalOtherCows            MTH12_TOTAL_OTHER_COWS_NO            
capture rename   MonthTotalHeiferInCalf         MTH12_TOTAL_IN_CALF_HEIFERS_NO       
capture rename   MonthTotalCalveslessthan       MTH12_TOTAL_CALVES_LT6MTHS_NO        
capture rename   MonthTotalCalves612month       MTH12_TOTAL_CALVES_6_12MTHS_NO       
capture rename   MonthTotalCattle12Years        MTH12_TOTAL_CATTLE_1_2YRS_NO         
capture rename   MonthTotalCattleover2Yea       MTH12_TOTAL_CATTLE_GT2YRS_NO         
capture rename   MonthTotalBeefStockBulls       MTH12_TOTAL_BEEF_STOCK_BULLS_NO      
capture rename   MonthTotalallcattle            MTH12_TOTAL_ALL_CATTLE_NO            
