capture rename   PigsPurchasesBreedingStockNu   BREEDING_STOCK_PURCHASES_NO          
capture rename   PigsPurchasesBreedingStockTo   BREEDING_STOCK_PURCHASES_EU          
capture rename   PigsPurchasesBonhamsStores     BONHAMS_STORES_PURCHASES_NO          
capture rename   F                              BONHAMS_STORES_PURCHASES_KGS         
capture rename   G                              BONHAMS_STORES_PURCHASES_EU          
capture rename   SalesBreedingStocknumbers      BREEDING_STOCK_SALES_NO              
capture rename   SalesBreedingStockTotalprice   BREEDING_STOCK_SALES_EU              
capture rename   SalesBonhamsStoresnumbers      BONHAMS_STORES_SALES_NO              
capture rename   SalesBonhamsStoresTotalWei     BONHAMS_STORES_SALES_KGS             
capture rename   SalesBonhamsStoresTotalpri     BONHAMS_STORES_SALES_EU              
capture rename   SalesPorkersBaconPigsnumbe     PORKERS_BACON_SALES_NO               
capture rename   SalesPorkersBaconPigsTotal     PORKERS_BACON_SALES_KGS              
capture rename   O                              PORKERS_BACON_SALES_EU               
